// Generated by apianyware emit-typescript — DO NOT EDIT.
// Type surface: constants (TestKit)
//
// Declaration-only .d.ts, co-generated with constants.ts from the same IR pass
// (ADR-0055 §2): the declared `const` types, no module-load initializers.

import {
  NSString,
} from '@apianyware/foundation';
import type {
  TKAlignment,
} from '@apianyware/testkit';

export const TKDefaultFontName: NSString;
export const TKGreeting: NSString;
export const TKDefaultTimeout: number;
export const TKDefaultAlignment: TKAlignment;
