// Generated by apianyware emit-typescript — DO NOT EDIT.
// Constants: TestKit (module @apianyware/testkit)
//
// Each constant is a module-load-initialized exported `const` (ADR-0055 §6): a CFSTR
// macro built from its literal, a pointer-valued global read + wrapped borrowed, a
// scalar/enum global read — a runtime address is not a TS literal (ADR-0025).

import {
  NSString,
} from '@apianyware/foundation';
import {
  __cfstr,
  __dispatch,
  __wrapOwned,
  __wrapRetained,
} from '@apianyware/runtime';
import type {
  TKAlignment,
} from '@apianyware/testkit';

export const TKDefaultFontName: NSString = __wrapRetained(NSString, __dispatch.aw_ts_const_P('TKDefaultFontName'))!;
export const TKGreeting: NSString = __wrapOwned(NSString, __cfstr('Hello, TestKit'))!;
export const TKDefaultTimeout: number = __dispatch.aw_ts_const_d('TKDefaultTimeout');
export const TKDefaultAlignment: TKAlignment = __dispatch.aw_ts_const_q('TKDefaultAlignment') as TKAlignment;
