// Generated by apianyware emit-typescript — DO NOT EDIT.
// Type surface: delegate specs (TestKit)
//
// Declaration-only .d.ts, co-generated with delegates.ts from the same IR pass
// (ADR-0055 §2). A spec is runtime data, so — unlike protocols.d.ts — this declares
// what that module defines rather than repeating it.

import type { DelegateSpec } from '@apianyware/runtime';

export declare const SPEC_TKRefreshing: DelegateSpec;
export declare const SPEC_TKButtonDelegate: DelegateSpec;
