// Generated by apianyware emit-typescript — DO NOT EDIT.
// Delegate specs: TestKit (module @apianyware/testkit)
//
// One `DelegateSpec` per emitted protocol (ADR-0059 §3/§8): the forwarder-class memo key,
// the installable methods (selector + ObjC type encoding; a method's POSITION is its
// respondsToSelector: bit index), and the inbound value surface — one kind per argument,
// one for the return. A JS object literal reaching any `id<P>` slot is bridged through
// the spec for P (`__protocolArg`, ADR-0055 §4b).
//
// A spec is per PROTOCOL, never per slot: the setter, the association key and the
// associate/skip arm describe a *slot*, and one protocol types many — so the call site
// passes those. And an `obj` kind carries no class (ADR-0059 §8, reconciled by k88's
// dynamic wrap), which is why this module imports nothing but the runtime.

import {
  type DelegateSpec,
  __methodMarshal,
  OBJ,
  RET_OBJ,
  RET_RAW,
} from '@apianyware/runtime';

export const SPEC_TKRefreshing: DelegateSpec = {
  protocol: 'TKRefreshing',
  methods: [
    ['refresh', 'v@:'],
    ['refreshInterval', 'q@:'],
  ],
  marshal: __methodMarshal({
    'refresh': { args: [], ret: RET_RAW },
    'refreshInterval': { args: [], ret: RET_RAW },
  }),
};

export const SPEC_TKButtonDelegate: DelegateSpec = {
  protocol: 'TKButtonDelegate',
  methods: [
    ['didClickButton:', 'v@:@'],
    ['alignmentForButton:', 'q@:@'],
    ['titleForButton:', '@@:@'],
  ],
  marshal: __methodMarshal({
    'didClickButton:': { args: [OBJ], ret: RET_RAW },
    'alignmentForButton:': { args: [OBJ], ret: RET_RAW },
    'titleForButton:': { args: [OBJ], ret: RET_OBJ() },
  }),
};
