// Generated by apianyware emit-typescript — DO NOT EDIT.
// Type surface: enums (TestKit)
//
// Declaration-only .d.ts, co-generated with enums.ts from the same IR pass (ADR-0055
// §2). An enum's member = value, so this body is identical to the enums.ts body —
// runtime and types cannot drift.

export enum TKAlignment {
  TKAlignmentLeft = 0,
  TKAlignmentCenter = 1,
  TKAlignmentRight = 2,
}

export enum TKKeyMask {
  TKKeyMaskNone = 0,
  TKKeyMaskShift = 1,
  TKKeyMaskControl = 2,
  TKKeyMaskOption = 4,
  TKKeyMaskCommand = 8,
  TKKeyMaskAll = 4294967295,
}
