// Generated by apianyware emit-typescript — DO NOT EDIT.
// Enums: TestKit (module @apianyware/testkit)
//
// Real TS enums (ADR-0055 §6): named members, integer values; `const enum` is avoided
// (it breaks isolatedModules/bundlers). An enum carries both a runtime object and a
// type, so its .d.ts is co-generated from the same pass with an identical body.

export enum TKAlignment {
  TKAlignmentLeft = 0,
  TKAlignmentCenter = 1,
  TKAlignmentRight = 2,
}

export enum TKKeyMask {
  TKKeyMaskNone = 0,
  TKKeyMaskShift = 1,
  TKKeyMaskControl = 2,
  TKKeyMaskOption = 4,
  TKKeyMaskCommand = 8,
  TKKeyMaskAll = 4294967295,
}
