// Generated by apianyware emit-typescript — DO NOT EDIT.
// Functions: TestKit (module @apianyware/testkit)
//
// Each free function is a coercion-free dispatch into the addon's per-symbol entry
// (ADR-0054): object args unwrap, scalars pass through, an object return wraps by
// ownership (the CF Create Rule). A Swift-native scalar function binds its
// call-by-name trampoline (aw_ts_swift_*, ADR-0027); non-scalar/variadic defer.

import {
  NSObject,
  __dispatch,
  __unwrap,
  __wrapOwned,
  __wrapRetained,
} from '@apianyware/runtime';
import {
  TKObject,
  TKView,
} from '@apianyware/testkit';
import type {
  TKAlignment,
} from '@apianyware/testkit';

export function TKComputeDistance(x: number, y: number): number {
  return __dispatch.aw_ts_fn_TKComputeDistance(x, y);
}

export function TKViewForObject(obj: NSObject): TKView | null {
  const __ret = __dispatch.aw_ts_fn_TKViewForObject(__unwrap(obj));
  return __wrapRetained(TKView, __ret);
}

export function TKObjectCreate(name: NSObject): TKObject {
  const __ret = __dispatch.aw_ts_fn_TKObjectCreate(__unwrap(name));
  return __wrapOwned(TKObject, __ret)!;
}

export function TKClampAlignment(a: TKAlignment): TKAlignment {
  return __dispatch.aw_ts_fn_TKClampAlignment(a) as TKAlignment;
}

export function TKResetAll(): void {
  __dispatch.aw_ts_fn_TKResetAll();
}

export function TKSwiftScale(factor: number): number {
  return __dispatch.aw_ts_swift_TestKit_TKSwiftScale(factor);
}

export function TKSwiftMakeThing(): TKObject {
  const __ret = __dispatch.aw_ts_swift_TestKit_TKSwiftMakeThing();
  return __wrapOwned(TKObject, __ret)!;
}
