// Generated by apianyware emit-typescript — DO NOT EDIT.
// Type surface: functions (TestKit)
//
// Declaration-only .d.ts, co-generated with functions.ts from the same IR pass
// (ADR-0055 §2): the exported function signatures, no dispatch bodies.

import {
  NSObject,
} from '@apianyware/runtime';
import {
  TKObject,
  TKView,
} from '@apianyware/testkit';
import type {
  TKAlignment,
} from '@apianyware/testkit';

export function TKComputeDistance(x: number, y: number): number;
export function TKViewForObject(obj: NSObject): TKView | null;
export function TKObjectCreate(name: NSObject): TKObject;
export function TKClampAlignment(a: TKAlignment): TKAlignment;
export function TKResetAll(): void;
export function TKSwiftScale(factor: number): number;
export function TKSwiftMakeThing(): TKObject;
