// Generated by apianyware emit-typescript — DO NOT EDIT.
// Protocols: TestKit (module @apianyware/testkit)
//
// Real TS interfaces (ADR-0055 §4): @required → members, @optional → `?` members,
// inherited protocols → `extends` (same-framework in-file; cross-framework imported
// type-only). An interface is type-only, so this module is (essentially) empty at
// runtime — emitted so the barrel's `export *` resolves; its .d.ts is co-generated
// from the same pass with a byte-identical body.

import {
  NSString,
} from '@apianyware/foundation';
import {
  NSObject,
} from '@apianyware/runtime';
import type {
  NSCopying,
} from '@apianyware/foundation';
import type {
  TKAlignment,
} from '@apianyware/testkit';

export interface TKRefreshing {
  refresh(): void;
  refreshInterval?(): number;
}

export interface TKButtonDelegate extends TKRefreshing, NSCopying {
  didClickButton_(button: NSObject): void;
  alignmentForButton_(button: NSObject): TKAlignment;
  titleForButton_?(button: NSObject): NSString | null;
}
