// Generated by apianyware emit-typescript — DO NOT EDIT.
// Type surface: protocols (TestKit)
//
// Declaration-only .d.ts, co-generated with protocols.ts from the same IR pass
// (ADR-0055 §2). An interface is type-only, so this body is identical to the
// protocols.ts body — runtime and types cannot drift.

import {
  NSString,
} from '@apianyware/foundation';
import {
  NSObject,
} from '@apianyware/runtime';
import type {
  NSCopying,
} from '@apianyware/foundation';
import type {
  TKAlignment,
} from '@apianyware/testkit';

export interface TKRefreshing {
  refresh(): void;
  refreshInterval?(): number;
}

export interface TKButtonDelegate extends TKRefreshing, NSCopying {
  didClickButton_(button: NSObject): void;
  alignmentForButton_(button: NSObject): TKAlignment;
  titleForButton_?(button: NSObject): NSString | null;
}
