// Generated by apianyware emit-typescript — DO NOT EDIT.
// Class: TKButton (TestKit)
//
// Runtime seam (Step 3 provides these from '@apianyware/runtime'; ADR-0055/0057):
//   NSObject — branded-handle root class; its internal ctor wraps a handle and hosts
//     [Symbol.dispose]. Emitted subclasses inherit both and declare neither.
//   __unwrap(obj) — obj's native handle (0n for null; throws on a disposed handle).
//   __wrapRetained(Cls, id) / __wrapOwned(Cls, id) — the +0 / +1 uniqued branded
//     wrapper (null when id is 0n; retain folds into the dispatch entry).
//   __class(name) — the Class handle; __sel(sel) — the interned SEL handle.
//   __registerClass(name, cls) — registers this class so a Class RETURN resolves back
//     to it; __classArg(cls) / __classCtor(id) — the Class value crossing, in / out;
//     __selName(sel) — a SEL handle back to its selector-name string.
//   __dispatch.aw_ts_msg_<codes>(recv, sel, …) — the addon's per-signature entry.
//   __init(obj) — the universal `-init` primitive for a class whose real ancestry
//     never redeclares it (k122): the same id -> id dispatch shape a real init() body
//     calls, reused as one shared runtime primitive rather than a per-class copy.

import {
  NSString,
} from '@apianyware/foundation';
import {
  NSObject,
  OBJ,
  RAW,
  RET_OBJ,
  RET_RAW,
  __dispatch,
  __init,
  __protocolArg,
  __registerClass,
  __sel,
  __unwrap,
  __wrapRetained,
} from '@apianyware/runtime';
import {
  SPEC_TKButtonDelegate,
  TKView,
} from '@apianyware/testkit';
import type {
  OverridableMethod,
} from '@apianyware/runtime';
import type {
  TKAlignment,
  TKButtonDelegate,
  TKKeyMask,
} from '@apianyware/testkit';

export class TKButton extends TKView {
  static { __registerClass('TKButton', TKButton); }

  static readonly __overridable: readonly OverridableMethod[] = [
    { name: 'title', selector: 'title', encoding: '@@:', superEntry: 'aw_ts_super_0_P', args: [], ret: RET_OBJ() },
    { name: 'setEnabled_', selector: 'setEnabled:', encoding: 'v@:c', superEntry: 'aw_ts_super_b_v', args: [RAW], ret: RET_RAW },
    { name: 'setDelegate_', selector: 'setDelegate:', encoding: 'v@:@', superEntry: 'aw_ts_super_P_v', args: [OBJ], ret: RET_RAW },
    { name: 'delegate', selector: 'delegate', encoding: '@@:', superEntry: 'aw_ts_super_0_P', args: [], ret: RET_OBJ() },
    { name: 'setAlignment_', selector: 'setAlignment:', encoding: 'v@:q', superEntry: 'aw_ts_super_q_v', args: [RAW], ret: RET_RAW },
    { name: 'keyMask', selector: 'keyMask', encoding: 'I@:', superEntry: 'aw_ts_super_0_I', args: [], ret: RET_RAW },
  ];

  title(): NSString | null {
    const __ret = __dispatch.aw_ts_msg_0_P(__unwrap(this), __sel('title'));
    return __wrapRetained(NSString, __ret);
  }

  setEnabled_(enabled: boolean): void {
    __dispatch.aw_ts_msg_b_v(__unwrap(this), __sel('setEnabled:'), enabled);
  }

  setDelegate_(delegate: TKButtonDelegate): void {
    __dispatch.aw_ts_msg_P_v(__unwrap(this), __sel('setDelegate:'), __protocolArg(__unwrap(this), 'setDelegate:#0', delegate, SPEC_TKButtonDelegate, true));
  }

  delegate(): TKButtonDelegate & NSObject | null {
    const __ret = __dispatch.aw_ts_msg_0_P(__unwrap(this), __sel('delegate'));
    return __wrapRetained<TKButtonDelegate & NSObject>(__ret);
  }

  setAlignment_(alignment: TKAlignment): void {
    __dispatch.aw_ts_msg_q_v(__unwrap(this), __sel('setAlignment:'), alignment);
  }

  keyMask(): TKKeyMask {
    return __dispatch.aw_ts_msg_0_I(__unwrap(this), __sel('keyMask')) as TKKeyMask;
  }

  init(): this {
    return __init(this);
  }
}
