// Generated by apianyware emit-typescript — DO NOT EDIT.
// Type surface: TKButton (TestKit)
//
// Declaration-only .d.ts, co-generated with the .ts class body from one IR pass
// (ADR-0055 §2) so runtime and types cannot drift: the public type surface tsc and
// consumers see — no bodies, no __cls/dispatch internals, no runtime-seam helpers.

import {
  NSString,
} from '@apianyware/foundation';
import {
  NSObject,
} from '@apianyware/runtime';
import {
  TKView,
} from '@apianyware/testkit';
import type {
  TKAlignment,
  TKButtonDelegate,
  TKKeyMask,
} from '@apianyware/testkit';

export class TKButton extends TKView {
  title(): NSString | null;
  setEnabled_(enabled: boolean): void;
  setDelegate_(delegate: TKButtonDelegate): void;
  delegate(): TKButtonDelegate & NSObject | null;
  setAlignment_(alignment: TKAlignment): void;
  keyMask(): TKKeyMask;
  init(): this;
}
