// Generated by apianyware emit-typescript — DO NOT EDIT.
// Class: TKGizmo (TestKit)
//
// Runtime seam (Step 3 provides these from '@apianyware/runtime'; ADR-0055/0057):
//   NSObject — branded-handle root class; its internal ctor wraps a handle and hosts
//     [Symbol.dispose]. Emitted subclasses inherit both and declare neither.
//   __unwrap(obj) — obj's native handle (0n for null; throws on a disposed handle).
//   __wrapRetained(Cls, id) / __wrapOwned(Cls, id) — the +0 / +1 uniqued branded
//     wrapper (null when id is 0n; retain folds into the dispatch entry).
//   __class(name) — the Class handle; __sel(sel) — the interned SEL handle.
//   __registerClass(name, cls) — registers this class so a Class RETURN resolves back
//     to it; __classArg(cls) / __classCtor(id) — the Class value crossing, in / out;
//     __selName(sel) — a SEL handle back to its selector-name string.
//   __dispatch.aw_ts_msg_<codes>(recv, sel, …) — the addon's per-signature entry.
//   __init(obj) — the universal `-init` primitive for a class whose real ancestry
//     never redeclares it (k122): the same id -> id dispatch shape a real init() body
//     calls, reused as one shared runtime primitive rather than a per-class copy.

import {
  RET_RAW,
  __dispatch,
  __init,
  __registerClass,
  __sel,
  __unwrap,
} from '@apianyware/runtime';
import {
  TKMissing,
} from '@apianyware/testkit';
import type {
  OverridableMethod,
} from '@apianyware/runtime';

export class TKGizmo extends TKMissing {
  static { __registerClass('TKGizmo', TKGizmo); }

  static readonly __overridable: readonly OverridableMethod[] = [
    { name: 'reset', selector: 'reset', encoding: 'v@:', superEntry: 'aw_ts_super_0_v', args: [], ret: RET_RAW },
  ];

  reset(): void {
    __dispatch.aw_ts_msg_0_v(__unwrap(this), __sel('reset'));
  }

  init(): this {
    return __init(this);
  }
}
