// Generated by apianyware emit-typescript — DO NOT EDIT.
// Type surface: TKGizmo (TestKit)
//
// Declaration-only .d.ts, co-generated with the .ts class body from one IR pass
// (ADR-0055 §2) so runtime and types cannot drift: the public type surface tsc and
// consumers see — no bodies, no __cls/dispatch internals, no runtime-seam helpers.

import {
  TKMissing,
} from '@apianyware/testkit';

export class TKGizmo extends TKMissing {
  reset(): void;
  init(): this;
}
