// Generated by apianyware emit-typescript — DO NOT EDIT.
// Type surface: TKMissing (TestKit) — synthesized bare class-graph node

import {
  NSObject,
} from '@apianyware/runtime';

export class TKMissing extends NSObject {}
