// Generated by apianyware emit-typescript — DO NOT EDIT.
// Class: TKMissing (TestKit) — synthesized bare class-graph node
//
// Referenced as a superclass but not collected; a minimal root-derived class so the
// extends chain does not dangle (ADR-0055 §2). It still registers: a bare node is a
// real ObjC class, so a Class handle crossing out must resolve to THIS constructor
// rather than degrade to an unbound stand-in (`__classCtor`, classes.ts).

import {
  NSObject,
  __registerClass,
} from '@apianyware/runtime';

export class TKMissing extends NSObject {
  static { __registerClass('TKMissing', TKMissing); }
}
