// Generated by apianyware emit-typescript — DO NOT EDIT.
// Class: TKObject (TestKit)
//
// Runtime seam (Step 3 provides these from '@apianyware/runtime'; ADR-0055/0057):
//   NSObject — branded-handle root class; its internal ctor wraps a handle and hosts
//     [Symbol.dispose]. Emitted subclasses inherit both and declare neither.
//   __unwrap(obj) — obj's native handle (0n for null; throws on a disposed handle).
//   __wrapRetained(Cls, id) / __wrapOwned(Cls, id) — the +0 / +1 uniqued branded
//     wrapper (null when id is 0n; retain folds into the dispatch entry).
//   __class(name) — the Class handle; __sel(sel) — the interned SEL handle.
//   __registerClass(name, cls) — registers this class so a Class RETURN resolves back
//     to it; __classArg(cls) / __classCtor(id) — the Class value crossing, in / out;
//     __selName(sel) — a SEL handle back to its selector-name string.
//   __dispatch.aw_ts_msg_<codes>(recv, sel, …) — the addon's per-signature entry.
//   Result<T> / __resultRetained(Cls, r) / __resultOwned(Cls, r) / __resultScalar(r)
//     — the NSError** → Result<T> channel (ADR-0058): the addon's `…_e` entry keys
//     failure on the primary return + @catches, the runtime builds the discriminated
//     union (ok:false carries the wrapped NSError).
//   __init(obj) — the universal `-init` primitive for a class whose real ancestry
//     never redeclares it (k122): the same id -> id dispatch shape a real init() body
//     calls, reused as one shared runtime primitive rather than a per-class copy.

import {
  NSString,
} from '@apianyware/foundation';
import {
  NSObject,
  OBJ,
  RAW,
  RET_OBJ,
  RET_RAW,
  __class,
  __dispatch,
  __init,
  __registerClass,
  __resultRetained,
  __resultScalar,
  __sel,
  __unwrap,
  __wrapRetained,
} from '@apianyware/runtime';
import type {
  OverridableMethod,
  Result,
} from '@apianyware/runtime';

export class TKObject extends NSObject {
  static { __registerClass('TKObject', TKObject); }

  static readonly __overridable: readonly OverridableMethod[] = [
    { name: 'name', selector: 'name', encoding: '@@:', superEntry: 'aw_ts_super_0_P', args: [], ret: RET_OBJ() },
    { name: 'setTag_', selector: 'setTag:', encoding: 'v@:q', superEntry: 'aw_ts_super_q_v', args: [RAW], ret: RET_RAW },
    { name: 'tag', selector: 'tag', encoding: 'q@:', superEntry: 'aw_ts_super_0_q', args: [], ret: RET_RAW },
    { name: 'writeToFile_error_', selector: 'writeToFile:error:', encoding: 'c@:@@', superEntry: 'aw_ts_super_PP_b', args: [OBJ, RAW], ret: RET_RAW },
  ];

  static readonly __cls: bigint = __class('TKObject');

  static objectWithName_(name: NSObject): TKObject {
    const __ret = __dispatch.aw_ts_msg_P_P(TKObject.__cls, __sel('objectWithName:'), __unwrap(name));
    return __wrapRetained(TKObject, __ret)!;
  }

  static objectFromFile_error_(path: NSString): Result<TKObject> {
    return __resultRetained(TKObject, __dispatch.aw_ts_msg_P_P_e(TKObject.__cls, __sel('objectFromFile:error:'), __unwrap(path)));
  }

  name(): NSString | null {
    const __ret = __dispatch.aw_ts_msg_0_P(__unwrap(this), __sel('name'));
    return __wrapRetained(NSString, __ret);
  }

  setTag_(tag: number): void {
    __dispatch.aw_ts_msg_q_v(__unwrap(this), __sel('setTag:'), tag);
  }

  tag(): number {
    return __dispatch.aw_ts_msg_0_q(__unwrap(this), __sel('tag'));
  }

  writeToFile_error_(path: NSString): Result<boolean> {
    return __resultScalar(__dispatch.aw_ts_msg_P_b_e(__unwrap(this), __sel('writeToFile:error:'), __unwrap(path)));
  }

  init(): this {
    return __init(this);
  }
}
