// Generated by apianyware emit-typescript — DO NOT EDIT.
// Type surface: TKObject (TestKit)
//
// Declaration-only .d.ts, co-generated with the .ts class body from one IR pass
// (ADR-0055 §2) so runtime and types cannot drift: the public type surface tsc and
// consumers see — no bodies, no __cls/dispatch internals, no runtime-seam helpers.

import {
  NSString,
} from '@apianyware/foundation';
import {
  NSObject,
} from '@apianyware/runtime';
import type {
  Result,
} from '@apianyware/runtime';

export class TKObject extends NSObject {
  static objectWithName_(name: NSObject): TKObject;
  static objectFromFile_error_(path: NSString): Result<TKObject>;
  name(): NSString | null;
  setTag_(tag: number): void;
  tag(): number;
  writeToFile_error_(path: NSString): Result<boolean>;
  init(): this;
}
