// Generated by apianyware emit-typescript — DO NOT EDIT.
// Type surface: TKView (TestKit)
//
// Declaration-only .d.ts, co-generated with the .ts class body from one IR pass
// (ADR-0055 §2) so runtime and types cannot drift: the public type surface tsc and
// consumers see — no bodies, no __cls/dispatch internals, no runtime-seam helpers.

import {
  TKObject,
} from '@apianyware/testkit';
import type {
  TKRefreshing,
} from '@apianyware/testkit';

export class TKView extends TKObject implements TKRefreshing {
  initWithParent_(parent: TKObject): this | null;
  addSubview_(view: TKView): void;
  superview(): TKView | null;
  refresh(): void;
  init(): this;
}
