;;; Generated TestKit bindings (gerbil-bindings package) — re-export facade
(import
  :gerbil-bindings/testkit/tkobject
  :gerbil-bindings/testkit/tkview
  :gerbil-bindings/testkit/tkbutton
  :gerbil-bindings/testkit/tkmanager
  :gerbil-bindings/testkit/tkhelper
  :gerbil-bindings/testkit/protocols/tkcopying
  :gerbil-bindings/testkit/protocols/tkdelegate
  :gerbil-bindings/testkit/enums
  :gerbil-bindings/testkit/constants
  :gerbil-bindings/testkit/functions
  )
(export
  TKAlignmentCenter
  TKAlignmentLeft
  TKAlignmentRight
  TKButton
  TKButton?
  TKComputeDistance
  TKCreateBuffer
  TKDefaultTimeout
  TKGetName
  TKHelper
  TKHelper?
  TKManager
  TKManager?
  TKObject
  TKObject?
  TKRegisterCallback
  TKReset
  TKStatusAttribute
  TKTransformPoint
  TKVersionString
  TKView
  TKView?
  animate-with-duration-animations
  dealloc
  description
  enabled
  frame
  hidden
  is-highlighted
  label
  load-resource-error
  make-tkbutton
  make-tkcopying
  make-tkdelegate
  make-tkhelper
  make-tkmanager
  make-tkobject
  make-tkview-init-with-frame
  resource-named
  set-enabled!
  set-frame!
  set-hidden!
  set-label!
  set-needs-display!
  set-tag!
  set-target-action!
  set-title!
  tag
  title
  tkbutton-enabled
  tkbutton-is-highlighted
  tkbutton-label
  tkbutton-set-enabled!
  tkbutton-set-label!
  tkbutton-set-target-action!
  tkcopying-selectors
  tkdelegate-selectors
  tkhelper-maximum-count
  tkhelper-version-string
  tkmanager-load-resource-error
  tkmanager-resource-named
  tkmanager-shared-manager
  tkobject-dealloc
  tkobject-description
  tkview-animate-with-duration-animations
  tkview-appearance
  tkview-frame
  tkview-hidden
  tkview-set-frame!
  tkview-set-hidden!
  tkview-set-needs-display!
  tkview-set-tag!
  tkview-set-title!
  tkview-tag
  tkview-title
  )
