;;; Generated Foundation bindings — NSString — class + dispatch (ADR-0034) — do not edit
(in-package #:apianyware-sbcl-impl)

;; --- NSString (Foundation) — metaclass-backed class (ADR-0034) ---
(defclass ns:ns-string (ns:ns-object) () (:metaclass objc-class))
(register-objc-class 'ns:ns-string "NSString" "NSObject")

;; --- NSString (Foundation) — dispatch (ADR-0034 §2) ---
(defmethod ns:length ((self ns:ns-string))
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:unsigned 64) sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "length")))
(defmethod ns:double-value ((self ns:ns-string))
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:double sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "doubleValue")))
(defmethod ns:float-value ((self ns:ns-string))
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:float sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "floatValue")))
(defmethod ns:int-value ((self ns:ns-string))
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:signed 32) sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "intValue")))
(defmethod ns:integer-value ((self ns:ns-string))
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:signed 64) sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "integerValue")))
(defmethod ns:long-long-value ((self ns:ns-string))
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:signed 64) sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "longLongValue")))
(defmethod ns:bool-value ((self ns:ns-string))
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:boolean 8) sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "boolValue")))
(defmethod ns:uppercase-string ((self ns:ns-string))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "uppercaseString")) t))
(defmethod ns:lowercase-string ((self ns:ns-string))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "lowercaseString")) t))
(defmethod ns:capitalized-string ((self ns:ns-string))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "capitalizedString")) t))
(defmethod ns:localized-uppercase-string ((self ns:ns-string))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "localizedUppercaseString")) t))
(defmethod ns:localized-lowercase-string ((self ns:ns-string))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "localizedLowercaseString")) t))
(defmethod ns:localized-capitalized-string ((self ns:ns-string))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "localizedCapitalizedString")) t))
(defmethod ns:utf8-string ((self ns:ns-string))
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:c-string sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "UTF8String")))
(defmethod ns:fastest-encoding ((self ns:ns-string))
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:unsigned 64) sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "fastestEncoding")))
(defmethod ns:smallest-encoding ((self ns:ns-string))
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:unsigned 64) sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "smallestEncoding")))
(defmethod ns:available-string-encodings ((class (eql (find-class 'ns:ns-string))))
  (declare (ignore class))
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-class "NSString") (aw-sel "availableStringEncodings")))
(defmethod ns:default-c-string-encoding ((class (eql (find-class 'ns:ns-string))))
  (declare (ignore class))
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:unsigned 64) sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-class "NSString") (aw-sel "defaultCStringEncoding")))
(defmethod ns:decomposed-string-with-canonical-mapping ((self ns:ns-string))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "decomposedStringWithCanonicalMapping")) t))
(defmethod ns:precomposed-string-with-canonical-mapping ((self ns:ns-string))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "precomposedStringWithCanonicalMapping")) t))
(defmethod ns:decomposed-string-with-compatibility-mapping ((self ns:ns-string))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "decomposedStringWithCompatibilityMapping")) t))
(defmethod ns:precomposed-string-with-compatibility-mapping ((self ns:ns-string))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "precomposedStringWithCompatibilityMapping")) t))
(defmethod ns:description ((self ns:ns-string))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "description")) t))
(defmethod ns:hash ((self ns:ns-string))
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:unsigned 64) sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "hash")))
(defmethod ns:path-components ((self ns:ns-string))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "pathComponents")) t))
(defmethod ns:absolute-path ((self ns:ns-string))
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:boolean 8) sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "absolutePath")))
(defmethod ns:last-path-component ((self ns:ns-string))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "lastPathComponent")) t))
(defmethod ns:string-by-deleting-last-path-component ((self ns:ns-string))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "stringByDeletingLastPathComponent")) t))
(defmethod ns:path-extension ((self ns:ns-string))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "pathExtension")) t))
(defmethod ns:string-by-deleting-path-extension ((self ns:ns-string))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "stringByDeletingPathExtension")) t))
(defmethod ns:string-by-abbreviating-with-tilde-in-path ((self ns:ns-string))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "stringByAbbreviatingWithTildeInPath")) t))
(defmethod ns:string-by-expanding-tilde-in-path ((self ns:ns-string))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "stringByExpandingTildeInPath")) t))
(defmethod ns:string-by-standardizing-path ((self ns:ns-string))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "stringByStandardizingPath")) t))
(defmethod ns:string-by-resolving-symlinks-in-path ((self ns:ns-string))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "stringByResolvingSymlinksInPath")) t))
(defmethod ns:file-system-representation ((self ns:ns-string))
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:c-string sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "fileSystemRepresentation")))
(defmethod ns:string-by-removing-percent-encoding ((self ns:ns-string))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "stringByRemovingPercentEncoding")) t))
(defmethod ns:character-at-index_ ((self ns:ns-string) index)
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:unsigned 16) sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:unsigned 64))) (aw-ptr self) (aw-sel "characterAtIndex:") index))
(defmethod ns:encode-with-coder_ ((self ns:ns-string) coder)
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:void sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "encodeWithCoder:") (aw-ptr coder)))
(defmethod ns:item-provider-visibility-for-representation-with-type-identifier_ ((self ns:ns-string) type-identifier)
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:signed 64) sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "itemProviderVisibilityForRepresentationWithTypeIdentifier:") (aw-ptr type-identifier)))
(defmethod ns:load-data-with-type-identifier_for-item-provider-completion-handler_ ((self ns:ns-string) type-identifier completion-handler)
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "loadDataWithTypeIdentifier:forItemProviderCompletionHandler:") (aw-ptr type-identifier) (aw-block completion-handler))))
(defmethod ns:writable-type-identifiers-for-item-provider ((self ns:ns-string))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "writableTypeIdentifiersForItemProvider"))))
(defmethod ns:object-with-item-provider-data_type-identifier_error_ ((class (eql (find-class 'ns:ns-string))) data type-identifier)
  (declare (ignore class))
  (aw-with-error-cell (%err)
    (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-class "NSString") (aw-sel "objectWithItemProviderData:typeIdentifier:error:") (aw-ptr data) (aw-ptr type-identifier) %err))))
(defmethod ns:readable-type-identifiers-for-item-provider ((class (eql (find-class 'ns:ns-string))))
  (declare (ignore class))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-class "NSString") (aw-sel "readableTypeIdentifiersForItemProvider"))))
(defmethod ns:supports-secure-coding ((class (eql (find-class 'ns:ns-string))))
  (declare (ignore class))
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:boolean 8) sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-class "NSString") (aw-sel "supportsSecureCoding")))
(register-objc-init 'ns:ns-string "initWithCoder:" (:init-with-coder) (lambda (%alloced %args) (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) %alloced (aw-sel "initWithCoder:") (aw-ptr (getf %args :init-with-coder)))))

;; --- NSString (Foundation) — Swift-native residual (receiver-handle trampolines, ADR-0038) ---
(defun ns:make-ns-string-string (string)
  (aw-wrap (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_init_Foundation_NSString_bd6dd38a" (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-swift-string-arg string)) t))

