(in-package #:apianyware-sbcl-impl)

;;; Generated Foundation bindings — Swift-native value-struct residual (ADR-0042) — do not edit

;; --- CharacterSet (Foundation) — Swift-native value-struct residual (ADR-0042) ---
(defclass ns:character-set (ns:value-struct) ())
(defmethod ns:has-member-in-plane ((self ns:character-set) in-plane)
  (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_m_Foundation_CharacterSet_hasMember" (sb-alien:function (sb-alien:boolean 8) sb-alien:system-area-pointer (sb-alien:unsigned 8))) (aw-ptr self) in-plane))
(defmethod ns:insert-characters-in ((self ns:character-set) characters-in)
  (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_m_Foundation_CharacterSet_insert_95925dba" (sb-alien:function sb-alien:void sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-swift-string-arg characters-in)))
(defmethod ns:remove-characters-in ((self ns:character-set) characters-in)
  (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_m_Foundation_CharacterSet_remove_52b61c01" (sb-alien:function sb-alien:void sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-swift-string-arg characters-in)))
(defmethod ns:invert ((self ns:character-set))
  (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_m_Foundation_CharacterSet_invert" (sb-alien:function sb-alien:void sb-alien:system-area-pointer)) (aw-ptr self)))
(defun ns:make-character-set ()
  (make-instance 'ns:character-set :ptr (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_init_Foundation_CharacterSet_d0f648ae" (sb-alien:function sb-alien:system-area-pointer)))))
(defun ns:make-character-set-characters-in (characters-in)
  (make-instance 'ns:character-set :ptr (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_init_Foundation_CharacterSet_65eb7364" (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-swift-string-arg characters-in))))
(defun ns:make-character-set-contents-of-file (contents-of-file)
  (make-instance 'ns:character-set :ptr (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_init_Foundation_CharacterSet_6ea6127c" (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-swift-string-arg contents-of-file))))
;; --- PersonNameComponents (Foundation) — Swift-native value-struct residual (ADR-0042) ---
(defclass ns:person-name-components (ns:value-struct) ())
(defmethod ns:formatted ((self ns:person-name-components))
  (aw-swift-string-result (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_m_Foundation_PersonNameComponents_formatted_0659424c" (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self))))
(defun ns:make-person-name-components ()
  (make-instance 'ns:person-name-components :ptr (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_init_Foundation_PersonNameComponents_edec75ad" (sb-alien:function sb-alien:system-area-pointer)))))
;; --- Morphology (Foundation) — Swift-native value-struct residual (ADR-0042) ---
(defclass ns:morphology (ns:value-struct) ())
(defmethod ns:custom-pronoun-for-language ((self ns:morphology) for-language)
  (aw-wrap (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_m_Foundation_Morphology_customPronoun" (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-swift-string-arg for-language)) t))
(defun ns:make-morphology ()
  (make-instance 'ns:morphology :ptr (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_init_Foundation_Morphology_dc2edebc" (sb-alien:function sb-alien:system-area-pointer)))))
;; --- IndexSet (Foundation) — Swift-native value-struct residual (ADR-0042) ---
(defclass ns:index-set (ns:value-struct) ())
(defmethod ns:make-iterator ((self ns:index-set))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_m_Foundation_IndexSet_makeIterator" (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self)) t))
(defmethod ns:contains ((self ns:index-set) arg0)
  (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_m_Foundation_IndexSet_contains_077304da" (sb-alien:function (sb-alien:boolean 8) sb-alien:system-area-pointer (sb-alien:signed 64))) (aw-ptr self) arg0))
(defmethod ns:insert ((self ns:index-set) arg0)
  (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_m_Foundation_IndexSet_insert_27a24baa" (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:signed 64))) (aw-ptr self) arg0))
(defmethod ns:remove-all ((self ns:index-set))
  (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_m_Foundation_IndexSet_removeAll" (sb-alien:function sb-alien:void sb-alien:system-area-pointer)) (aw-ptr self)))
(defmethod ns:shift-starting-at-by ((self ns:index-set) starting-at by)
  (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_m_Foundation_IndexSet_shift" (sb-alien:function sb-alien:void sb-alien:system-area-pointer (sb-alien:signed 64) (sb-alien:signed 64))) (aw-ptr self) starting-at by))
(defun ns:make-index-set-integer (integer)
  (make-instance 'ns:index-set :ptr (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_init_Foundation_IndexSet_15866e27" (sb-alien:function sb-alien:system-area-pointer (sb-alien:signed 64))) integer)))
(defun ns:make-index-set ()
  (make-instance 'ns:index-set :ptr (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_init_Foundation_IndexSet_fab6d2fb" (sb-alien:function sb-alien:system-area-pointer)))))
;; --- AttributeContainer (Foundation) — Swift-native value-struct residual (ADR-0042) ---
(defclass ns:attribute-container (ns:value-struct) ())
(defmethod ns:filter-inherited-by-added-text ((self ns:attribute-container) inherited-by-added-text)
  (aw-wrap (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_m_Foundation_AttributeContainer_filter_5c8fba4d" (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:boolean 8))) (aw-ptr self) inherited-by-added-text) t))
(defun ns:make-attribute-container ()
  (make-instance 'ns:attribute-container :ptr (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_init_Foundation_AttributeContainer_95452245" (sb-alien:function sb-alien:system-area-pointer)))))
;; --- AttributedString (Foundation) — Swift-native value-struct residual (ADR-0042) ---
(defclass ns:attributed-string (ns:value-struct) ())
(defmethod ns:inflected ((self ns:attributed-string))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_m_Foundation_AttributedString_inflected_d9496ebc" (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self)) t))
(defun ns:make-attributed-string ()
  (make-instance 'ns:attributed-string :ptr (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_init_Foundation_AttributedString_3c249066" (sb-alien:function sb-alien:system-area-pointer)))))
(defun ns:make-attributed-string-string-literal (string-literal)
  (make-instance 'ns:attributed-string :ptr (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_init_Foundation_AttributedString_bebd6a40" (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-swift-string-arg string-literal))))
;; --- AttributedSubstring (Foundation) — Swift-native value-struct residual (ADR-0042) ---
(defclass ns:attributed-substring (ns:value-struct) ())
(defun ns:make-attributed-substring ()
  (make-instance 'ns:attributed-substring :ptr (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_init_Foundation_AttributedSubstring" (sb-alien:function sb-alien:system-area-pointer)))))
;; --- Data (Foundation) — Swift-native value-struct residual (ADR-0042) ---
(defclass ns:data (ns:value-struct) ())
(defmethod ns:reserve-capacity ((self ns:data) arg0)
  (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_m_Foundation_Data_reserveCapacity" (sb-alien:function sb-alien:void sb-alien:system-area-pointer (sb-alien:signed 64))) (aw-ptr self) arg0))
(defmethod ns:advanced-by ((self ns:data) by)
  (aw-wrap (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_m_Foundation_Data_advanced" (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:signed 64))) (aw-ptr self) by) t))
(defmethod ns:index-before ((self ns:data) before)
  (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_m_Foundation_Data_index_b6d8f102" (sb-alien:function (sb-alien:signed 64) sb-alien:system-area-pointer (sb-alien:signed 64))) (aw-ptr self) before))
(defmethod ns:index-after ((self ns:data) after)
  (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_m_Foundation_Data_index_e174a67d" (sb-alien:function (sb-alien:signed 64) sb-alien:system-area-pointer (sb-alien:signed 64))) (aw-ptr self) after))
(defmethod ns:make-iterator ((self ns:data))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_m_Foundation_Data_makeIterator" (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self)) t))
(defun ns:make-data-repeating-count (repeating count)
  (make-instance 'ns:data :ptr (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_init_Foundation_Data_60339ea6" (sb-alien:function sb-alien:system-area-pointer (sb-alien:unsigned 8) (sb-alien:signed 64))) repeating count)))
(defun ns:make-data-capacity (capacity)
  (make-instance 'ns:data :ptr (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_init_Foundation_Data_0569fb74" (sb-alien:function sb-alien:system-area-pointer (sb-alien:signed 64))) capacity)))
(defun ns:make-data-count (count)
  (make-instance 'ns:data :ptr (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_init_Foundation_Data_77e73120" (sb-alien:function sb-alien:system-area-pointer (sb-alien:signed 64))) count)))
(defun ns:make-data ()
  (make-instance 'ns:data :ptr (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_init_Foundation_Data_1b7523c5" (sb-alien:function sb-alien:system-area-pointer)))))
;; --- Locale (Foundation) — Swift-native value-struct residual (ADR-0042) ---
(defclass ns:locale (ns:value-struct) ())
(defmethod ns:localized-string-for-identifier ((self ns:locale) for-identifier)
  (aw-swift-string-result (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_m_Foundation_Locale_localizedString_99adc185" (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-swift-string-arg for-identifier))))
(defmethod ns:localized-string-for-language-code ((self ns:locale) for-language-code)
  (aw-swift-string-result (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_m_Foundation_Locale_localizedString_32f9698e" (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-swift-string-arg for-language-code))))
(defmethod ns:localized-string-for-region-code ((self ns:locale) for-region-code)
  (aw-swift-string-result (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_m_Foundation_Locale_localizedString_6dd0859b" (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-swift-string-arg for-region-code))))
(defmethod ns:localized-string-for-script-code ((self ns:locale) for-script-code)
  (aw-swift-string-result (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_m_Foundation_Locale_localizedString_fe2ac4c5" (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-swift-string-arg for-script-code))))
(defmethod ns:localized-string-for-variant-code ((self ns:locale) for-variant-code)
  (aw-swift-string-result (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_m_Foundation_Locale_localizedString_12adba57" (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-swift-string-arg for-variant-code))))
(defmethod ns:localized-string-for-currency-code ((self ns:locale) for-currency-code)
  (aw-swift-string-result (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_m_Foundation_Locale_localizedString_3f0a3da8" (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-swift-string-arg for-currency-code))))
(defmethod ns:localized-string-for-collation-identifier ((self ns:locale) for-collation-identifier)
  (aw-swift-string-result (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_m_Foundation_Locale_localizedString_b81eeb7f" (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-swift-string-arg for-collation-identifier))))
(defmethod ns:localized-string-for-collator-identifier ((self ns:locale) for-collator-identifier)
  (aw-swift-string-result (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_m_Foundation_Locale_localizedString_36664c43" (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-swift-string-arg for-collator-identifier))))
(defun ns:make-locale-identifier (identifier)
  (make-instance 'ns:locale :ptr (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_init_Foundation_Locale_e44f9eed" (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-swift-string-arg identifier))))
;; --- PredicateCodableConfiguration (Foundation) — Swift-native value-struct residual (ADR-0042) ---
(defclass ns:predicate-codable-configuration (ns:value-struct) ())
(defun ns:make-predicate-codable-configuration ()
  (make-instance 'ns:predicate-codable-configuration :ptr (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_init_Foundation_PredicateCodableConfiguration" (sb-alien:function sb-alien:system-area-pointer)))))
;; --- TimeZone (Foundation) — Swift-native value-struct residual (ADR-0042) ---
(defclass ns:time-zone (ns:value-struct) ())
(defun ns:make-time-zone-identifier (identifier)
  (make-instance 'ns:time-zone :ptr (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_init_Foundation_TimeZone_6cb5a22c" (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-swift-string-arg identifier))))
(defun ns:make-time-zone-seconds-from-gmt (seconds-from-gmt)
  (make-instance 'ns:time-zone :ptr (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_init_Foundation_TimeZone_59a8c1ca" (sb-alien:function sb-alien:system-area-pointer (sb-alien:signed 64))) seconds-from-gmt)))
(defun ns:make-time-zone-abbreviation (abbreviation)
  (make-instance 'ns:time-zone :ptr (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_init_Foundation_TimeZone_cac74a72" (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-swift-string-arg abbreviation))))
;; --- URLResourceValues (Foundation) — Swift-native value-struct residual (ADR-0042) ---
(defclass ns:url-resource-values (ns:value-struct) ())
(defun ns:make-url-resource-values ()
  (make-instance 'ns:url-resource-values :ptr (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_init_Foundation_URLResourceValues" (sb-alien:function sb-alien:system-area-pointer)))))
;; --- URL (Foundation) — Swift-native value-struct residual (ADR-0042) ---
(defclass ns:url (ns:value-struct) ())
(defmethod ns:host-percent-encoded ((self ns:url) percent-encoded)
  (aw-swift-string-result (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_m_Foundation_URL_host" (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:boolean 8))) (aw-ptr self) percent-encoded)))
(defmethod ns:user-percent-encoded ((self ns:url) percent-encoded)
  (aw-swift-string-result (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_m_Foundation_URL_user" (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:boolean 8))) (aw-ptr self) percent-encoded)))
(defmethod ns:password-percent-encoded ((self ns:url) percent-encoded)
  (aw-swift-string-result (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_m_Foundation_URL_password" (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:boolean 8))) (aw-ptr self) percent-encoded)))
(defmethod ns:path-percent-encoded ((self ns:url) percent-encoded)
  (aw-swift-string-result (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_m_Foundation_URL_path" (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:boolean 8))) (aw-ptr self) percent-encoded)))
(defmethod ns:query-percent-encoded ((self ns:url) percent-encoded)
  (aw-swift-string-result (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_m_Foundation_URL_query" (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:boolean 8))) (aw-ptr self) percent-encoded)))
(defmethod ns:fragment-percent-encoded ((self ns:url) percent-encoded)
  (aw-swift-string-result (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_m_Foundation_URL_fragment" (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:boolean 8))) (aw-ptr self) percent-encoded)))
(defmethod ns:appending-path-component-is-directory ((self ns:url) arg0 is-directory)
  (aw-wrap (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_m_Foundation_URL_appendingPathComponent_139fa27e" (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:boolean 8))) (aw-ptr self) (aw-swift-string-arg arg0) is-directory) t))
(defmethod ns:appending-path-component ((self ns:url) arg0)
  (aw-wrap (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_m_Foundation_URL_appendingPathComponent_b45bd20d" (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-swift-string-arg arg0)) t))
(defmethod ns:deleting-last-path-component ((self ns:url))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_m_Foundation_URL_deletingLastPathComponent" (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self)) t))
(defmethod ns:appending-path-extension ((self ns:url) arg0)
  (aw-wrap (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_m_Foundation_URL_appendingPathExtension" (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-swift-string-arg arg0)) t))
(defmethod ns:deleting-path-extension ((self ns:url))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_m_Foundation_URL_deletingPathExtension" (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self)) t))
(defmethod ns:append-path-component-is-directory ((self ns:url) arg0 is-directory)
  (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_m_Foundation_URL_appendPathComponent_c5f2a958" (sb-alien:function sb-alien:void sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:boolean 8))) (aw-ptr self) (aw-swift-string-arg arg0) is-directory))
(defmethod ns:append-path-component ((self ns:url) arg0)
  (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_m_Foundation_URL_appendPathComponent_a440c5b1" (sb-alien:function sb-alien:void sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-swift-string-arg arg0)))
(defmethod ns:append-path-extension ((self ns:url) arg0)
  (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_m_Foundation_URL_appendPathExtension" (sb-alien:function sb-alien:void sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-swift-string-arg arg0)))
(defmethod ns:delete-last-path-component ((self ns:url))
  (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_m_Foundation_URL_deleteLastPathComponent" (sb-alien:function sb-alien:void sb-alien:system-area-pointer)) (aw-ptr self)))
(defmethod ns:delete-path-extension ((self ns:url))
  (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_m_Foundation_URL_deletePathExtension" (sb-alien:function sb-alien:void sb-alien:system-area-pointer)) (aw-ptr self)))
(defmethod ns:standardize ((self ns:url))
  (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_m_Foundation_URL_standardize" (sb-alien:function sb-alien:void sb-alien:system-area-pointer)) (aw-ptr self)))
(defmethod ns:resolving-symlinks-in-path ((self ns:url))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_m_Foundation_URL_resolvingSymlinksInPath" (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self)) t))
(defmethod ns:resolve-symlinks-in-path ((self ns:url))
  (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_m_Foundation_URL_resolveSymlinksInPath" (sb-alien:function sb-alien:void sb-alien:system-area-pointer)) (aw-ptr self)))
(defmethod ns:check-resource-is-reachable ((self ns:url))
  (aw-swift-call/error (%err)
    (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_m_Foundation_URL_checkResourceIsReachable" (sb-alien:function (sb-alien:boolean 8) sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) %err)))
(defmethod ns:check-promised-item-is-reachable ((self ns:url))
  (aw-swift-call/error (%err)
    (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_m_Foundation_URL_checkPromisedItemIsReachable" (sb-alien:function (sb-alien:boolean 8) sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) %err)))
(defmethod ns:remove-all-cached-resource-values ((self ns:url))
  (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_m_Foundation_URL_removeAllCachedResourceValues" (sb-alien:function sb-alien:void sb-alien:system-area-pointer)) (aw-ptr self)))
(defmethod ns:start-accessing-security-scoped-resource ((self ns:url))
  (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_m_Foundation_URL_startAccessingSecurityScopedResource" (sb-alien:function (sb-alien:boolean 8) sb-alien:system-area-pointer)) (aw-ptr self)))
(defmethod ns:stop-accessing-security-scoped-resource ((self ns:url))
  (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_m_Foundation_URL_stopAccessingSecurityScopedResource" (sb-alien:function sb-alien:void sb-alien:system-area-pointer)) (aw-ptr self)))
(defmethod ns:formatted ((self ns:url))
  (aw-swift-string-result (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_m_Foundation_URL_formatted_0659424c" (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self))))
(defun ns:make-url-string (string)
  (make-instance 'ns:url :ptr (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_init_Foundation_URL_f9d049ea" (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-swift-string-arg string))))
(defun ns:make-url-string-encoding-invalid-characters (string encoding-invalid-characters)
  (make-instance 'ns:url :ptr (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_init_Foundation_URL_ac210810" (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:boolean 8))) (aw-swift-string-arg string) encoding-invalid-characters)))
(defun ns:make-url-file-url-with-path-is-directory (file-url-with-path is-directory)
  (make-instance 'ns:url :ptr (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_init_Foundation_URL_1d741432" (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:boolean 8))) (aw-swift-string-arg file-url-with-path) is-directory)))
(defun ns:make-url-file-url-with-path (file-url-with-path)
  (make-instance 'ns:url :ptr (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_init_Foundation_URL_35032f07" (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-swift-string-arg file-url-with-path))))
(defun ns:make-url-file-reference-literal-resource-name (file-reference-literal-resource-name)
  (make-instance 'ns:url :ptr (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_init_Foundation_URL_9818bd67" (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-swift-string-arg file-reference-literal-resource-name))))
;; --- URLComponents (Foundation) — Swift-native value-struct residual (ADR-0042) ---
(defclass ns:url-components (ns:value-struct) ())
(defmethod ns:url-relative-to ((self ns:url-components) relative-to)
  (aw-wrap (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_m_Foundation_URLComponents_url" (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-ptr relative-to)) t))
(defun ns:make-url-components ()
  (make-instance 'ns:url-components :ptr (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_init_Foundation_URLComponents_73ae299f" (sb-alien:function sb-alien:system-area-pointer)))))
(defun ns:make-url-components-string (string)
  (make-instance 'ns:url-components :ptr (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_init_Foundation_URLComponents_c3af778b" (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-swift-string-arg string))))
(defun ns:make-url-components-string-encoding-invalid-characters (string encoding-invalid-characters)
  (make-instance 'ns:url-components :ptr (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_init_Foundation_URLComponents_640d5e3c" (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:boolean 8))) (aw-swift-string-arg string) encoding-invalid-characters)))
;; --- URLQueryItem (Foundation) — Swift-native value-struct residual (ADR-0042) ---
(defclass ns:url-query-item (ns:value-struct) ())
(defun ns:make-url-query-item-name-value (name value)
  (make-instance 'ns:url-query-item :ptr (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_init_Foundation_URLQueryItem" (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-swift-string-arg name) (aw-swift-string-arg value))))
;; --- Date (Foundation) — Swift-native value-struct residual (ADR-0042) ---
(defclass ns:date (ns:value-struct) ())
(defmethod ns:adding-time-interval ((self ns:date) arg0)
  (aw-wrap (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_m_Foundation_Date_addingTimeInterval" (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:double)) (aw-ptr self) arg0) t))
(defmethod ns:add-time-interval ((self ns:date) arg0)
  (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_m_Foundation_Date_addTimeInterval" (sb-alien:function sb-alien:void sb-alien:system-area-pointer sb-alien:double)) (aw-ptr self) arg0))
(defmethod ns:formatted ((self ns:date))
  (aw-swift-string-result (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_m_Foundation_Date_formatted_0659424c" (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self))))
(defmethod ns:advanced-by ((self ns:date) by)
  (aw-wrap (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_m_Foundation_Date_advanced" (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:double)) (aw-ptr self) by) t))
(defun ns:make-date ()
  (make-instance 'ns:date :ptr (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_init_Foundation_Date_1b8fe179" (sb-alien:function sb-alien:system-area-pointer)))))
(defun ns:make-date-time-interval-since-now (time-interval-since-now)
  (make-instance 'ns:date :ptr (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_init_Foundation_Date_68faa683" (sb-alien:function sb-alien:system-area-pointer sb-alien:double)) time-interval-since-now)))
(defun ns:make-date-time-interval-since1970 (time-interval-since1970)
  (make-instance 'ns:date :ptr (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_init_Foundation_Date_62ad0b28" (sb-alien:function sb-alien:system-area-pointer sb-alien:double)) time-interval-since1970)))
(defun ns:make-date-time-interval-since-reference-date (time-interval-since-reference-date)
  (make-instance 'ns:date :ptr (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_init_Foundation_Date_ced6b451" (sb-alien:function sb-alien:system-area-pointer sb-alien:double)) time-interval-since-reference-date)))
;; --- DateInterval (Foundation) — Swift-native value-struct residual (ADR-0042) ---
(defclass ns:date-interval (ns:value-struct) ())
(defun ns:make-date-interval ()
  (make-instance 'ns:date-interval :ptr (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_init_Foundation_DateInterval_7f09887d" (sb-alien:function sb-alien:system-area-pointer)))))
;; --- IndexPath (Foundation) — Swift-native value-struct residual (ADR-0042) ---
(defclass ns:index-path (ns:value-struct) ())
(defmethod ns:drop-last ((self ns:index-path))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_m_Foundation_IndexPath_dropLast" (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self)) t))
(defmethod ns:append ((self ns:index-path) arg0)
  (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_m_Foundation_IndexPath_append_9fa557e6" (sb-alien:function sb-alien:void sb-alien:system-area-pointer (sb-alien:signed 64))) (aw-ptr self) arg0))
(defmethod ns:appending ((self ns:index-path) arg0)
  (aw-wrap (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_m_Foundation_IndexPath_appending_7752b293" (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:signed 64))) (aw-ptr self) arg0) t))
(defmethod ns:make-iterator ((self ns:index-path))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_m_Foundation_IndexPath_makeIterator" (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self)) t))
(defmethod ns:index-before ((self ns:index-path) before)
  (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_m_Foundation_IndexPath_index_b6d8f102" (sb-alien:function (sb-alien:signed 64) sb-alien:system-area-pointer (sb-alien:signed 64))) (aw-ptr self) before))
(defmethod ns:index-after ((self ns:index-path) after)
  (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_m_Foundation_IndexPath_index_e174a67d" (sb-alien:function (sb-alien:signed 64) sb-alien:system-area-pointer (sb-alien:signed 64))) (aw-ptr self) after))
(defun ns:make-index-path ()
  (make-instance 'ns:index-path :ptr (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_init_Foundation_IndexPath_0d72512b" (sb-alien:function sb-alien:system-area-pointer)))))
(defun ns:make-index-path-index (index)
  (make-instance 'ns:index-path :ptr (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_init_Foundation_IndexPath_dc0d0cd4" (sb-alien:function sb-alien:system-area-pointer (sb-alien:signed 64))) index)))
;; --- UUID (Foundation) — Swift-native value-struct residual (ADR-0042) ---
(defclass ns:uuid (ns:value-struct) ())
(defun ns:make-uuid ()
  (make-instance 'ns:uuid :ptr (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_init_Foundation_UUID_6aed1663" (sb-alien:function sb-alien:system-area-pointer)))))
(defun ns:make-uuid-uuid-string (uuid-string)
  (make-instance 'ns:uuid :ptr (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_init_Foundation_UUID_01854f7b" (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-swift-string-arg uuid-string))))
;; --- AffineTransform (Foundation) — Swift-native value-struct residual (ADR-0042) ---
(defclass ns:affine-transform (ns:value-struct) ())
(defmethod ns:translate-x-y ((self ns:affine-transform) x y)
  (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_m_Foundation_AffineTransform_translate" (sb-alien:function sb-alien:void sb-alien:system-area-pointer sb-alien:double sb-alien:double)) (aw-ptr self) x y))
(defmethod ns:rotate-by-degrees ((self ns:affine-transform) by-degrees)
  (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_m_Foundation_AffineTransform_rotate_1554ec45" (sb-alien:function sb-alien:void sb-alien:system-area-pointer sb-alien:double)) (aw-ptr self) by-degrees))
(defmethod ns:rotate-by-radians ((self ns:affine-transform) by-radians)
  (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_m_Foundation_AffineTransform_rotate_cd7d50fd" (sb-alien:function sb-alien:void sb-alien:system-area-pointer sb-alien:double)) (aw-ptr self) by-radians))
(defmethod ns:scale-x-y ((self ns:affine-transform) x y)
  (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_m_Foundation_AffineTransform_scale_e7dc8efc" (sb-alien:function sb-alien:void sb-alien:system-area-pointer sb-alien:double sb-alien:double)) (aw-ptr self) x y))
(defmethod ns:invert ((self ns:affine-transform))
  (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_m_Foundation_AffineTransform_invert" (sb-alien:function sb-alien:void sb-alien:system-area-pointer)) (aw-ptr self)))
(defmethod ns:inverted ((self ns:affine-transform))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_m_Foundation_AffineTransform_inverted" (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self)) t))
(defun ns:make-affine-transform-m11-m12-m21-m22-t-x-t-y (m11 m12 m21 m22 t-x t-y)
  (make-instance 'ns:affine-transform :ptr (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_init_Foundation_AffineTransform_fddb125f" (sb-alien:function sb-alien:system-area-pointer sb-alien:double sb-alien:double sb-alien:double sb-alien:double sb-alien:double sb-alien:double)) m11 m12 m21 m22 t-x t-y)))
(defun ns:make-affine-transform ()
  (make-instance 'ns:affine-transform :ptr (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_init_Foundation_AffineTransform_3ba61781" (sb-alien:function sb-alien:system-area-pointer)))))
(defun ns:make-affine-transform-translation-by-x-by-y (translation-by-x by-y)
  (make-instance 'ns:affine-transform :ptr (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_init_Foundation_AffineTransform_6ca1680a" (sb-alien:function sb-alien:system-area-pointer sb-alien:double sb-alien:double)) translation-by-x by-y)))
(defun ns:make-affine-transform-scale-by-x-by-y (scale-by-x by-y)
  (make-instance 'ns:affine-transform :ptr (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_init_Foundation_AffineTransform_58ad1471" (sb-alien:function sb-alien:system-area-pointer sb-alien:double sb-alien:double)) scale-by-x by-y)))
(defun ns:make-affine-transform-scale (scale)
  (make-instance 'ns:affine-transform :ptr (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_init_Foundation_AffineTransform_f59d0f07" (sb-alien:function sb-alien:system-area-pointer sb-alien:double)) scale)))
(defun ns:make-affine-transform-rotation-by-radians (rotation-by-radians)
  (make-instance 'ns:affine-transform :ptr (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_init_Foundation_AffineTransform_9e891a1a" (sb-alien:function sb-alien:system-area-pointer sb-alien:double)) rotation-by-radians)))
(defun ns:make-affine-transform-rotation-by-degrees (rotation-by-degrees)
  (make-instance 'ns:affine-transform :ptr (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_init_Foundation_AffineTransform_2b2346c0" (sb-alien:function sb-alien:system-area-pointer sb-alien:double)) rotation-by-degrees)))
;; --- ErrorUserInfoKey (Foundation) — Swift-native value-struct residual (ADR-0042) ---
(defclass ns:error-user-info-key (ns:value-struct) ())
(defun ns:make-error-user-info-key-raw-value (raw-value)
  (make-instance 'ns:error-user-info-key :ptr (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_init_Foundation_ErrorUserInfoKey" (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-swift-string-arg raw-value))))
;; --- URLRequest (Foundation) — Swift-native value-struct residual (ADR-0042) ---
(defclass ns:url-request (ns:value-struct) ())
(defmethod ns:value-for-http-header-field ((self ns:url-request) for-http-header-field)
  (aw-swift-string-result (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_m_Foundation_URLRequest_value" (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-swift-string-arg for-http-header-field))))
(defmethod ns:set-value-for-http-header-field ((self ns:url-request) arg0 for-http-header-field)
  (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_m_Foundation_URLRequest_setValue" (sb-alien:function sb-alien:void sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-swift-string-arg arg0) (aw-swift-string-arg for-http-header-field)))
(defmethod ns:add-value-for-http-header-field ((self ns:url-request) arg0 for-http-header-field)
  (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_m_Foundation_URLRequest_addValue" (sb-alien:function sb-alien:void sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-swift-string-arg arg0) (aw-swift-string-arg for-http-header-field)))
;; --- NSFastEnumerationIterator (Foundation) — Swift-native value-struct residual (ADR-0042) ---
(defclass ns:ns-fast-enumeration-iterator (ns:value-struct) ())
(defmethod ns:next ((self ns:ns-fast-enumeration-iterator))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_m_Foundation_NSFastEnumerationIterator_next" (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self)) t))
;; --- LocalizedStringResource (Foundation) — Swift-native value-struct residual (ADR-0042) ---
(defclass ns:localized-string-resource (ns:value-struct) ())
(defun ns:make-localized-string-resource-string-literal (string-literal)
  (make-instance 'ns:localized-string-resource :ptr (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_init_Foundation_LocalizedStringResource_c501785e" (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-swift-string-arg string-literal))))
;; --- Decimal (Foundation) — Swift-native value-struct residual (ADR-0042) ---
(defclass ns:decimal (ns:value-struct) ())
(defmethod ns:negate ((self ns:decimal))
  (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_m_Foundation_Decimal_negate" (sb-alien:function sb-alien:void sb-alien:system-area-pointer)) (aw-ptr self)))
(defmethod ns:formatted ((self ns:decimal))
  (aw-swift-string-result (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_m_Foundation_Decimal_formatted_0659424c" (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self))))
(defun ns:make-decimal (arg0)
  (make-instance 'ns:decimal :ptr (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_init_Foundation_Decimal_cdf10ebe" (sb-alien:function sb-alien:system-area-pointer (sb-alien:unsigned 8))) arg0)))
(defun ns:make-decimal-float-literal (float-literal)
  (make-instance 'ns:decimal :ptr (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_init_Foundation_Decimal_7820212a" (sb-alien:function sb-alien:system-area-pointer sb-alien:double)) float-literal)))
(defun ns:make-decimal-integer-literal (integer-literal)
  (make-instance 'ns:decimal :ptr (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_init_Foundation_Decimal_adcbba20" (sb-alien:function sb-alien:system-area-pointer (sb-alien:signed 64))) integer-literal)))
