;;; Generated TestKit bindings — generics — one defgeneric per selector (ADR-0034 §2) — do not edit
(in-package #:apianyware-sbcl-impl)

(defgeneric ns:animate-with-duration-animations (receiver arg0 arg1) (:documentation "ObjC selector generic (2 args)."))
(defgeneric ns:appearance (receiver) (:documentation "ObjC selector generic (0 args)."))
(defgeneric ns:dealloc (receiver) (:documentation "ObjC selector generic (0 args)."))
(defgeneric ns:description (receiver) (:documentation "ObjC selector generic (0 args)."))
(defgeneric ns:enabled (receiver) (:documentation "ObjC selector generic (0 args)."))
(defgeneric ns:frame (receiver) (:documentation "ObjC selector generic (0 args)."))
(defgeneric ns:hidden (receiver) (:documentation "ObjC selector generic (0 args)."))
(defgeneric ns:is-highlighted (receiver) (:documentation "ObjC selector generic (0 args)."))
(defgeneric ns:label (receiver) (:documentation "ObjC selector generic (0 args)."))
(defgeneric ns:load-resource-error (receiver arg0) (:documentation "ObjC selector generic (1 arg)."))
(defgeneric ns:maximum-count (receiver) (:documentation "ObjC selector generic (0 args)."))
(defgeneric ns:resource-named (receiver arg0) (:documentation "ObjC selector generic (1 arg)."))
(defgeneric ns:set-enabled (receiver arg0) (:documentation "ObjC selector generic (1 arg)."))
(defgeneric ns:set-frame (receiver arg0) (:documentation "ObjC selector generic (1 arg)."))
(defgeneric ns:set-hidden (receiver arg0) (:documentation "ObjC selector generic (1 arg)."))
(defgeneric ns:set-label (receiver arg0) (:documentation "ObjC selector generic (1 arg)."))
(defgeneric ns:set-needs-display (receiver) (:documentation "ObjC selector generic (0 args)."))
(defgeneric ns:set-tag (receiver arg0) (:documentation "ObjC selector generic (1 arg)."))
(defgeneric ns:set-target-action (receiver arg0 arg1) (:documentation "ObjC selector generic (2 args)."))
(defgeneric ns:set-title (receiver arg0) (:documentation "ObjC selector generic (1 arg)."))
(defgeneric ns:shared-manager (receiver) (:documentation "ObjC selector generic (0 args)."))
(defgeneric ns:tag (receiver) (:documentation "ObjC selector generic (0 args)."))
(defgeneric ns:title (receiver) (:documentation "ObjC selector generic (0 args)."))
(defgeneric ns:version-string (receiver) (:documentation "ObjC selector generic (0 args)."))
