// Generated by apianyware emit-typescript — DO NOT EDIT.
// Class: NSArray (Foundation)
//
// Runtime seam (Step 3 provides these from '@apianyware/runtime'; ADR-0055/0057):
//   NSObject — branded-handle root class; its internal ctor wraps a handle and hosts
//     [Symbol.dispose]. Emitted subclasses inherit both and declare neither.
//   __unwrap(obj) — obj's native handle (0n for null; throws on a disposed handle).
//   __wrapRetained(Cls, id) / __wrapOwned(Cls, id) — the +0 / +1 uniqued branded
//     wrapper (null when id is 0n; retain folds into the dispatch entry).
//   __class(name) — the Class handle; __sel(sel) — the interned SEL handle.
//   __registerClass(name, cls) — registers this class so a Class RETURN resolves back
//     to it; __classArg(cls) / __classCtor(id) — the Class value crossing, in / out;
//     __selName(sel) — a SEL handle back to its selector-name string.
//   __dispatch.aw_ts_msg_<codes>(recv, sel, …) — the addon's per-signature entry.
//   Result<T> / __resultRetained(Cls, r) / __resultOwned(Cls, r) / __resultScalar(r)
//     — the NSError** → Result<T> channel (ADR-0058): the addon's `…_e` entry keys
//     failure on the primary return + @catches, the runtime builds the discriminated
//     union (ok:false carries the wrapped NSError).

import {
  NSCoder,
  NSData,
  NSEnumerator,
  NSIndexSet,
  NSOrderedCollectionDifference,
  NSPredicate,
  NSString,
  NSURL,
} from '@apianyware/foundation';
import {
  NSObject,
  OBJ,
  RAW,
  RET_OBJ,
  RET_RAW,
  SEL,
  __class,
  __dispatch,
  __registerClass,
  __resultOwned,
  __resultRetained,
  __resultScalar,
  __sel,
  __unwrap,
  __wrapOwned,
  __wrapRetained,
} from '@apianyware/runtime';
import type {
  NSCoding,
  NSOrderedCollectionDifferenceCalculationOptions,
  NSSecureCoding,
} from '@apianyware/foundation';
import type {
  NSRange,
  OverridableMethod,
  Result,
} from '@apianyware/runtime';

export class NSArray extends NSObject implements NSSecureCoding, NSCoding {
  static { __registerClass('NSArray', NSArray); }

  static readonly __overridable: readonly OverridableMethod[] = [
    { name: 'objectAtIndex_', selector: 'objectAtIndex:', encoding: '@@:Q', superEntry: 'aw_ts_super_Q_P', args: [RAW], ret: RET_OBJ() },
    { name: 'init', selector: 'init', encoding: '@@:', superEntry: 'aw_ts_super_0_P_o', args: [], ret: RET_OBJ('owned') },
    { name: 'initWithCoder_', selector: 'initWithCoder:', encoding: '@@:@', superEntry: 'aw_ts_super_P_P_o', args: [OBJ], ret: RET_OBJ('owned') },
    { name: 'count', selector: 'count', encoding: 'Q@:', superEntry: 'aw_ts_super_0_Q', args: [], ret: RET_RAW },
    { name: 'arrayByAddingObject_', selector: 'arrayByAddingObject:', encoding: '@@:@', superEntry: 'aw_ts_super_P_P', args: [OBJ], ret: RET_OBJ() },
    { name: 'arrayByAddingObjectsFromArray_', selector: 'arrayByAddingObjectsFromArray:', encoding: '@@:@', superEntry: 'aw_ts_super_P_P', args: [OBJ], ret: RET_OBJ() },
    { name: 'componentsJoinedByString_', selector: 'componentsJoinedByString:', encoding: '@@:@', superEntry: 'aw_ts_super_P_P', args: [OBJ], ret: RET_OBJ() },
    { name: 'containsObject_', selector: 'containsObject:', encoding: 'c@:@', superEntry: 'aw_ts_super_P_b', args: [OBJ], ret: RET_RAW },
    { name: 'descriptionWithLocale_', selector: 'descriptionWithLocale:', encoding: '@@:@', superEntry: 'aw_ts_super_P_P', args: [OBJ], ret: RET_OBJ() },
    { name: 'descriptionWithLocale_indent_', selector: 'descriptionWithLocale:indent:', encoding: '@@:@Q', superEntry: 'aw_ts_super_PQ_P', args: [OBJ, RAW], ret: RET_OBJ() },
    { name: 'firstObjectCommonWithArray_', selector: 'firstObjectCommonWithArray:', encoding: '@@:@', superEntry: 'aw_ts_super_P_P', args: [OBJ], ret: RET_OBJ() },
    { name: 'indexOfObject_', selector: 'indexOfObject:', encoding: 'Q@:@', superEntry: 'aw_ts_super_P_Q', args: [OBJ], ret: RET_RAW },
    { name: 'indexOfObject_inRange_', selector: 'indexOfObject:inRange:', encoding: 'Q@:@{_NSRange=QQ}', superEntry: 'aw_ts_super_PG_Q', args: [OBJ, RAW], ret: RET_RAW },
    { name: 'indexOfObjectIdenticalTo_', selector: 'indexOfObjectIdenticalTo:', encoding: 'Q@:@', superEntry: 'aw_ts_super_P_Q', args: [OBJ], ret: RET_RAW },
    { name: 'indexOfObjectIdenticalTo_inRange_', selector: 'indexOfObjectIdenticalTo:inRange:', encoding: 'Q@:@{_NSRange=QQ}', superEntry: 'aw_ts_super_PG_Q', args: [OBJ, RAW], ret: RET_RAW },
    { name: 'isEqualToArray_', selector: 'isEqualToArray:', encoding: 'c@:@', superEntry: 'aw_ts_super_P_b', args: [OBJ], ret: RET_RAW },
    { name: 'objectEnumerator', selector: 'objectEnumerator', encoding: '@@:', superEntry: 'aw_ts_super_0_P', args: [], ret: RET_OBJ() },
    { name: 'reverseObjectEnumerator', selector: 'reverseObjectEnumerator', encoding: '@@:', superEntry: 'aw_ts_super_0_P', args: [], ret: RET_OBJ() },
    { name: 'sortedArrayUsingSelector_', selector: 'sortedArrayUsingSelector:', encoding: '@@:@', superEntry: 'aw_ts_super_P_P', args: [SEL], ret: RET_OBJ() },
    { name: 'subarrayWithRange_', selector: 'subarrayWithRange:', encoding: '@@:{_NSRange=QQ}', superEntry: 'aw_ts_super_G_P', args: [RAW], ret: RET_OBJ() },
    { name: 'writeToURL_error_', selector: 'writeToURL:error:', encoding: 'c@:@@', superEntry: 'aw_ts_super_PP_b', args: [OBJ, RAW], ret: RET_RAW },
    { name: 'makeObjectsPerformSelector_', selector: 'makeObjectsPerformSelector:', encoding: 'v@:@', superEntry: 'aw_ts_super_P_v', args: [SEL], ret: RET_RAW },
    { name: 'makeObjectsPerformSelector_withObject_', selector: 'makeObjectsPerformSelector:withObject:', encoding: 'v@:@@', superEntry: 'aw_ts_super_PP_v', args: [SEL, OBJ], ret: RET_RAW },
    { name: 'objectsAtIndexes_', selector: 'objectsAtIndexes:', encoding: '@@:@', superEntry: 'aw_ts_super_P_P', args: [OBJ], ret: RET_OBJ() },
    { name: 'objectAtIndexedSubscript_', selector: 'objectAtIndexedSubscript:', encoding: '@@:Q', superEntry: 'aw_ts_super_Q_P', args: [RAW], ret: RET_OBJ() },
    { name: 'description', selector: 'description', encoding: '@@:', superEntry: 'aw_ts_super_0_P', args: [], ret: RET_OBJ() },
    { name: 'firstObject', selector: 'firstObject', encoding: '@@:', superEntry: 'aw_ts_super_0_P', args: [], ret: RET_OBJ() },
    { name: 'lastObject', selector: 'lastObject', encoding: '@@:', superEntry: 'aw_ts_super_0_P', args: [], ret: RET_OBJ() },
    { name: 'sortedArrayHint', selector: 'sortedArrayHint', encoding: '@@:', superEntry: 'aw_ts_super_0_P', args: [], ret: RET_OBJ() },
    { name: 'initWithArray_', selector: 'initWithArray:', encoding: '@@:@', superEntry: 'aw_ts_super_P_P_o', args: [OBJ], ret: RET_OBJ('owned') },
    { name: 'initWithArray_copyItems_', selector: 'initWithArray:copyItems:', encoding: '@@:@c', superEntry: 'aw_ts_super_Pb_P_o', args: [OBJ, RAW], ret: RET_OBJ('owned') },
    { name: 'initWithContentsOfURL_error_', selector: 'initWithContentsOfURL:error:', encoding: '@@:@@', superEntry: 'aw_ts_super_PP_P_o', args: [OBJ, RAW], ret: RET_OBJ('owned') },
    { name: 'differenceFromArray_withOptions_', selector: 'differenceFromArray:withOptions:', encoding: '@@:@Q', superEntry: 'aw_ts_super_PQ_P', args: [OBJ, RAW], ret: RET_OBJ() },
    { name: 'differenceFromArray_', selector: 'differenceFromArray:', encoding: '@@:@', superEntry: 'aw_ts_super_P_P', args: [OBJ], ret: RET_OBJ() },
    { name: 'arrayByApplyingDifference_', selector: 'arrayByApplyingDifference:', encoding: '@@:@', superEntry: 'aw_ts_super_P_P', args: [OBJ], ret: RET_OBJ() },
    { name: 'initWithContentsOfFile_', selector: 'initWithContentsOfFile:', encoding: '@@:@', superEntry: 'aw_ts_super_P_P_o', args: [OBJ], ret: RET_OBJ('owned') },
    { name: 'initWithContentsOfURL_', selector: 'initWithContentsOfURL:', encoding: '@@:@', superEntry: 'aw_ts_super_P_P_o', args: [OBJ], ret: RET_OBJ('owned') },
    { name: 'writeToFile_atomically_', selector: 'writeToFile:atomically:', encoding: 'c@:@c', superEntry: 'aw_ts_super_Pb_b', args: [OBJ, RAW], ret: RET_RAW },
    { name: 'writeToURL_atomically_', selector: 'writeToURL:atomically:', encoding: 'c@:@c', superEntry: 'aw_ts_super_Pb_b', args: [OBJ, RAW], ret: RET_RAW },
    { name: 'pathsMatchingExtensions_', selector: 'pathsMatchingExtensions:', encoding: '@@:@', superEntry: 'aw_ts_super_P_P', args: [OBJ], ret: RET_OBJ() },
    { name: 'valueForKey_', selector: 'valueForKey:', encoding: '@@:@', superEntry: 'aw_ts_super_P_P', args: [OBJ], ret: RET_OBJ() },
    { name: 'setValue_forKey_', selector: 'setValue:forKey:', encoding: 'v@:@@', superEntry: 'aw_ts_super_PP_v', args: [OBJ, OBJ], ret: RET_RAW },
    { name: 'removeObserver_fromObjectsAtIndexes_forKeyPath_', selector: 'removeObserver:fromObjectsAtIndexes:forKeyPath:', encoding: 'v@:@@@', superEntry: 'aw_ts_super_PPP_v', args: [OBJ, OBJ, OBJ], ret: RET_RAW },
    { name: 'removeObserver_forKeyPath_', selector: 'removeObserver:forKeyPath:', encoding: 'v@:@@', superEntry: 'aw_ts_super_PP_v', args: [OBJ, OBJ], ret: RET_RAW },
    { name: 'sortedArrayUsingDescriptors_', selector: 'sortedArrayUsingDescriptors:', encoding: '@@:@', superEntry: 'aw_ts_super_P_P', args: [OBJ], ret: RET_OBJ() },
    { name: 'filteredArrayUsingPredicate_', selector: 'filteredArrayUsingPredicate:', encoding: '@@:@', superEntry: 'aw_ts_super_P_P', args: [OBJ], ret: RET_OBJ() },
    { name: 'encodeWithCoder_', selector: 'encodeWithCoder:', encoding: 'v@:@', superEntry: 'aw_ts_super_P_v', args: [OBJ], ret: RET_RAW },
  ];

  static readonly __cls: bigint = __class('NSArray');

  static array(): NSArray {
    const __ret = __dispatch.aw_ts_msg_0_P(NSArray.__cls, __sel('array'));
    return __wrapRetained(NSArray, __ret)!;
  }

  static arrayWithObject_(anObject: NSObject): NSArray {
    const __ret = __dispatch.aw_ts_msg_P_P(NSArray.__cls, __sel('arrayWithObject:'), __unwrap(anObject));
    return __wrapRetained(NSArray, __ret)!;
  }

  static arrayWithArray_(array: NSArray): NSArray {
    const __ret = __dispatch.aw_ts_msg_P_P(NSArray.__cls, __sel('arrayWithArray:'), __unwrap(array));
    return __wrapRetained(NSArray, __ret)!;
  }

  static arrayWithContentsOfURL_error_(url: NSURL): Result<NSArray> {
    return __resultRetained(NSArray, __dispatch.aw_ts_msg_P_P_e(NSArray.__cls, __sel('arrayWithContentsOfURL:error:'), __unwrap(url)));
  }

  static arrayWithContentsOfFile_(path: NSString): NSArray {
    const __ret = __dispatch.aw_ts_msg_P_P(NSArray.__cls, __sel('arrayWithContentsOfFile:'), __unwrap(path));
    return __wrapRetained(NSArray, __ret)!;
  }

  static arrayWithContentsOfURL_(url: NSURL): NSArray {
    const __ret = __dispatch.aw_ts_msg_P_P(NSArray.__cls, __sel('arrayWithContentsOfURL:'), __unwrap(url));
    return __wrapRetained(NSArray, __ret)!;
  }

  static supportsSecureCoding(): boolean {
    return __dispatch.aw_ts_msg_0_b(NSArray.__cls, __sel('supportsSecureCoding'));
  }

  objectAtIndex_(index: number): NSObject {
    const __ret = __dispatch.aw_ts_msg_Q_P(__unwrap(this), __sel('objectAtIndex:'), index);
    return __wrapRetained(__ret)!;
  }

  init(): this {
    const __ret = __dispatch.aw_ts_msg_0_P_o(__unwrap(this), __sel('init'));
    return __wrapOwned<this>(__ret)!;
  }

  initWithCoder_(coder: NSCoder): this {
    const __ret = __dispatch.aw_ts_msg_P_P_o(__unwrap(this), __sel('initWithCoder:'), __unwrap(coder));
    return __wrapOwned<this>(__ret)!;
  }

  count(): number {
    return __dispatch.aw_ts_msg_0_Q(__unwrap(this), __sel('count'));
  }

  arrayByAddingObject_(anObject: NSObject): NSArray {
    const __ret = __dispatch.aw_ts_msg_P_P(__unwrap(this), __sel('arrayByAddingObject:'), __unwrap(anObject));
    return __wrapRetained(NSArray, __ret)!;
  }

  arrayByAddingObjectsFromArray_(otherArray: NSArray): NSArray {
    const __ret = __dispatch.aw_ts_msg_P_P(__unwrap(this), __sel('arrayByAddingObjectsFromArray:'), __unwrap(otherArray));
    return __wrapRetained(NSArray, __ret)!;
  }

  componentsJoinedByString_(separator: NSString): NSString {
    const __ret = __dispatch.aw_ts_msg_P_P(__unwrap(this), __sel('componentsJoinedByString:'), __unwrap(separator));
    return __wrapRetained(NSString, __ret)!;
  }

  containsObject_(anObject: NSObject): boolean {
    return __dispatch.aw_ts_msg_P_b(__unwrap(this), __sel('containsObject:'), __unwrap(anObject));
  }

  descriptionWithLocale_(locale: NSObject): NSString {
    const __ret = __dispatch.aw_ts_msg_P_P(__unwrap(this), __sel('descriptionWithLocale:'), __unwrap(locale));
    return __wrapRetained(NSString, __ret)!;
  }

  descriptionWithLocale_indent_(locale: NSObject, level: number): NSString {
    const __ret = __dispatch.aw_ts_msg_PQ_P(__unwrap(this), __sel('descriptionWithLocale:indent:'), __unwrap(locale), level);
    return __wrapRetained(NSString, __ret)!;
  }

  firstObjectCommonWithArray_(otherArray: NSArray): NSObject {
    const __ret = __dispatch.aw_ts_msg_P_P(__unwrap(this), __sel('firstObjectCommonWithArray:'), __unwrap(otherArray));
    return __wrapRetained(__ret)!;
  }

  indexOfObject_(anObject: NSObject): number {
    return __dispatch.aw_ts_msg_P_Q(__unwrap(this), __sel('indexOfObject:'), __unwrap(anObject));
  }

  indexOfObject_inRange_(anObject: NSObject, range: NSRange): number {
    return __dispatch.aw_ts_msg_PG_Q(__unwrap(this), __sel('indexOfObject:inRange:'), __unwrap(anObject), range);
  }

  indexOfObjectIdenticalTo_(anObject: NSObject): number {
    return __dispatch.aw_ts_msg_P_Q(__unwrap(this), __sel('indexOfObjectIdenticalTo:'), __unwrap(anObject));
  }

  indexOfObjectIdenticalTo_inRange_(anObject: NSObject, range: NSRange): number {
    return __dispatch.aw_ts_msg_PG_Q(__unwrap(this), __sel('indexOfObjectIdenticalTo:inRange:'), __unwrap(anObject), range);
  }

  isEqualToArray_(otherArray: NSArray): boolean {
    return __dispatch.aw_ts_msg_P_b(__unwrap(this), __sel('isEqualToArray:'), __unwrap(otherArray));
  }

  objectEnumerator(): NSEnumerator {
    const __ret = __dispatch.aw_ts_msg_0_P(__unwrap(this), __sel('objectEnumerator'));
    return __wrapRetained(NSEnumerator, __ret)!;
  }

  reverseObjectEnumerator(): NSEnumerator {
    const __ret = __dispatch.aw_ts_msg_0_P(__unwrap(this), __sel('reverseObjectEnumerator'));
    return __wrapRetained(NSEnumerator, __ret)!;
  }

  sortedArrayUsingSelector_(comparator: string): NSArray {
    const __ret = __dispatch.aw_ts_msg_P_P(__unwrap(this), __sel('sortedArrayUsingSelector:'), __sel(comparator));
    return __wrapRetained(NSArray, __ret)!;
  }

  subarrayWithRange_(range: NSRange): NSArray {
    const __ret = __dispatch.aw_ts_msg_G_P(__unwrap(this), __sel('subarrayWithRange:'), range);
    return __wrapRetained(NSArray, __ret)!;
  }

  writeToURL_error_(url: NSURL): Result<boolean> {
    return __resultScalar(__dispatch.aw_ts_msg_P_b_e(__unwrap(this), __sel('writeToURL:error:'), __unwrap(url)));
  }

  makeObjectsPerformSelector_(aSelector: string): void {
    __dispatch.aw_ts_msg_P_v(__unwrap(this), __sel('makeObjectsPerformSelector:'), __sel(aSelector));
  }

  makeObjectsPerformSelector_withObject_(aSelector: string, argument: NSObject): void {
    __dispatch.aw_ts_msg_PP_v(__unwrap(this), __sel('makeObjectsPerformSelector:withObject:'), __sel(aSelector), __unwrap(argument));
  }

  objectsAtIndexes_(indexes: NSIndexSet): NSArray {
    const __ret = __dispatch.aw_ts_msg_P_P(__unwrap(this), __sel('objectsAtIndexes:'), __unwrap(indexes));
    return __wrapRetained(NSArray, __ret)!;
  }

  objectAtIndexedSubscript_(idx: number): NSObject {
    const __ret = __dispatch.aw_ts_msg_Q_P(__unwrap(this), __sel('objectAtIndexedSubscript:'), idx);
    return __wrapRetained(__ret)!;
  }

  description(): NSString {
    const __ret = __dispatch.aw_ts_msg_0_P(__unwrap(this), __sel('description'));
    return __wrapRetained(NSString, __ret)!;
  }

  firstObject(): NSObject {
    const __ret = __dispatch.aw_ts_msg_0_P(__unwrap(this), __sel('firstObject'));
    return __wrapRetained(__ret)!;
  }

  lastObject(): NSObject {
    const __ret = __dispatch.aw_ts_msg_0_P(__unwrap(this), __sel('lastObject'));
    return __wrapRetained(__ret)!;
  }

  sortedArrayHint(): NSData {
    const __ret = __dispatch.aw_ts_msg_0_P(__unwrap(this), __sel('sortedArrayHint'));
    return __wrapRetained(NSData, __ret)!;
  }

  initWithArray_(array: NSArray): this {
    const __ret = __dispatch.aw_ts_msg_P_P_o(__unwrap(this), __sel('initWithArray:'), __unwrap(array));
    return __wrapOwned<this>(__ret)!;
  }

  initWithArray_copyItems_(array: NSArray, flag: boolean): this {
    const __ret = __dispatch.aw_ts_msg_Pb_P_o(__unwrap(this), __sel('initWithArray:copyItems:'), __unwrap(array), flag);
    return __wrapOwned<this>(__ret)!;
  }

  initWithContentsOfURL_error_(url: NSURL): Result<NSArray> {
    return __resultOwned(NSArray, __dispatch.aw_ts_msg_P_P_o_e(__unwrap(this), __sel('initWithContentsOfURL:error:'), __unwrap(url)));
  }

  differenceFromArray_withOptions_(other: NSArray, options: NSOrderedCollectionDifferenceCalculationOptions): NSOrderedCollectionDifference {
    const __ret = __dispatch.aw_ts_msg_PQ_P(__unwrap(this), __sel('differenceFromArray:withOptions:'), __unwrap(other), options);
    return __wrapRetained(NSOrderedCollectionDifference, __ret)!;
  }

  differenceFromArray_(other: NSArray): NSOrderedCollectionDifference {
    const __ret = __dispatch.aw_ts_msg_P_P(__unwrap(this), __sel('differenceFromArray:'), __unwrap(other));
    return __wrapRetained(NSOrderedCollectionDifference, __ret)!;
  }

  arrayByApplyingDifference_(difference: NSOrderedCollectionDifference): NSArray {
    const __ret = __dispatch.aw_ts_msg_P_P(__unwrap(this), __sel('arrayByApplyingDifference:'), __unwrap(difference));
    return __wrapRetained(NSArray, __ret)!;
  }

  initWithContentsOfFile_(path: NSString): NSArray {
    const __ret = __dispatch.aw_ts_msg_P_P_o(__unwrap(this), __sel('initWithContentsOfFile:'), __unwrap(path));
    return __wrapOwned(NSArray, __ret)!;
  }

  initWithContentsOfURL_(url: NSURL): NSArray {
    const __ret = __dispatch.aw_ts_msg_P_P_o(__unwrap(this), __sel('initWithContentsOfURL:'), __unwrap(url));
    return __wrapOwned(NSArray, __ret)!;
  }

  writeToFile_atomically_(path: NSString, useAuxiliaryFile: boolean): boolean {
    return __dispatch.aw_ts_msg_Pb_b(__unwrap(this), __sel('writeToFile:atomically:'), __unwrap(path), useAuxiliaryFile);
  }

  writeToURL_atomically_(url: NSURL, atomically: boolean): boolean {
    return __dispatch.aw_ts_msg_Pb_b(__unwrap(this), __sel('writeToURL:atomically:'), __unwrap(url), atomically);
  }

  pathsMatchingExtensions_(filterTypes: NSArray): NSArray {
    const __ret = __dispatch.aw_ts_msg_P_P(__unwrap(this), __sel('pathsMatchingExtensions:'), __unwrap(filterTypes));
    return __wrapRetained(NSArray, __ret)!;
  }

  valueForKey_(key: NSString): NSObject {
    const __ret = __dispatch.aw_ts_msg_P_P(__unwrap(this), __sel('valueForKey:'), __unwrap(key));
    return __wrapRetained(__ret)!;
  }

  setValue_forKey_(value: NSObject, key: NSString): void {
    __dispatch.aw_ts_msg_PP_v(__unwrap(this), __sel('setValue:forKey:'), __unwrap(value), __unwrap(key));
  }

  removeObserver_fromObjectsAtIndexes_forKeyPath_(observer: NSObject, indexes: NSIndexSet, keyPath: NSString): void {
    __dispatch.aw_ts_msg_PPP_v(__unwrap(this), __sel('removeObserver:fromObjectsAtIndexes:forKeyPath:'), __unwrap(observer), __unwrap(indexes), __unwrap(keyPath));
  }

  removeObserver_forKeyPath_(observer: NSObject, keyPath: NSString): void {
    __dispatch.aw_ts_msg_PP_v(__unwrap(this), __sel('removeObserver:forKeyPath:'), __unwrap(observer), __unwrap(keyPath));
  }

  sortedArrayUsingDescriptors_(sortDescriptors: NSArray): NSArray {
    const __ret = __dispatch.aw_ts_msg_P_P(__unwrap(this), __sel('sortedArrayUsingDescriptors:'), __unwrap(sortDescriptors));
    return __wrapRetained(NSArray, __ret)!;
  }

  filteredArrayUsingPredicate_(predicate: NSPredicate): NSArray {
    const __ret = __dispatch.aw_ts_msg_P_P(__unwrap(this), __sel('filteredArrayUsingPredicate:'), __unwrap(predicate));
    return __wrapRetained(NSArray, __ret)!;
  }

  encodeWithCoder_(coder: NSCoder): void {
    __dispatch.aw_ts_msg_P_v(__unwrap(this), __sel('encodeWithCoder:'), __unwrap(coder));
  }
}
