// Generated by apianyware emit-typescript — DO NOT EDIT.
// Type surface: NSArray (Foundation)
//
// Declaration-only .d.ts, co-generated with the .ts class body from one IR pass
// (ADR-0055 §2) so runtime and types cannot drift: the public type surface tsc and
// consumers see — no bodies, no __cls/dispatch internals, no runtime-seam helpers.

import {
  NSCoder,
  NSData,
  NSEnumerator,
  NSIndexSet,
  NSOrderedCollectionDifference,
  NSPredicate,
  NSString,
  NSURL,
} from '@apianyware/foundation';
import {
  NSObject,
} from '@apianyware/runtime';
import type {
  NSCoding,
  NSOrderedCollectionDifferenceCalculationOptions,
  NSSecureCoding,
} from '@apianyware/foundation';
import type {
  NSRange,
  Result,
} from '@apianyware/runtime';

export class NSArray extends NSObject implements NSSecureCoding, NSCoding {
  static array(): NSArray;
  static arrayWithObject_(anObject: NSObject): NSArray;
  static arrayWithArray_(array: NSArray): NSArray;
  static arrayWithContentsOfURL_error_(url: NSURL): Result<NSArray>;
  static arrayWithContentsOfFile_(path: NSString): NSArray;
  static arrayWithContentsOfURL_(url: NSURL): NSArray;
  static supportsSecureCoding(): boolean;
  objectAtIndex_(index: number): NSObject;
  init(): this;
  initWithCoder_(coder: NSCoder): this;
  count(): number;
  arrayByAddingObject_(anObject: NSObject): NSArray;
  arrayByAddingObjectsFromArray_(otherArray: NSArray): NSArray;
  componentsJoinedByString_(separator: NSString): NSString;
  containsObject_(anObject: NSObject): boolean;
  descriptionWithLocale_(locale: NSObject): NSString;
  descriptionWithLocale_indent_(locale: NSObject, level: number): NSString;
  firstObjectCommonWithArray_(otherArray: NSArray): NSObject;
  indexOfObject_(anObject: NSObject): number;
  indexOfObject_inRange_(anObject: NSObject, range: NSRange): number;
  indexOfObjectIdenticalTo_(anObject: NSObject): number;
  indexOfObjectIdenticalTo_inRange_(anObject: NSObject, range: NSRange): number;
  isEqualToArray_(otherArray: NSArray): boolean;
  objectEnumerator(): NSEnumerator;
  reverseObjectEnumerator(): NSEnumerator;
  sortedArrayUsingSelector_(comparator: string): NSArray;
  subarrayWithRange_(range: NSRange): NSArray;
  writeToURL_error_(url: NSURL): Result<boolean>;
  makeObjectsPerformSelector_(aSelector: string): void;
  makeObjectsPerformSelector_withObject_(aSelector: string, argument: NSObject): void;
  objectsAtIndexes_(indexes: NSIndexSet): NSArray;
  objectAtIndexedSubscript_(idx: number): NSObject;
  description(): NSString;
  firstObject(): NSObject;
  lastObject(): NSObject;
  sortedArrayHint(): NSData;
  initWithArray_(array: NSArray): this;
  initWithArray_copyItems_(array: NSArray, flag: boolean): this;
  initWithContentsOfURL_error_(url: NSURL): Result<NSArray>;
  differenceFromArray_withOptions_(other: NSArray, options: NSOrderedCollectionDifferenceCalculationOptions): NSOrderedCollectionDifference;
  differenceFromArray_(other: NSArray): NSOrderedCollectionDifference;
  arrayByApplyingDifference_(difference: NSOrderedCollectionDifference): NSArray;
  initWithContentsOfFile_(path: NSString): NSArray;
  initWithContentsOfURL_(url: NSURL): NSArray;
  writeToFile_atomically_(path: NSString, useAuxiliaryFile: boolean): boolean;
  writeToURL_atomically_(url: NSURL, atomically: boolean): boolean;
  pathsMatchingExtensions_(filterTypes: NSArray): NSArray;
  valueForKey_(key: NSString): NSObject;
  setValue_forKey_(value: NSObject, key: NSString): void;
  removeObserver_fromObjectsAtIndexes_forKeyPath_(observer: NSObject, indexes: NSIndexSet, keyPath: NSString): void;
  removeObserver_forKeyPath_(observer: NSObject, keyPath: NSString): void;
  sortedArrayUsingDescriptors_(sortDescriptors: NSArray): NSArray;
  filteredArrayUsingPredicate_(predicate: NSPredicate): NSArray;
  encodeWithCoder_(coder: NSCoder): void;
}
