// Generated by apianyware emit-typescript — DO NOT EDIT.
// Type surface: NSMutableString (Foundation)
//
// Declaration-only .d.ts, co-generated with the .ts class body from one IR pass
// (ADR-0055 §2) so runtime and types cannot drift: the public type surface tsc and
// consumers see — no bodies, no __cls/dispatch internals, no runtime-seam helpers.

import {
  NSArray,
  NSCoder,
  NSString,
} from '@apianyware/foundation';
import type {
  NSCoding,
  NSItemProviderWriting,
  NSSecureCoding,
  NSStringCompareOptions,
} from '@apianyware/foundation';
import type {
  NSRange,
} from '@apianyware/runtime';

export class NSMutableString extends NSString implements NSCoding, NSItemProviderWriting, NSSecureCoding {
  static stringWithCapacity_(capacity: number): NSMutableString;
  static supportsSecureCoding(): boolean;
  static writableTypeIdentifiersForItemProvider(): NSArray;
  replaceCharactersInRange_withString_(range: NSRange, aString: NSString): void;
  insertString_atIndex_(aString: NSString, loc: number): void;
  deleteCharactersInRange_(range: NSRange): void;
  appendString_(aString: NSString): void;
  setString_(aString: NSString): void;
  replaceOccurrencesOfString_withString_options_range_(target: NSString, replacement: NSString, options: NSStringCompareOptions, searchRange: NSRange): number;
  initWithCapacity_(capacity: number): NSMutableString;
  encodeWithCoder_(coder: NSCoder): void;
  initWithCoder_(coder: NSCoder): this;
}
