// Generated by apianyware emit-typescript — DO NOT EDIT.
// Class: NSMutableString (Foundation)
//
// Runtime seam (Step 3 provides these from '@apianyware/runtime'; ADR-0055/0057):
//   NSObject — branded-handle root class; its internal ctor wraps a handle and hosts
//     [Symbol.dispose]. Emitted subclasses inherit both and declare neither.
//   __unwrap(obj) — obj's native handle (0n for null; throws on a disposed handle).
//   __wrapRetained(Cls, id) / __wrapOwned(Cls, id) — the +0 / +1 uniqued branded
//     wrapper (null when id is 0n; retain folds into the dispatch entry).
//   __class(name) — the Class handle; __sel(sel) — the interned SEL handle.
//   __registerClass(name, cls) — registers this class so a Class RETURN resolves back
//     to it; __classArg(cls) / __classCtor(id) — the Class value crossing, in / out;
//     __selName(sel) — a SEL handle back to its selector-name string.
//   __dispatch.aw_ts_msg_<codes>(recv, sel, …) — the addon's per-signature entry.

import {
  NSArray,
  NSCoder,
  NSString,
} from '@apianyware/foundation';
import {
  OBJ,
  RAW,
  RET_OBJ,
  RET_RAW,
  __class,
  __dispatch,
  __registerClass,
  __sel,
  __unwrap,
  __wrapOwned,
  __wrapRetained,
} from '@apianyware/runtime';
import type {
  NSCoding,
  NSItemProviderWriting,
  NSSecureCoding,
  NSStringCompareOptions,
} from '@apianyware/foundation';
import type {
  NSRange,
  OverridableMethod,
} from '@apianyware/runtime';

export class NSMutableString extends NSString implements NSCoding, NSItemProviderWriting, NSSecureCoding {
  static { __registerClass('NSMutableString', NSMutableString); }

  static readonly __overridable: readonly OverridableMethod[] = [
    { name: 'replaceCharactersInRange_withString_', selector: 'replaceCharactersInRange:withString:', encoding: 'v@:{_NSRange=QQ}@', superEntry: 'aw_ts_super_GP_v', args: [RAW, OBJ], ret: RET_RAW },
    { name: 'insertString_atIndex_', selector: 'insertString:atIndex:', encoding: 'v@:@Q', superEntry: 'aw_ts_super_PQ_v', args: [OBJ, RAW], ret: RET_RAW },
    { name: 'deleteCharactersInRange_', selector: 'deleteCharactersInRange:', encoding: 'v@:{_NSRange=QQ}', superEntry: 'aw_ts_super_G_v', args: [RAW], ret: RET_RAW },
    { name: 'appendString_', selector: 'appendString:', encoding: 'v@:@', superEntry: 'aw_ts_super_P_v', args: [OBJ], ret: RET_RAW },
    { name: 'setString_', selector: 'setString:', encoding: 'v@:@', superEntry: 'aw_ts_super_P_v', args: [OBJ], ret: RET_RAW },
    { name: 'replaceOccurrencesOfString_withString_options_range_', selector: 'replaceOccurrencesOfString:withString:options:range:', encoding: 'Q@:@@Q{_NSRange=QQ}', superEntry: 'aw_ts_super_PPQG_Q', args: [OBJ, OBJ, RAW, RAW], ret: RET_RAW },
    { name: 'initWithCapacity_', selector: 'initWithCapacity:', encoding: '@@:Q', superEntry: 'aw_ts_super_Q_P_o', args: [RAW], ret: RET_OBJ('owned') },
    { name: 'encodeWithCoder_', selector: 'encodeWithCoder:', encoding: 'v@:@', superEntry: 'aw_ts_super_P_v', args: [OBJ], ret: RET_RAW },
    { name: 'initWithCoder_', selector: 'initWithCoder:', encoding: '@@:@', superEntry: 'aw_ts_super_P_P_o', args: [OBJ], ret: RET_OBJ('owned') },
  ];

  static readonly __cls: bigint = __class('NSMutableString');

  static stringWithCapacity_(capacity: number): NSMutableString {
    const __ret = __dispatch.aw_ts_msg_Q_P(NSMutableString.__cls, __sel('stringWithCapacity:'), capacity);
    return __wrapRetained(NSMutableString, __ret)!;
  }

  static supportsSecureCoding(): boolean {
    return __dispatch.aw_ts_msg_0_b(NSMutableString.__cls, __sel('supportsSecureCoding'));
  }

  static writableTypeIdentifiersForItemProvider(): NSArray {
    const __ret = __dispatch.aw_ts_msg_0_P(NSMutableString.__cls, __sel('writableTypeIdentifiersForItemProvider'));
    return __wrapRetained(NSArray, __ret)!;
  }

  replaceCharactersInRange_withString_(range: NSRange, aString: NSString): void {
    __dispatch.aw_ts_msg_GP_v(__unwrap(this), __sel('replaceCharactersInRange:withString:'), range, __unwrap(aString));
  }

  insertString_atIndex_(aString: NSString, loc: number): void {
    __dispatch.aw_ts_msg_PQ_v(__unwrap(this), __sel('insertString:atIndex:'), __unwrap(aString), loc);
  }

  deleteCharactersInRange_(range: NSRange): void {
    __dispatch.aw_ts_msg_G_v(__unwrap(this), __sel('deleteCharactersInRange:'), range);
  }

  appendString_(aString: NSString): void {
    __dispatch.aw_ts_msg_P_v(__unwrap(this), __sel('appendString:'), __unwrap(aString));
  }

  setString_(aString: NSString): void {
    __dispatch.aw_ts_msg_P_v(__unwrap(this), __sel('setString:'), __unwrap(aString));
  }

  replaceOccurrencesOfString_withString_options_range_(target: NSString, replacement: NSString, options: NSStringCompareOptions, searchRange: NSRange): number {
    return __dispatch.aw_ts_msg_PPQG_Q(__unwrap(this), __sel('replaceOccurrencesOfString:withString:options:range:'), __unwrap(target), __unwrap(replacement), options, searchRange);
  }

  initWithCapacity_(capacity: number): NSMutableString {
    const __ret = __dispatch.aw_ts_msg_Q_P_o(__unwrap(this), __sel('initWithCapacity:'), capacity);
    return __wrapOwned(NSMutableString, __ret)!;
  }

  encodeWithCoder_(coder: NSCoder): void {
    __dispatch.aw_ts_msg_P_v(__unwrap(this), __sel('encodeWithCoder:'), __unwrap(coder));
  }

  initWithCoder_(coder: NSCoder): this {
    const __ret = __dispatch.aw_ts_msg_P_P_o(__unwrap(this), __sel('initWithCoder:'), __unwrap(coder));
    return __wrapOwned<this>(__ret)!;
  }
}
