// Generated by apianyware emit-typescript — DO NOT EDIT.
// Type surface: NSString (Foundation)
//
// Declaration-only .d.ts, co-generated with the .ts class body from one IR pass
// (ADR-0055 §2) so runtime and types cannot drift: the public type surface tsc and
// consumers see — no bodies, no __cls/dispatch internals, no runtime-seam helpers.

import {
  NSArray,
  NSCharacterSet,
  NSCoder,
  NSData,
  NSDictionary,
  NSLocale,
  NSURL,
} from '@apianyware/foundation';
import {
  NSObject,
} from '@apianyware/runtime';
import type {
  NSCoding,
  NSComparisonResult,
  NSItemProviderWriting,
  NSSecureCoding,
  NSStringCompareOptions,
} from '@apianyware/foundation';
import type {
  NSRange,
  Result,
} from '@apianyware/runtime';

export class NSString extends NSObject implements NSSecureCoding, NSCoding, NSItemProviderWriting {
  static localizedNameOfStringEncoding_(encoding: number): NSString;
  static string(): NSString;
  static stringWithString_(string: NSString): NSString;
  static stringWithUTF8String_(nullTerminatedCString: string): NSString;
  static stringWithCString_encoding_(cString: string, enc: number): NSString;
  static stringWithContentsOfURL_encoding_error_(url: NSURL, enc: number): Result<NSString>;
  static stringWithContentsOfFile_encoding_error_(path: NSString, enc: number): Result<NSString>;
  static defaultCStringEncoding(): number;
  static pathWithComponents_(components: NSArray): NSString;
  static supportsSecureCoding(): boolean;
  static writableTypeIdentifiersForItemProvider(): NSArray;
  characterAtIndex_(index: number): number;
  init(): this;
  initWithCoder_(coder: NSCoder): this;
  length(): number;
  substringFromIndex_(from: number): NSString;
  substringToIndex_(to: number): NSString;
  substringWithRange_(range: NSRange): NSString;
  compare_(string: NSString): NSComparisonResult;
  compare_options_(string: NSString, mask: NSStringCompareOptions): NSComparisonResult;
  compare_options_range_(string: NSString, mask: NSStringCompareOptions, rangeOfReceiverToCompare: NSRange): NSComparisonResult;
  compare_options_range_locale_(string: NSString, mask: NSStringCompareOptions, rangeOfReceiverToCompare: NSRange, locale: NSObject): NSComparisonResult;
  caseInsensitiveCompare_(string: NSString): NSComparisonResult;
  localizedCompare_(string: NSString): NSComparisonResult;
  localizedCaseInsensitiveCompare_(string: NSString): NSComparisonResult;
  localizedStandardCompare_(string: NSString): NSComparisonResult;
  isEqualToString_(aString: NSString): boolean;
  hasPrefix_(str: NSString): boolean;
  hasSuffix_(str: NSString): boolean;
  commonPrefixWithString_options_(str: NSString, mask: NSStringCompareOptions): NSString;
  containsString_(str: NSString): boolean;
  localizedCaseInsensitiveContainsString_(str: NSString): boolean;
  localizedStandardContainsString_(str: NSString): boolean;
  localizedStandardRangeOfString_(str: NSString): NSRange;
  rangeOfString_(searchString: NSString): NSRange;
  rangeOfString_options_(searchString: NSString, mask: NSStringCompareOptions): NSRange;
  rangeOfString_options_range_(searchString: NSString, mask: NSStringCompareOptions, rangeOfReceiverToSearch: NSRange): NSRange;
  rangeOfString_options_range_locale_(searchString: NSString, mask: NSStringCompareOptions, rangeOfReceiverToSearch: NSRange, locale: NSLocale): NSRange;
  rangeOfCharacterFromSet_(searchSet: NSCharacterSet): NSRange;
  rangeOfCharacterFromSet_options_(searchSet: NSCharacterSet, mask: NSStringCompareOptions): NSRange;
  rangeOfCharacterFromSet_options_range_(searchSet: NSCharacterSet, mask: NSStringCompareOptions, rangeOfReceiverToSearch: NSRange): NSRange;
  rangeOfComposedCharacterSequenceAtIndex_(index: number): NSRange;
  rangeOfComposedCharacterSequencesForRange_(range: NSRange): NSRange;
  stringByAppendingString_(aString: NSString): NSString;
  uppercaseStringWithLocale_(locale: NSLocale): NSString;
  lowercaseStringWithLocale_(locale: NSLocale): NSString;
  capitalizedStringWithLocale_(locale: NSLocale): NSString;
  lineRangeForRange_(range: NSRange): NSRange;
  paragraphRangeForRange_(range: NSRange): NSRange;
  dataUsingEncoding_allowLossyConversion_(encoding: number, lossy: boolean): NSData;
  dataUsingEncoding_(encoding: number): NSData;
  canBeConvertedToEncoding_(encoding: number): boolean;
  cStringUsingEncoding_(encoding: number): string;
  maximumLengthOfBytesUsingEncoding_(enc: number): number;
  lengthOfBytesUsingEncoding_(enc: number): number;
  componentsSeparatedByString_(separator: NSString): NSArray;
  componentsSeparatedByCharactersInSet_(separator: NSCharacterSet): NSArray;
  stringByTrimmingCharactersInSet_(set: NSCharacterSet): NSString;
  stringByPaddingToLength_withString_startingAtIndex_(newLength: number, padString: NSString, padIndex: number): NSString;
  stringByFoldingWithOptions_locale_(options: NSStringCompareOptions, locale: NSLocale): NSString;
  stringByReplacingOccurrencesOfString_withString_options_range_(target: NSString, replacement: NSString, options: NSStringCompareOptions, searchRange: NSRange): NSString;
  stringByReplacingOccurrencesOfString_withString_(target: NSString, replacement: NSString): NSString;
  stringByReplacingCharactersInRange_withString_(range: NSRange, replacement: NSString): NSString;
  stringByApplyingTransform_reverse_(transform: NSString, reverse: boolean): NSString;
  writeToURL_atomically_encoding_error_(url: NSURL, useAuxiliaryFile: boolean, enc: number): Result<boolean>;
  writeToFile_atomically_encoding_error_(path: NSString, useAuxiliaryFile: boolean, enc: number): Result<boolean>;
  initWithUTF8String_(nullTerminatedCString: string): this;
  initWithString_(aString: NSString): this;
  initWithData_encoding_(data: NSData, encoding: number): this;
  initWithCString_encoding_(nullTerminatedCString: string, encoding: number): this;
  initWithContentsOfURL_encoding_error_(url: NSURL, enc: number): Result<this>;
  initWithContentsOfFile_encoding_error_(path: NSString, enc: number): Result<this>;
  doubleValue(): number;
  floatValue(): number;
  intValue(): number;
  integerValue(): number;
  longLongValue(): number;
  boolValue(): boolean;
  uppercaseString(): NSString;
  lowercaseString(): NSString;
  capitalizedString(): NSString;
  localizedUppercaseString(): NSString;
  localizedLowercaseString(): NSString;
  localizedCapitalizedString(): NSString;
  UTF8String(): string;
  fastestEncoding(): number;
  smallestEncoding(): number;
  decomposedStringWithCanonicalMapping(): NSString;
  precomposedStringWithCanonicalMapping(): NSString;
  decomposedStringWithCompatibilityMapping(): NSString;
  precomposedStringWithCompatibilityMapping(): NSString;
  description(): NSString;
  hash(): number;
  propertyList(): NSObject;
  propertyListFromStringsFileFormat(): NSDictionary;
  variantFittingPresentationWidth_(width: number): NSString;
  stringByAppendingPathComponent_(str: NSString): NSString;
  stringByAppendingPathExtension_(str: NSString): NSString;
  stringsByAppendingPaths_(paths: NSArray): NSArray;
  pathComponents(): NSArray;
  isAbsolutePath(): boolean;
  lastPathComponent(): NSString;
  stringByDeletingLastPathComponent(): NSString;
  pathExtension(): NSString;
  stringByDeletingPathExtension(): NSString;
  stringByAbbreviatingWithTildeInPath(): NSString;
  stringByExpandingTildeInPath(): NSString;
  stringByStandardizingPath(): NSString;
  stringByResolvingSymlinksInPath(): NSString;
  fileSystemRepresentation(): string;
  stringByAddingPercentEncodingWithAllowedCharacters_(allowedCharacters: NSCharacterSet): NSString;
  stringByRemovingPercentEncoding(): NSString;
  encodeWithCoder_(coder: NSCoder): void;
}
