// Generated by apianyware emit-typescript — DO NOT EDIT.
// Class: NSString (Foundation)
//
// Runtime seam (Step 3 provides these from '@apianyware/runtime'; ADR-0055/0057):
//   NSObject — branded-handle root class; its internal ctor wraps a handle and hosts
//     [Symbol.dispose]. Emitted subclasses inherit both and declare neither.
//   __unwrap(obj) — obj's native handle (0n for null; throws on a disposed handle).
//   __wrapRetained(Cls, id) / __wrapOwned(Cls, id) — the +0 / +1 uniqued branded
//     wrapper (null when id is 0n; retain folds into the dispatch entry).
//   __class(name) — the Class handle; __sel(sel) — the interned SEL handle.
//   __registerClass(name, cls) — registers this class so a Class RETURN resolves back
//     to it; __classArg(cls) / __classCtor(id) — the Class value crossing, in / out;
//     __selName(sel) — a SEL handle back to its selector-name string.
//   __dispatch.aw_ts_msg_<codes>(recv, sel, …) — the addon's per-signature entry.
//   Result<T> / __resultRetained(Cls, r) / __resultOwned(Cls, r) / __resultScalar(r)
//     — the NSError** → Result<T> channel (ADR-0058): the addon's `…_e` entry keys
//     failure on the primary return + @catches, the runtime builds the discriminated
//     union (ok:false carries the wrapped NSError).

import {
  NSArray,
  NSCharacterSet,
  NSCoder,
  NSData,
  NSDictionary,
  NSLocale,
  NSURL,
} from '@apianyware/foundation';
import {
  NSObject,
  OBJ,
  RAW,
  RET_OBJ,
  RET_RAW,
  __class,
  __dispatch,
  __registerClass,
  __resultOwned,
  __resultRetained,
  __resultScalar,
  __sel,
  __unwrap,
  __wrapOwned,
  __wrapRetained,
} from '@apianyware/runtime';
import type {
  NSCoding,
  NSComparisonResult,
  NSItemProviderWriting,
  NSSecureCoding,
  NSStringCompareOptions,
} from '@apianyware/foundation';
import type {
  NSRange,
  OverridableMethod,
  Result,
} from '@apianyware/runtime';

export class NSString extends NSObject implements NSSecureCoding, NSCoding, NSItemProviderWriting {
  static { __registerClass('NSString', NSString); }

  static readonly __overridable: readonly OverridableMethod[] = [
    { name: 'characterAtIndex_', selector: 'characterAtIndex:', encoding: 'S@:Q', superEntry: 'aw_ts_super_Q_S', args: [RAW], ret: RET_RAW },
    { name: 'init', selector: 'init', encoding: '@@:', superEntry: 'aw_ts_super_0_P_o', args: [], ret: RET_OBJ('owned') },
    { name: 'initWithCoder_', selector: 'initWithCoder:', encoding: '@@:@', superEntry: 'aw_ts_super_P_P_o', args: [OBJ], ret: RET_OBJ('owned') },
    { name: 'length', selector: 'length', encoding: 'Q@:', superEntry: 'aw_ts_super_0_Q', args: [], ret: RET_RAW },
    { name: 'substringFromIndex_', selector: 'substringFromIndex:', encoding: '@@:Q', superEntry: 'aw_ts_super_Q_P', args: [RAW], ret: RET_OBJ() },
    { name: 'substringToIndex_', selector: 'substringToIndex:', encoding: '@@:Q', superEntry: 'aw_ts_super_Q_P', args: [RAW], ret: RET_OBJ() },
    { name: 'substringWithRange_', selector: 'substringWithRange:', encoding: '@@:{_NSRange=QQ}', superEntry: 'aw_ts_super_G_P', args: [RAW], ret: RET_OBJ() },
    { name: 'compare_', selector: 'compare:', encoding: 'q@:@', superEntry: 'aw_ts_super_P_q', args: [OBJ], ret: RET_RAW },
    { name: 'compare_options_', selector: 'compare:options:', encoding: 'q@:@Q', superEntry: 'aw_ts_super_PQ_q', args: [OBJ, RAW], ret: RET_RAW },
    { name: 'compare_options_range_', selector: 'compare:options:range:', encoding: 'q@:@Q{_NSRange=QQ}', superEntry: 'aw_ts_super_PQG_q', args: [OBJ, RAW, RAW], ret: RET_RAW },
    { name: 'compare_options_range_locale_', selector: 'compare:options:range:locale:', encoding: 'q@:@Q{_NSRange=QQ}@', superEntry: 'aw_ts_super_PQGP_q', args: [OBJ, RAW, RAW, OBJ], ret: RET_RAW },
    { name: 'caseInsensitiveCompare_', selector: 'caseInsensitiveCompare:', encoding: 'q@:@', superEntry: 'aw_ts_super_P_q', args: [OBJ], ret: RET_RAW },
    { name: 'localizedCompare_', selector: 'localizedCompare:', encoding: 'q@:@', superEntry: 'aw_ts_super_P_q', args: [OBJ], ret: RET_RAW },
    { name: 'localizedCaseInsensitiveCompare_', selector: 'localizedCaseInsensitiveCompare:', encoding: 'q@:@', superEntry: 'aw_ts_super_P_q', args: [OBJ], ret: RET_RAW },
    { name: 'localizedStandardCompare_', selector: 'localizedStandardCompare:', encoding: 'q@:@', superEntry: 'aw_ts_super_P_q', args: [OBJ], ret: RET_RAW },
    { name: 'isEqualToString_', selector: 'isEqualToString:', encoding: 'c@:@', superEntry: 'aw_ts_super_P_b', args: [OBJ], ret: RET_RAW },
    { name: 'hasPrefix_', selector: 'hasPrefix:', encoding: 'c@:@', superEntry: 'aw_ts_super_P_b', args: [OBJ], ret: RET_RAW },
    { name: 'hasSuffix_', selector: 'hasSuffix:', encoding: 'c@:@', superEntry: 'aw_ts_super_P_b', args: [OBJ], ret: RET_RAW },
    { name: 'commonPrefixWithString_options_', selector: 'commonPrefixWithString:options:', encoding: '@@:@Q', superEntry: 'aw_ts_super_PQ_P', args: [OBJ, RAW], ret: RET_OBJ() },
    { name: 'containsString_', selector: 'containsString:', encoding: 'c@:@', superEntry: 'aw_ts_super_P_b', args: [OBJ], ret: RET_RAW },
    { name: 'localizedCaseInsensitiveContainsString_', selector: 'localizedCaseInsensitiveContainsString:', encoding: 'c@:@', superEntry: 'aw_ts_super_P_b', args: [OBJ], ret: RET_RAW },
    { name: 'localizedStandardContainsString_', selector: 'localizedStandardContainsString:', encoding: 'c@:@', superEntry: 'aw_ts_super_P_b', args: [OBJ], ret: RET_RAW },
    { name: 'stringByAppendingString_', selector: 'stringByAppendingString:', encoding: '@@:@', superEntry: 'aw_ts_super_P_P', args: [OBJ], ret: RET_OBJ() },
    { name: 'uppercaseStringWithLocale_', selector: 'uppercaseStringWithLocale:', encoding: '@@:@', superEntry: 'aw_ts_super_P_P', args: [OBJ], ret: RET_OBJ() },
    { name: 'lowercaseStringWithLocale_', selector: 'lowercaseStringWithLocale:', encoding: '@@:@', superEntry: 'aw_ts_super_P_P', args: [OBJ], ret: RET_OBJ() },
    { name: 'capitalizedStringWithLocale_', selector: 'capitalizedStringWithLocale:', encoding: '@@:@', superEntry: 'aw_ts_super_P_P', args: [OBJ], ret: RET_OBJ() },
    { name: 'dataUsingEncoding_allowLossyConversion_', selector: 'dataUsingEncoding:allowLossyConversion:', encoding: '@@:Qc', superEntry: 'aw_ts_super_Qb_P', args: [RAW, RAW], ret: RET_OBJ() },
    { name: 'dataUsingEncoding_', selector: 'dataUsingEncoding:', encoding: '@@:Q', superEntry: 'aw_ts_super_Q_P', args: [RAW], ret: RET_OBJ() },
    { name: 'canBeConvertedToEncoding_', selector: 'canBeConvertedToEncoding:', encoding: 'c@:Q', superEntry: 'aw_ts_super_Q_b', args: [RAW], ret: RET_RAW },
    { name: 'maximumLengthOfBytesUsingEncoding_', selector: 'maximumLengthOfBytesUsingEncoding:', encoding: 'Q@:Q', superEntry: 'aw_ts_super_Q_Q', args: [RAW], ret: RET_RAW },
    { name: 'lengthOfBytesUsingEncoding_', selector: 'lengthOfBytesUsingEncoding:', encoding: 'Q@:Q', superEntry: 'aw_ts_super_Q_Q', args: [RAW], ret: RET_RAW },
    { name: 'componentsSeparatedByString_', selector: 'componentsSeparatedByString:', encoding: '@@:@', superEntry: 'aw_ts_super_P_P', args: [OBJ], ret: RET_OBJ() },
    { name: 'componentsSeparatedByCharactersInSet_', selector: 'componentsSeparatedByCharactersInSet:', encoding: '@@:@', superEntry: 'aw_ts_super_P_P', args: [OBJ], ret: RET_OBJ() },
    { name: 'stringByTrimmingCharactersInSet_', selector: 'stringByTrimmingCharactersInSet:', encoding: '@@:@', superEntry: 'aw_ts_super_P_P', args: [OBJ], ret: RET_OBJ() },
    { name: 'stringByPaddingToLength_withString_startingAtIndex_', selector: 'stringByPaddingToLength:withString:startingAtIndex:', encoding: '@@:Q@Q', superEntry: 'aw_ts_super_QPQ_P', args: [RAW, OBJ, RAW], ret: RET_OBJ() },
    { name: 'stringByFoldingWithOptions_locale_', selector: 'stringByFoldingWithOptions:locale:', encoding: '@@:Q@', superEntry: 'aw_ts_super_QP_P', args: [RAW, OBJ], ret: RET_OBJ() },
    { name: 'stringByReplacingOccurrencesOfString_withString_options_range_', selector: 'stringByReplacingOccurrencesOfString:withString:options:range:', encoding: '@@:@@Q{_NSRange=QQ}', superEntry: 'aw_ts_super_PPQG_P', args: [OBJ, OBJ, RAW, RAW], ret: RET_OBJ() },
    { name: 'stringByReplacingOccurrencesOfString_withString_', selector: 'stringByReplacingOccurrencesOfString:withString:', encoding: '@@:@@', superEntry: 'aw_ts_super_PP_P', args: [OBJ, OBJ], ret: RET_OBJ() },
    { name: 'stringByReplacingCharactersInRange_withString_', selector: 'stringByReplacingCharactersInRange:withString:', encoding: '@@:{_NSRange=QQ}@', superEntry: 'aw_ts_super_GP_P', args: [RAW, OBJ], ret: RET_OBJ() },
    { name: 'stringByApplyingTransform_reverse_', selector: 'stringByApplyingTransform:reverse:', encoding: '@@:@c', superEntry: 'aw_ts_super_Pb_P', args: [OBJ, RAW], ret: RET_OBJ() },
    { name: 'writeToURL_atomically_encoding_error_', selector: 'writeToURL:atomically:encoding:error:', encoding: 'c@:@cQ@', superEntry: 'aw_ts_super_PbQP_b', args: [OBJ, RAW, RAW, RAW], ret: RET_RAW },
    { name: 'writeToFile_atomically_encoding_error_', selector: 'writeToFile:atomically:encoding:error:', encoding: 'c@:@cQ@', superEntry: 'aw_ts_super_PbQP_b', args: [OBJ, RAW, RAW, RAW], ret: RET_RAW },
    { name: 'initWithString_', selector: 'initWithString:', encoding: '@@:@', superEntry: 'aw_ts_super_P_P_o', args: [OBJ], ret: RET_OBJ('owned') },
    { name: 'initWithData_encoding_', selector: 'initWithData:encoding:', encoding: '@@:@Q', superEntry: 'aw_ts_super_PQ_P_o', args: [OBJ, RAW], ret: RET_OBJ('owned') },
    { name: 'initWithContentsOfURL_encoding_error_', selector: 'initWithContentsOfURL:encoding:error:', encoding: '@@:@Q@', superEntry: 'aw_ts_super_PQP_P_o', args: [OBJ, RAW, RAW], ret: RET_OBJ('owned') },
    { name: 'initWithContentsOfFile_encoding_error_', selector: 'initWithContentsOfFile:encoding:error:', encoding: '@@:@Q@', superEntry: 'aw_ts_super_PQP_P_o', args: [OBJ, RAW, RAW], ret: RET_OBJ('owned') },
    { name: 'doubleValue', selector: 'doubleValue', encoding: 'd@:', superEntry: 'aw_ts_super_0_d', args: [], ret: RET_RAW },
    { name: 'floatValue', selector: 'floatValue', encoding: 'f@:', superEntry: 'aw_ts_super_0_f', args: [], ret: RET_RAW },
    { name: 'intValue', selector: 'intValue', encoding: 'i@:', superEntry: 'aw_ts_super_0_i', args: [], ret: RET_RAW },
    { name: 'integerValue', selector: 'integerValue', encoding: 'q@:', superEntry: 'aw_ts_super_0_q', args: [], ret: RET_RAW },
    { name: 'longLongValue', selector: 'longLongValue', encoding: 'q@:', superEntry: 'aw_ts_super_0_q', args: [], ret: RET_RAW },
    { name: 'boolValue', selector: 'boolValue', encoding: 'c@:', superEntry: 'aw_ts_super_0_b', args: [], ret: RET_RAW },
    { name: 'uppercaseString', selector: 'uppercaseString', encoding: '@@:', superEntry: 'aw_ts_super_0_P', args: [], ret: RET_OBJ() },
    { name: 'lowercaseString', selector: 'lowercaseString', encoding: '@@:', superEntry: 'aw_ts_super_0_P', args: [], ret: RET_OBJ() },
    { name: 'capitalizedString', selector: 'capitalizedString', encoding: '@@:', superEntry: 'aw_ts_super_0_P', args: [], ret: RET_OBJ() },
    { name: 'localizedUppercaseString', selector: 'localizedUppercaseString', encoding: '@@:', superEntry: 'aw_ts_super_0_P', args: [], ret: RET_OBJ() },
    { name: 'localizedLowercaseString', selector: 'localizedLowercaseString', encoding: '@@:', superEntry: 'aw_ts_super_0_P', args: [], ret: RET_OBJ() },
    { name: 'localizedCapitalizedString', selector: 'localizedCapitalizedString', encoding: '@@:', superEntry: 'aw_ts_super_0_P', args: [], ret: RET_OBJ() },
    { name: 'fastestEncoding', selector: 'fastestEncoding', encoding: 'Q@:', superEntry: 'aw_ts_super_0_Q', args: [], ret: RET_RAW },
    { name: 'smallestEncoding', selector: 'smallestEncoding', encoding: 'Q@:', superEntry: 'aw_ts_super_0_Q', args: [], ret: RET_RAW },
    { name: 'decomposedStringWithCanonicalMapping', selector: 'decomposedStringWithCanonicalMapping', encoding: '@@:', superEntry: 'aw_ts_super_0_P', args: [], ret: RET_OBJ() },
    { name: 'precomposedStringWithCanonicalMapping', selector: 'precomposedStringWithCanonicalMapping', encoding: '@@:', superEntry: 'aw_ts_super_0_P', args: [], ret: RET_OBJ() },
    { name: 'decomposedStringWithCompatibilityMapping', selector: 'decomposedStringWithCompatibilityMapping', encoding: '@@:', superEntry: 'aw_ts_super_0_P', args: [], ret: RET_OBJ() },
    { name: 'precomposedStringWithCompatibilityMapping', selector: 'precomposedStringWithCompatibilityMapping', encoding: '@@:', superEntry: 'aw_ts_super_0_P', args: [], ret: RET_OBJ() },
    { name: 'description', selector: 'description', encoding: '@@:', superEntry: 'aw_ts_super_0_P', args: [], ret: RET_OBJ() },
    { name: 'hash', selector: 'hash', encoding: 'Q@:', superEntry: 'aw_ts_super_0_Q', args: [], ret: RET_RAW },
    { name: 'propertyList', selector: 'propertyList', encoding: '@@:', superEntry: 'aw_ts_super_0_P', args: [], ret: RET_OBJ() },
    { name: 'propertyListFromStringsFileFormat', selector: 'propertyListFromStringsFileFormat', encoding: '@@:', superEntry: 'aw_ts_super_0_P', args: [], ret: RET_OBJ() },
    { name: 'variantFittingPresentationWidth_', selector: 'variantFittingPresentationWidth:', encoding: '@@:q', superEntry: 'aw_ts_super_q_P', args: [RAW], ret: RET_OBJ() },
    { name: 'stringByAppendingPathComponent_', selector: 'stringByAppendingPathComponent:', encoding: '@@:@', superEntry: 'aw_ts_super_P_P', args: [OBJ], ret: RET_OBJ() },
    { name: 'stringByAppendingPathExtension_', selector: 'stringByAppendingPathExtension:', encoding: '@@:@', superEntry: 'aw_ts_super_P_P', args: [OBJ], ret: RET_OBJ() },
    { name: 'stringsByAppendingPaths_', selector: 'stringsByAppendingPaths:', encoding: '@@:@', superEntry: 'aw_ts_super_P_P', args: [OBJ], ret: RET_OBJ() },
    { name: 'pathComponents', selector: 'pathComponents', encoding: '@@:', superEntry: 'aw_ts_super_0_P', args: [], ret: RET_OBJ() },
    { name: 'isAbsolutePath', selector: 'isAbsolutePath', encoding: 'c@:', superEntry: 'aw_ts_super_0_b', args: [], ret: RET_RAW },
    { name: 'lastPathComponent', selector: 'lastPathComponent', encoding: '@@:', superEntry: 'aw_ts_super_0_P', args: [], ret: RET_OBJ() },
    { name: 'stringByDeletingLastPathComponent', selector: 'stringByDeletingLastPathComponent', encoding: '@@:', superEntry: 'aw_ts_super_0_P', args: [], ret: RET_OBJ() },
    { name: 'pathExtension', selector: 'pathExtension', encoding: '@@:', superEntry: 'aw_ts_super_0_P', args: [], ret: RET_OBJ() },
    { name: 'stringByDeletingPathExtension', selector: 'stringByDeletingPathExtension', encoding: '@@:', superEntry: 'aw_ts_super_0_P', args: [], ret: RET_OBJ() },
    { name: 'stringByAbbreviatingWithTildeInPath', selector: 'stringByAbbreviatingWithTildeInPath', encoding: '@@:', superEntry: 'aw_ts_super_0_P', args: [], ret: RET_OBJ() },
    { name: 'stringByExpandingTildeInPath', selector: 'stringByExpandingTildeInPath', encoding: '@@:', superEntry: 'aw_ts_super_0_P', args: [], ret: RET_OBJ() },
    { name: 'stringByStandardizingPath', selector: 'stringByStandardizingPath', encoding: '@@:', superEntry: 'aw_ts_super_0_P', args: [], ret: RET_OBJ() },
    { name: 'stringByResolvingSymlinksInPath', selector: 'stringByResolvingSymlinksInPath', encoding: '@@:', superEntry: 'aw_ts_super_0_P', args: [], ret: RET_OBJ() },
    { name: 'stringByAddingPercentEncodingWithAllowedCharacters_', selector: 'stringByAddingPercentEncodingWithAllowedCharacters:', encoding: '@@:@', superEntry: 'aw_ts_super_P_P', args: [OBJ], ret: RET_OBJ() },
    { name: 'stringByRemovingPercentEncoding', selector: 'stringByRemovingPercentEncoding', encoding: '@@:', superEntry: 'aw_ts_super_0_P', args: [], ret: RET_OBJ() },
    { name: 'encodeWithCoder_', selector: 'encodeWithCoder:', encoding: 'v@:@', superEntry: 'aw_ts_super_P_v', args: [OBJ], ret: RET_RAW },
  ];

  static readonly __cls: bigint = __class('NSString');

  static localizedNameOfStringEncoding_(encoding: number): NSString {
    const __ret = __dispatch.aw_ts_msg_Q_P(NSString.__cls, __sel('localizedNameOfStringEncoding:'), encoding);
    return __wrapRetained(NSString, __ret)!;
  }

  static string(): NSString {
    const __ret = __dispatch.aw_ts_msg_0_P(NSString.__cls, __sel('string'));
    return __wrapRetained(NSString, __ret)!;
  }

  static stringWithString_(string: NSString): NSString {
    const __ret = __dispatch.aw_ts_msg_P_P(NSString.__cls, __sel('stringWithString:'), __unwrap(string));
    return __wrapRetained(NSString, __ret)!;
  }

  static stringWithUTF8String_(nullTerminatedCString: string): NSString {
    const __ret = __dispatch.aw_ts_msg_N_P(NSString.__cls, __sel('stringWithUTF8String:'), nullTerminatedCString);
    return __wrapRetained(NSString, __ret)!;
  }

  static stringWithCString_encoding_(cString: string, enc: number): NSString {
    const __ret = __dispatch.aw_ts_msg_NQ_P(NSString.__cls, __sel('stringWithCString:encoding:'), cString, enc);
    return __wrapRetained(NSString, __ret)!;
  }

  static stringWithContentsOfURL_encoding_error_(url: NSURL, enc: number): Result<NSString> {
    return __resultRetained(NSString, __dispatch.aw_ts_msg_PQ_P_e(NSString.__cls, __sel('stringWithContentsOfURL:encoding:error:'), __unwrap(url), enc));
  }

  static stringWithContentsOfFile_encoding_error_(path: NSString, enc: number): Result<NSString> {
    return __resultRetained(NSString, __dispatch.aw_ts_msg_PQ_P_e(NSString.__cls, __sel('stringWithContentsOfFile:encoding:error:'), __unwrap(path), enc));
  }

  static defaultCStringEncoding(): number {
    return __dispatch.aw_ts_msg_0_Q(NSString.__cls, __sel('defaultCStringEncoding'));
  }

  static pathWithComponents_(components: NSArray): NSString {
    const __ret = __dispatch.aw_ts_msg_P_P(NSString.__cls, __sel('pathWithComponents:'), __unwrap(components));
    return __wrapRetained(NSString, __ret)!;
  }

  static supportsSecureCoding(): boolean {
    return __dispatch.aw_ts_msg_0_b(NSString.__cls, __sel('supportsSecureCoding'));
  }

  static writableTypeIdentifiersForItemProvider(): NSArray {
    const __ret = __dispatch.aw_ts_msg_0_P(NSString.__cls, __sel('writableTypeIdentifiersForItemProvider'));
    return __wrapRetained(NSArray, __ret)!;
  }

  characterAtIndex_(index: number): number {
    return __dispatch.aw_ts_msg_Q_S(__unwrap(this), __sel('characterAtIndex:'), index);
  }

  init(): this {
    const __ret = __dispatch.aw_ts_msg_0_P_o(__unwrap(this), __sel('init'));
    return __wrapOwned<this>(__ret)!;
  }

  initWithCoder_(coder: NSCoder): this {
    const __ret = __dispatch.aw_ts_msg_P_P_o(__unwrap(this), __sel('initWithCoder:'), __unwrap(coder));
    return __wrapOwned<this>(__ret)!;
  }

  length(): number {
    return __dispatch.aw_ts_msg_0_Q(__unwrap(this), __sel('length'));
  }

  substringFromIndex_(from: number): NSString {
    const __ret = __dispatch.aw_ts_msg_Q_P(__unwrap(this), __sel('substringFromIndex:'), from);
    return __wrapRetained(NSString, __ret)!;
  }

  substringToIndex_(to: number): NSString {
    const __ret = __dispatch.aw_ts_msg_Q_P(__unwrap(this), __sel('substringToIndex:'), to);
    return __wrapRetained(NSString, __ret)!;
  }

  substringWithRange_(range: NSRange): NSString {
    const __ret = __dispatch.aw_ts_msg_G_P(__unwrap(this), __sel('substringWithRange:'), range);
    return __wrapRetained(NSString, __ret)!;
  }

  compare_(string: NSString): NSComparisonResult {
    return __dispatch.aw_ts_msg_P_q(__unwrap(this), __sel('compare:'), __unwrap(string)) as NSComparisonResult;
  }

  compare_options_(string: NSString, mask: NSStringCompareOptions): NSComparisonResult {
    return __dispatch.aw_ts_msg_PQ_q(__unwrap(this), __sel('compare:options:'), __unwrap(string), mask) as NSComparisonResult;
  }

  compare_options_range_(string: NSString, mask: NSStringCompareOptions, rangeOfReceiverToCompare: NSRange): NSComparisonResult {
    return __dispatch.aw_ts_msg_PQG_q(__unwrap(this), __sel('compare:options:range:'), __unwrap(string), mask, rangeOfReceiverToCompare) as NSComparisonResult;
  }

  compare_options_range_locale_(string: NSString, mask: NSStringCompareOptions, rangeOfReceiverToCompare: NSRange, locale: NSObject): NSComparisonResult {
    return __dispatch.aw_ts_msg_PQGP_q(__unwrap(this), __sel('compare:options:range:locale:'), __unwrap(string), mask, rangeOfReceiverToCompare, __unwrap(locale)) as NSComparisonResult;
  }

  caseInsensitiveCompare_(string: NSString): NSComparisonResult {
    return __dispatch.aw_ts_msg_P_q(__unwrap(this), __sel('caseInsensitiveCompare:'), __unwrap(string)) as NSComparisonResult;
  }

  localizedCompare_(string: NSString): NSComparisonResult {
    return __dispatch.aw_ts_msg_P_q(__unwrap(this), __sel('localizedCompare:'), __unwrap(string)) as NSComparisonResult;
  }

  localizedCaseInsensitiveCompare_(string: NSString): NSComparisonResult {
    return __dispatch.aw_ts_msg_P_q(__unwrap(this), __sel('localizedCaseInsensitiveCompare:'), __unwrap(string)) as NSComparisonResult;
  }

  localizedStandardCompare_(string: NSString): NSComparisonResult {
    return __dispatch.aw_ts_msg_P_q(__unwrap(this), __sel('localizedStandardCompare:'), __unwrap(string)) as NSComparisonResult;
  }

  isEqualToString_(aString: NSString): boolean {
    return __dispatch.aw_ts_msg_P_b(__unwrap(this), __sel('isEqualToString:'), __unwrap(aString));
  }

  hasPrefix_(str: NSString): boolean {
    return __dispatch.aw_ts_msg_P_b(__unwrap(this), __sel('hasPrefix:'), __unwrap(str));
  }

  hasSuffix_(str: NSString): boolean {
    return __dispatch.aw_ts_msg_P_b(__unwrap(this), __sel('hasSuffix:'), __unwrap(str));
  }

  commonPrefixWithString_options_(str: NSString, mask: NSStringCompareOptions): NSString {
    const __ret = __dispatch.aw_ts_msg_PQ_P(__unwrap(this), __sel('commonPrefixWithString:options:'), __unwrap(str), mask);
    return __wrapRetained(NSString, __ret)!;
  }

  containsString_(str: NSString): boolean {
    return __dispatch.aw_ts_msg_P_b(__unwrap(this), __sel('containsString:'), __unwrap(str));
  }

  localizedCaseInsensitiveContainsString_(str: NSString): boolean {
    return __dispatch.aw_ts_msg_P_b(__unwrap(this), __sel('localizedCaseInsensitiveContainsString:'), __unwrap(str));
  }

  localizedStandardContainsString_(str: NSString): boolean {
    return __dispatch.aw_ts_msg_P_b(__unwrap(this), __sel('localizedStandardContainsString:'), __unwrap(str));
  }

  localizedStandardRangeOfString_(str: NSString): NSRange {
    return __dispatch.aw_ts_msg_P_G(__unwrap(this), __sel('localizedStandardRangeOfString:'), __unwrap(str));
  }

  rangeOfString_(searchString: NSString): NSRange {
    return __dispatch.aw_ts_msg_P_G(__unwrap(this), __sel('rangeOfString:'), __unwrap(searchString));
  }

  rangeOfString_options_(searchString: NSString, mask: NSStringCompareOptions): NSRange {
    return __dispatch.aw_ts_msg_PQ_G(__unwrap(this), __sel('rangeOfString:options:'), __unwrap(searchString), mask);
  }

  rangeOfString_options_range_(searchString: NSString, mask: NSStringCompareOptions, rangeOfReceiverToSearch: NSRange): NSRange {
    return __dispatch.aw_ts_msg_PQG_G(__unwrap(this), __sel('rangeOfString:options:range:'), __unwrap(searchString), mask, rangeOfReceiverToSearch);
  }

  rangeOfString_options_range_locale_(searchString: NSString, mask: NSStringCompareOptions, rangeOfReceiverToSearch: NSRange, locale: NSLocale): NSRange {
    return __dispatch.aw_ts_msg_PQGP_G(__unwrap(this), __sel('rangeOfString:options:range:locale:'), __unwrap(searchString), mask, rangeOfReceiverToSearch, __unwrap(locale));
  }

  rangeOfCharacterFromSet_(searchSet: NSCharacterSet): NSRange {
    return __dispatch.aw_ts_msg_P_G(__unwrap(this), __sel('rangeOfCharacterFromSet:'), __unwrap(searchSet));
  }

  rangeOfCharacterFromSet_options_(searchSet: NSCharacterSet, mask: NSStringCompareOptions): NSRange {
    return __dispatch.aw_ts_msg_PQ_G(__unwrap(this), __sel('rangeOfCharacterFromSet:options:'), __unwrap(searchSet), mask);
  }

  rangeOfCharacterFromSet_options_range_(searchSet: NSCharacterSet, mask: NSStringCompareOptions, rangeOfReceiverToSearch: NSRange): NSRange {
    return __dispatch.aw_ts_msg_PQG_G(__unwrap(this), __sel('rangeOfCharacterFromSet:options:range:'), __unwrap(searchSet), mask, rangeOfReceiverToSearch);
  }

  rangeOfComposedCharacterSequenceAtIndex_(index: number): NSRange {
    return __dispatch.aw_ts_msg_Q_G(__unwrap(this), __sel('rangeOfComposedCharacterSequenceAtIndex:'), index);
  }

  rangeOfComposedCharacterSequencesForRange_(range: NSRange): NSRange {
    return __dispatch.aw_ts_msg_G_G(__unwrap(this), __sel('rangeOfComposedCharacterSequencesForRange:'), range);
  }

  stringByAppendingString_(aString: NSString): NSString {
    const __ret = __dispatch.aw_ts_msg_P_P(__unwrap(this), __sel('stringByAppendingString:'), __unwrap(aString));
    return __wrapRetained(NSString, __ret)!;
  }

  uppercaseStringWithLocale_(locale: NSLocale): NSString {
    const __ret = __dispatch.aw_ts_msg_P_P(__unwrap(this), __sel('uppercaseStringWithLocale:'), __unwrap(locale));
    return __wrapRetained(NSString, __ret)!;
  }

  lowercaseStringWithLocale_(locale: NSLocale): NSString {
    const __ret = __dispatch.aw_ts_msg_P_P(__unwrap(this), __sel('lowercaseStringWithLocale:'), __unwrap(locale));
    return __wrapRetained(NSString, __ret)!;
  }

  capitalizedStringWithLocale_(locale: NSLocale): NSString {
    const __ret = __dispatch.aw_ts_msg_P_P(__unwrap(this), __sel('capitalizedStringWithLocale:'), __unwrap(locale));
    return __wrapRetained(NSString, __ret)!;
  }

  lineRangeForRange_(range: NSRange): NSRange {
    return __dispatch.aw_ts_msg_G_G(__unwrap(this), __sel('lineRangeForRange:'), range);
  }

  paragraphRangeForRange_(range: NSRange): NSRange {
    return __dispatch.aw_ts_msg_G_G(__unwrap(this), __sel('paragraphRangeForRange:'), range);
  }

  dataUsingEncoding_allowLossyConversion_(encoding: number, lossy: boolean): NSData {
    const __ret = __dispatch.aw_ts_msg_Qb_P(__unwrap(this), __sel('dataUsingEncoding:allowLossyConversion:'), encoding, lossy);
    return __wrapRetained(NSData, __ret)!;
  }

  dataUsingEncoding_(encoding: number): NSData {
    const __ret = __dispatch.aw_ts_msg_Q_P(__unwrap(this), __sel('dataUsingEncoding:'), encoding);
    return __wrapRetained(NSData, __ret)!;
  }

  canBeConvertedToEncoding_(encoding: number): boolean {
    return __dispatch.aw_ts_msg_Q_b(__unwrap(this), __sel('canBeConvertedToEncoding:'), encoding);
  }

  cStringUsingEncoding_(encoding: number): string {
    return __dispatch.aw_ts_msg_Q_N(__unwrap(this), __sel('cStringUsingEncoding:'), encoding);
  }

  maximumLengthOfBytesUsingEncoding_(enc: number): number {
    return __dispatch.aw_ts_msg_Q_Q(__unwrap(this), __sel('maximumLengthOfBytesUsingEncoding:'), enc);
  }

  lengthOfBytesUsingEncoding_(enc: number): number {
    return __dispatch.aw_ts_msg_Q_Q(__unwrap(this), __sel('lengthOfBytesUsingEncoding:'), enc);
  }

  componentsSeparatedByString_(separator: NSString): NSArray {
    const __ret = __dispatch.aw_ts_msg_P_P(__unwrap(this), __sel('componentsSeparatedByString:'), __unwrap(separator));
    return __wrapRetained(NSArray, __ret)!;
  }

  componentsSeparatedByCharactersInSet_(separator: NSCharacterSet): NSArray {
    const __ret = __dispatch.aw_ts_msg_P_P(__unwrap(this), __sel('componentsSeparatedByCharactersInSet:'), __unwrap(separator));
    return __wrapRetained(NSArray, __ret)!;
  }

  stringByTrimmingCharactersInSet_(set: NSCharacterSet): NSString {
    const __ret = __dispatch.aw_ts_msg_P_P(__unwrap(this), __sel('stringByTrimmingCharactersInSet:'), __unwrap(set));
    return __wrapRetained(NSString, __ret)!;
  }

  stringByPaddingToLength_withString_startingAtIndex_(newLength: number, padString: NSString, padIndex: number): NSString {
    const __ret = __dispatch.aw_ts_msg_QPQ_P(__unwrap(this), __sel('stringByPaddingToLength:withString:startingAtIndex:'), newLength, __unwrap(padString), padIndex);
    return __wrapRetained(NSString, __ret)!;
  }

  stringByFoldingWithOptions_locale_(options: NSStringCompareOptions, locale: NSLocale): NSString {
    const __ret = __dispatch.aw_ts_msg_QP_P(__unwrap(this), __sel('stringByFoldingWithOptions:locale:'), options, __unwrap(locale));
    return __wrapRetained(NSString, __ret)!;
  }

  stringByReplacingOccurrencesOfString_withString_options_range_(target: NSString, replacement: NSString, options: NSStringCompareOptions, searchRange: NSRange): NSString {
    const __ret = __dispatch.aw_ts_msg_PPQG_P(__unwrap(this), __sel('stringByReplacingOccurrencesOfString:withString:options:range:'), __unwrap(target), __unwrap(replacement), options, searchRange);
    return __wrapRetained(NSString, __ret)!;
  }

  stringByReplacingOccurrencesOfString_withString_(target: NSString, replacement: NSString): NSString {
    const __ret = __dispatch.aw_ts_msg_PP_P(__unwrap(this), __sel('stringByReplacingOccurrencesOfString:withString:'), __unwrap(target), __unwrap(replacement));
    return __wrapRetained(NSString, __ret)!;
  }

  stringByReplacingCharactersInRange_withString_(range: NSRange, replacement: NSString): NSString {
    const __ret = __dispatch.aw_ts_msg_GP_P(__unwrap(this), __sel('stringByReplacingCharactersInRange:withString:'), range, __unwrap(replacement));
    return __wrapRetained(NSString, __ret)!;
  }

  stringByApplyingTransform_reverse_(transform: NSString, reverse: boolean): NSString {
    const __ret = __dispatch.aw_ts_msg_Pb_P(__unwrap(this), __sel('stringByApplyingTransform:reverse:'), __unwrap(transform), reverse);
    return __wrapRetained(NSString, __ret)!;
  }

  writeToURL_atomically_encoding_error_(url: NSURL, useAuxiliaryFile: boolean, enc: number): Result<boolean> {
    return __resultScalar(__dispatch.aw_ts_msg_PbQ_b_e(__unwrap(this), __sel('writeToURL:atomically:encoding:error:'), __unwrap(url), useAuxiliaryFile, enc));
  }

  writeToFile_atomically_encoding_error_(path: NSString, useAuxiliaryFile: boolean, enc: number): Result<boolean> {
    return __resultScalar(__dispatch.aw_ts_msg_PbQ_b_e(__unwrap(this), __sel('writeToFile:atomically:encoding:error:'), __unwrap(path), useAuxiliaryFile, enc));
  }

  initWithUTF8String_(nullTerminatedCString: string): this {
    const __ret = __dispatch.aw_ts_msg_N_P_o(__unwrap(this), __sel('initWithUTF8String:'), nullTerminatedCString);
    return __wrapOwned<this>(__ret)!;
  }

  initWithString_(aString: NSString): this {
    const __ret = __dispatch.aw_ts_msg_P_P_o(__unwrap(this), __sel('initWithString:'), __unwrap(aString));
    return __wrapOwned<this>(__ret)!;
  }

  initWithData_encoding_(data: NSData, encoding: number): this {
    const __ret = __dispatch.aw_ts_msg_PQ_P_o(__unwrap(this), __sel('initWithData:encoding:'), __unwrap(data), encoding);
    return __wrapOwned<this>(__ret)!;
  }

  initWithCString_encoding_(nullTerminatedCString: string, encoding: number): this {
    const __ret = __dispatch.aw_ts_msg_NQ_P_o(__unwrap(this), __sel('initWithCString:encoding:'), nullTerminatedCString, encoding);
    return __wrapOwned<this>(__ret)!;
  }

  initWithContentsOfURL_encoding_error_(url: NSURL, enc: number): Result<this> {
    return __resultOwned<this>(__dispatch.aw_ts_msg_PQ_P_o_e(__unwrap(this), __sel('initWithContentsOfURL:encoding:error:'), __unwrap(url), enc));
  }

  initWithContentsOfFile_encoding_error_(path: NSString, enc: number): Result<this> {
    return __resultOwned<this>(__dispatch.aw_ts_msg_PQ_P_o_e(__unwrap(this), __sel('initWithContentsOfFile:encoding:error:'), __unwrap(path), enc));
  }

  doubleValue(): number {
    return __dispatch.aw_ts_msg_0_d(__unwrap(this), __sel('doubleValue'));
  }

  floatValue(): number {
    return __dispatch.aw_ts_msg_0_f(__unwrap(this), __sel('floatValue'));
  }

  intValue(): number {
    return __dispatch.aw_ts_msg_0_i(__unwrap(this), __sel('intValue'));
  }

  integerValue(): number {
    return __dispatch.aw_ts_msg_0_q(__unwrap(this), __sel('integerValue'));
  }

  longLongValue(): number {
    return __dispatch.aw_ts_msg_0_q(__unwrap(this), __sel('longLongValue'));
  }

  boolValue(): boolean {
    return __dispatch.aw_ts_msg_0_b(__unwrap(this), __sel('boolValue'));
  }

  uppercaseString(): NSString {
    const __ret = __dispatch.aw_ts_msg_0_P(__unwrap(this), __sel('uppercaseString'));
    return __wrapRetained(NSString, __ret)!;
  }

  lowercaseString(): NSString {
    const __ret = __dispatch.aw_ts_msg_0_P(__unwrap(this), __sel('lowercaseString'));
    return __wrapRetained(NSString, __ret)!;
  }

  capitalizedString(): NSString {
    const __ret = __dispatch.aw_ts_msg_0_P(__unwrap(this), __sel('capitalizedString'));
    return __wrapRetained(NSString, __ret)!;
  }

  localizedUppercaseString(): NSString {
    const __ret = __dispatch.aw_ts_msg_0_P(__unwrap(this), __sel('localizedUppercaseString'));
    return __wrapRetained(NSString, __ret)!;
  }

  localizedLowercaseString(): NSString {
    const __ret = __dispatch.aw_ts_msg_0_P(__unwrap(this), __sel('localizedLowercaseString'));
    return __wrapRetained(NSString, __ret)!;
  }

  localizedCapitalizedString(): NSString {
    const __ret = __dispatch.aw_ts_msg_0_P(__unwrap(this), __sel('localizedCapitalizedString'));
    return __wrapRetained(NSString, __ret)!;
  }

  UTF8String(): string {
    return __dispatch.aw_ts_msg_0_N(__unwrap(this), __sel('UTF8String'));
  }

  fastestEncoding(): number {
    return __dispatch.aw_ts_msg_0_Q(__unwrap(this), __sel('fastestEncoding'));
  }

  smallestEncoding(): number {
    return __dispatch.aw_ts_msg_0_Q(__unwrap(this), __sel('smallestEncoding'));
  }

  decomposedStringWithCanonicalMapping(): NSString {
    const __ret = __dispatch.aw_ts_msg_0_P(__unwrap(this), __sel('decomposedStringWithCanonicalMapping'));
    return __wrapRetained(NSString, __ret)!;
  }

  precomposedStringWithCanonicalMapping(): NSString {
    const __ret = __dispatch.aw_ts_msg_0_P(__unwrap(this), __sel('precomposedStringWithCanonicalMapping'));
    return __wrapRetained(NSString, __ret)!;
  }

  decomposedStringWithCompatibilityMapping(): NSString {
    const __ret = __dispatch.aw_ts_msg_0_P(__unwrap(this), __sel('decomposedStringWithCompatibilityMapping'));
    return __wrapRetained(NSString, __ret)!;
  }

  precomposedStringWithCompatibilityMapping(): NSString {
    const __ret = __dispatch.aw_ts_msg_0_P(__unwrap(this), __sel('precomposedStringWithCompatibilityMapping'));
    return __wrapRetained(NSString, __ret)!;
  }

  description(): NSString {
    const __ret = __dispatch.aw_ts_msg_0_P(__unwrap(this), __sel('description'));
    return __wrapRetained(NSString, __ret)!;
  }

  hash(): number {
    return __dispatch.aw_ts_msg_0_Q(__unwrap(this), __sel('hash'));
  }

  propertyList(): NSObject {
    const __ret = __dispatch.aw_ts_msg_0_P(__unwrap(this), __sel('propertyList'));
    return __wrapRetained(__ret)!;
  }

  propertyListFromStringsFileFormat(): NSDictionary {
    const __ret = __dispatch.aw_ts_msg_0_P(__unwrap(this), __sel('propertyListFromStringsFileFormat'));
    return __wrapRetained(NSDictionary, __ret)!;
  }

  variantFittingPresentationWidth_(width: number): NSString {
    const __ret = __dispatch.aw_ts_msg_q_P(__unwrap(this), __sel('variantFittingPresentationWidth:'), width);
    return __wrapRetained(NSString, __ret)!;
  }

  stringByAppendingPathComponent_(str: NSString): NSString {
    const __ret = __dispatch.aw_ts_msg_P_P(__unwrap(this), __sel('stringByAppendingPathComponent:'), __unwrap(str));
    return __wrapRetained(NSString, __ret)!;
  }

  stringByAppendingPathExtension_(str: NSString): NSString {
    const __ret = __dispatch.aw_ts_msg_P_P(__unwrap(this), __sel('stringByAppendingPathExtension:'), __unwrap(str));
    return __wrapRetained(NSString, __ret)!;
  }

  stringsByAppendingPaths_(paths: NSArray): NSArray {
    const __ret = __dispatch.aw_ts_msg_P_P(__unwrap(this), __sel('stringsByAppendingPaths:'), __unwrap(paths));
    return __wrapRetained(NSArray, __ret)!;
  }

  pathComponents(): NSArray {
    const __ret = __dispatch.aw_ts_msg_0_P(__unwrap(this), __sel('pathComponents'));
    return __wrapRetained(NSArray, __ret)!;
  }

  isAbsolutePath(): boolean {
    return __dispatch.aw_ts_msg_0_b(__unwrap(this), __sel('isAbsolutePath'));
  }

  lastPathComponent(): NSString {
    const __ret = __dispatch.aw_ts_msg_0_P(__unwrap(this), __sel('lastPathComponent'));
    return __wrapRetained(NSString, __ret)!;
  }

  stringByDeletingLastPathComponent(): NSString {
    const __ret = __dispatch.aw_ts_msg_0_P(__unwrap(this), __sel('stringByDeletingLastPathComponent'));
    return __wrapRetained(NSString, __ret)!;
  }

  pathExtension(): NSString {
    const __ret = __dispatch.aw_ts_msg_0_P(__unwrap(this), __sel('pathExtension'));
    return __wrapRetained(NSString, __ret)!;
  }

  stringByDeletingPathExtension(): NSString {
    const __ret = __dispatch.aw_ts_msg_0_P(__unwrap(this), __sel('stringByDeletingPathExtension'));
    return __wrapRetained(NSString, __ret)!;
  }

  stringByAbbreviatingWithTildeInPath(): NSString {
    const __ret = __dispatch.aw_ts_msg_0_P(__unwrap(this), __sel('stringByAbbreviatingWithTildeInPath'));
    return __wrapRetained(NSString, __ret)!;
  }

  stringByExpandingTildeInPath(): NSString {
    const __ret = __dispatch.aw_ts_msg_0_P(__unwrap(this), __sel('stringByExpandingTildeInPath'));
    return __wrapRetained(NSString, __ret)!;
  }

  stringByStandardizingPath(): NSString {
    const __ret = __dispatch.aw_ts_msg_0_P(__unwrap(this), __sel('stringByStandardizingPath'));
    return __wrapRetained(NSString, __ret)!;
  }

  stringByResolvingSymlinksInPath(): NSString {
    const __ret = __dispatch.aw_ts_msg_0_P(__unwrap(this), __sel('stringByResolvingSymlinksInPath'));
    return __wrapRetained(NSString, __ret)!;
  }

  fileSystemRepresentation(): string {
    return __dispatch.aw_ts_msg_0_N(__unwrap(this), __sel('fileSystemRepresentation'));
  }

  stringByAddingPercentEncodingWithAllowedCharacters_(allowedCharacters: NSCharacterSet): NSString {
    const __ret = __dispatch.aw_ts_msg_P_P(__unwrap(this), __sel('stringByAddingPercentEncodingWithAllowedCharacters:'), __unwrap(allowedCharacters));
    return __wrapRetained(NSString, __ret)!;
  }

  stringByRemovingPercentEncoding(): NSString {
    const __ret = __dispatch.aw_ts_msg_0_P(__unwrap(this), __sel('stringByRemovingPercentEncoding'));
    return __wrapRetained(NSString, __ret)!;
  }

  encodeWithCoder_(coder: NSCoder): void {
    __dispatch.aw_ts_msg_P_v(__unwrap(this), __sel('encodeWithCoder:'), __unwrap(coder));
  }
}
