// Generated by apianyware emit-typescript — DO NOT EDIT.
// Type surface: NSValue (Foundation)
//
// Declaration-only .d.ts, co-generated with the .ts class body from one IR pass
// (ADR-0055 §2) so runtime and types cannot drift: the public type surface tsc and
// consumers see — no bodies, no __cls/dispatch internals, no runtime-seam helpers.

import {
  NSCoder,
} from '@apianyware/foundation';
import {
  NSObject,
} from '@apianyware/runtime';
import type {
  NSCoding,
  NSSecureCoding,
} from '@apianyware/foundation';
import type {
  CGPoint,
  CGRect,
  CGSize,
  NSEdgeInsets,
  NSRange,
} from '@apianyware/runtime';

export class NSValue extends NSObject implements NSSecureCoding, NSCoding {
  static valueWithNonretainedObject_(anObject: NSObject): NSValue;
  static valueWithRange_(range: NSRange): NSValue;
  static valueWithPoint_(point: CGPoint): NSValue;
  static valueWithSize_(size: CGSize): NSValue;
  static valueWithRect_(rect: CGRect): NSValue;
  static valueWithEdgeInsets_(insets: NSEdgeInsets): NSValue;
  static supportsSecureCoding(): boolean;
  initWithCoder_(coder: NSCoder): this;
  objCType(): string;
  isEqualToValue_(value: NSValue): boolean;
  nonretainedObjectValue(): NSObject;
  rangeValue(): NSRange;
  pointValue(): CGPoint;
  sizeValue(): CGSize;
  rectValue(): CGRect;
  edgeInsetsValue(): NSEdgeInsets;
  encodeWithCoder_(coder: NSCoder): void;
  init(): this;
}
