// Generated by apianyware emit-typescript — DO NOT EDIT.
// Class: NSValue (Foundation)
//
// Runtime seam (Step 3 provides these from '@apianyware/runtime'; ADR-0055/0057):
//   NSObject — branded-handle root class; its internal ctor wraps a handle and hosts
//     [Symbol.dispose]. Emitted subclasses inherit both and declare neither.
//   __unwrap(obj) — obj's native handle (0n for null; throws on a disposed handle).
//   __wrapRetained(Cls, id) / __wrapOwned(Cls, id) — the +0 / +1 uniqued branded
//     wrapper (null when id is 0n; retain folds into the dispatch entry).
//   __class(name) — the Class handle; __sel(sel) — the interned SEL handle.
//   __registerClass(name, cls) — registers this class so a Class RETURN resolves back
//     to it; __classArg(cls) / __classCtor(id) — the Class value crossing, in / out;
//     __selName(sel) — a SEL handle back to its selector-name string.
//   __dispatch.aw_ts_msg_<codes>(recv, sel, …) — the addon's per-signature entry.
//   __init(obj) — the universal `-init` primitive for a class whose real ancestry
//     never redeclares it (k122): the same id -> id dispatch shape a real init() body
//     calls, reused as one shared runtime primitive rather than a per-class copy.

import {
  NSCoder,
} from '@apianyware/foundation';
import {
  NSObject,
  OBJ,
  RET_OBJ,
  RET_RAW,
  __class,
  __dispatch,
  __init,
  __registerClass,
  __sel,
  __unwrap,
  __wrapOwned,
  __wrapRetained,
} from '@apianyware/runtime';
import type {
  NSCoding,
  NSSecureCoding,
} from '@apianyware/foundation';
import type {
  CGPoint,
  CGRect,
  CGSize,
  NSEdgeInsets,
  NSRange,
  OverridableMethod,
} from '@apianyware/runtime';

export class NSValue extends NSObject implements NSSecureCoding, NSCoding {
  static { __registerClass('NSValue', NSValue); }

  static readonly __overridable: readonly OverridableMethod[] = [
    { name: 'initWithCoder_', selector: 'initWithCoder:', encoding: '@@:@', superEntry: 'aw_ts_super_P_P_o', args: [OBJ], ret: RET_OBJ('owned') },
    { name: 'isEqualToValue_', selector: 'isEqualToValue:', encoding: 'c@:@', superEntry: 'aw_ts_super_P_b', args: [OBJ], ret: RET_RAW },
    { name: 'nonretainedObjectValue', selector: 'nonretainedObjectValue', encoding: '@@:', superEntry: 'aw_ts_super_0_P', args: [], ret: RET_OBJ() },
    { name: 'encodeWithCoder_', selector: 'encodeWithCoder:', encoding: 'v@:@', superEntry: 'aw_ts_super_P_v', args: [OBJ], ret: RET_RAW },
  ];

  static readonly __cls: bigint = __class('NSValue');

  static valueWithNonretainedObject_(anObject: NSObject): NSValue {
    const __ret = __dispatch.aw_ts_msg_P_P(NSValue.__cls, __sel('valueWithNonretainedObject:'), __unwrap(anObject));
    return __wrapRetained(NSValue, __ret)!;
  }

  static valueWithRange_(range: NSRange): NSValue {
    const __ret = __dispatch.aw_ts_msg_G_P(NSValue.__cls, __sel('valueWithRange:'), range);
    return __wrapRetained(NSValue, __ret)!;
  }

  static valueWithPoint_(point: CGPoint): NSValue {
    const __ret = __dispatch.aw_ts_msg_O_P(NSValue.__cls, __sel('valueWithPoint:'), point);
    return __wrapRetained(NSValue, __ret)!;
  }

  static valueWithSize_(size: CGSize): NSValue {
    const __ret = __dispatch.aw_ts_msg_Z_P(NSValue.__cls, __sel('valueWithSize:'), size);
    return __wrapRetained(NSValue, __ret)!;
  }

  static valueWithRect_(rect: CGRect): NSValue {
    const __ret = __dispatch.aw_ts_msg_R_P(NSValue.__cls, __sel('valueWithRect:'), rect);
    return __wrapRetained(NSValue, __ret)!;
  }

  static valueWithEdgeInsets_(insets: NSEdgeInsets): NSValue {
    const __ret = __dispatch.aw_ts_msg_E_P(NSValue.__cls, __sel('valueWithEdgeInsets:'), insets);
    return __wrapRetained(NSValue, __ret)!;
  }

  static supportsSecureCoding(): boolean {
    return __dispatch.aw_ts_msg_0_b(NSValue.__cls, __sel('supportsSecureCoding'));
  }

  initWithCoder_(coder: NSCoder): this {
    const __ret = __dispatch.aw_ts_msg_P_P_o(__unwrap(this), __sel('initWithCoder:'), __unwrap(coder));
    return __wrapOwned<this>(__ret)!;
  }

  objCType(): string {
    return __dispatch.aw_ts_msg_0_N(__unwrap(this), __sel('objCType'));
  }

  isEqualToValue_(value: NSValue): boolean {
    return __dispatch.aw_ts_msg_P_b(__unwrap(this), __sel('isEqualToValue:'), __unwrap(value));
  }

  nonretainedObjectValue(): NSObject {
    const __ret = __dispatch.aw_ts_msg_0_P(__unwrap(this), __sel('nonretainedObjectValue'));
    return __wrapRetained(__ret)!;
  }

  rangeValue(): NSRange {
    return __dispatch.aw_ts_msg_0_G(__unwrap(this), __sel('rangeValue'));
  }

  pointValue(): CGPoint {
    return __dispatch.aw_ts_msg_0_O(__unwrap(this), __sel('pointValue'));
  }

  sizeValue(): CGSize {
    return __dispatch.aw_ts_msg_0_Z(__unwrap(this), __sel('sizeValue'));
  }

  rectValue(): CGRect {
    return __dispatch.aw_ts_msg_0_R(__unwrap(this), __sel('rectValue'));
  }

  edgeInsetsValue(): NSEdgeInsets {
    return __dispatch.aw_ts_msg_0_E(__unwrap(this), __sel('edgeInsetsValue'));
  }

  encodeWithCoder_(coder: NSCoder): void {
    __dispatch.aw_ts_msg_P_v(__unwrap(this), __sel('encodeWithCoder:'), __unwrap(coder));
  }

  init(): this {
    return __init(this);
  }
}
