//! Enum emission — each ObjC `NS_ENUM`/`NS_OPTIONS` → a real TS **`enum`** (ADR-0055 §6).
//!
//! Enums are the one top-level construct whose **value is in the IR** (`EnumValue.value`),
//! so — unlike constants (runtime-read C globals) — an enum member is a true compile-time
//! literal. TypeScript's `enum` gives the best member discoverability
//! (`NSComparisonResult.NSOrderedAscending`) and matches NativeScript's surface. Two idiom
//! choices fix the output:
//!
//! 1. **Plain `export enum`, never `const enum`.** A `const enum` inlines its members and
//!    is erased at emit, which breaks `isolatedModules` and most bundlers (ADR-0055 §6). A
//!    plain `enum` carries **both** a runtime object **and** a type, so it emits into
//!    `enums.ts` **and** its co-generated `enums.d.ts` — whose bodies are **identical**
//!    (a member *is* its value), the trivially-non-drifting realization of ADR-0055 §2's
//!    one-pass-drives-both invariant. Member and enum names are the ObjC spellings verbatim
//!    (`NSOrderedAscending`, `NSComparisonResult`). No collision machinery is needed on
//!    either axis: TS enum members are **scoped to their enum** (unlike the Lisp targets'
//!    global `defconstant`s, so no *member*-name dedup), and the extractor already dedups
//!    enum *names* within a framework (`extract-objc`'s `seen_enums`, like class names), so
//!    no name clash reaches here. The one name that is *not* a valid TS identifier is an
//!    anonymous enum's libclang-synthetic name (`enum (unnamed at …)`); [`is_emittable_enum`]
//!    **skips** those so the module is always valid TS — projecting their *values* as plain
//!    module constants is the constants surface's job (a later leaf), not a garbage-named enum.
//!
//! 2. **Width/signedness reinterpretation** (ported from `emit-sbcl/src/emit_enums.rs` for
//!    cross-target consistency). `EnumValue.value` is an `i64`. This branch reinterprets an
//!    unsigned enum's *negative* `i64` (a high-bit value) as its unsigned reading, masked to
//!    the `underlying_primitive` width; a signed enum emits the `i64` verbatim. **It is a
//!    defensive net, not a path the current ObjC pipeline exercises:** `extract-objc` already
//!    resolves an unsigned enum constant from its `u64` component to a *positive* `i64`
//!    (`extract_declarations.rs`), and **skips** a value ≥ `2^63` with a `warn` rather than
//!    storing a negative — so an ObjC-sourced unsigned enum value is never negative here. The
//!    reinterpretation keeps the emitter correct under hand-authored/non-ObjC/future IR (and
//!    matches sbcl); the upstream drop of ≥ `2^63` members is an extractor limitation this
//!    emitter cannot recover.
//!
//! ## The 64-bit precision caveat (first-pass, documented)
//!
//! A TS `enum` member is a `number`, so a reinterpreted value above `2^53` (e.g. a `uint64`
//! `NS_OPTIONS` high bit `1 << 63`) loses precision — the same 64-bit limitation
//! [`crate::ffi_type_mapping`] already flags for `int64`/`uint64` → `number`. The
//! representable range (small values, low bit-flags) is exact; the rare `>2^53` sentinel is
//! imprecise. A `bigint`-backed enum is not expressible as a TS `enum`, so this is accepted
//! as the known first-pass limit, not solved here.
//!
//! Enums cross no ABI, so there is no `objc_exposed` direct/trampoline split (ADR-0026 §3,
//! the enum carve-out) — every enum emits regardless.

use apianyware_emit::code_writer::CodeWriter;
use apianyware_emit::write_line;
use apianyware_types::ir::Enum;
use apianyware_types::type_ref::{TypeRef, TypeRefKind};

use crate::naming::{is_valid_ts_identifier, module_specifier};

/// Render a framework's enums as the **`enums.ts`** module — the banner plus one
/// `export enum` per [`Enum`], carrying the runtime enum objects.
pub fn render_enums_module(enums: &[Enum], framework: &str) -> String {
    let mut w = CodeWriter::new();
    w.line("// Generated by apianyware emit-typescript — DO NOT EDIT.");
    write_line!(
        w,
        "// Enums: {framework} (module {})",
        module_specifier(framework)
    );
    w.line("//");
    w.line(
        "// Real TS enums (ADR-0055 §6): named members, integer values; `const enum` is avoided",
    );
    w.line("// (it breaks isolatedModules/bundlers). An enum carries both a runtime object and a");
    w.line("// type, so its .d.ts is co-generated from the same pass with an identical body.");
    w.blank_line();
    w.raw(&render_enum_bodies(enums));
    w.finish()
}

/// Render the co-generated **`enums.d.ts`** — the same [`render_enum_bodies`] the `.ts`
/// carries (an enum member *is* its value, so the two bodies are byte-identical; only the
/// banner differs), the enum realization of ADR-0055 §2's non-drift invariant.
pub fn render_enums_dts(enums: &[Enum], framework: &str) -> String {
    let mut w = CodeWriter::new();
    w.line("// Generated by apianyware emit-typescript — DO NOT EDIT.");
    write_line!(w, "// Type surface: enums ({framework})");
    w.line("//");
    w.line("// Declaration-only .d.ts, co-generated with enums.ts from the same IR pass (ADR-0055");
    w.line("// §2). An enum's member = value, so this body is identical to the enums.ts body —");
    w.line("// runtime and types cannot drift.");
    w.blank_line();
    w.raw(&render_enum_bodies(enums));
    w.finish()
}

/// The shared enum-block body both artifacts carry: one `export enum <Name> { <member> =
/// <value>, … }` per **emittable** enum ([`is_emittable_enum`]), blank-line-separated, in IR
/// order. Empty for an empty (or all-anonymous) enum list — the orchestrator only writes the
/// files when [`emitted_enum_count`] is non-zero. This is the single source both
/// [`render_enums_module`] and [`render_enums_dts`] concatenate onto their banner, so the
/// `.ts` and `.d.ts` bodies provably cannot drift.
fn render_enum_bodies(enums: &[Enum]) -> String {
    let mut w = CodeWriter::new();
    for (i, en) in enums.iter().filter(|en| is_emittable_enum(en)).enumerate() {
        if i > 0 {
            w.blank_line();
        }
        write_line!(w, "export enum {} {{", en.name);
        w.indent();
        for v in &en.values {
            write_line!(
                w,
                "{} = {},",
                v.name,
                format_enum_value(v.value, &en.enum_type)
            );
        }
        w.dedent();
        w.line("}");
    }
    w.finish()
}

/// The number of enums this framework actually emits — those with a valid TS-identifier name
/// ([`is_emittable_enum`]). The orchestrator drives its write decision, its `EmitResult`
/// count, and the barrel re-export off this, so all three agree with [`render_enum_bodies`].
pub fn emitted_enum_count(enums: &[Enum]) -> usize {
    enums.iter().filter(|en| is_emittable_enum(en)).count()
}

/// Whether an enum can be emitted as a TS `enum` — it carries a valid TS-identifier name
/// ([`crate::naming::is_valid_ts_identifier`]). Filters out an anonymous enum libclang names
/// synthetically (`enum (unnamed at …)`), which would otherwise emit uncompilable
/// `export enum enum (unnamed at …) { … }` (module note); its *values* belong to the constants
/// surface (a later leaf), not a garbage-named enum. Shared with [`crate::enum_graph`], whose
/// ownership registry only owns emittable enums (so a name in the registry is a real TS type).
pub fn is_emittable_enum(en: &Enum) -> bool {
    is_valid_ts_identifier(&en.name)
}

// --- value formatting (width/signedness) ---------------------------------------------

/// Format an enum value, reinterpreting an unsigned enum's negative `i64` (a high-bit value)
/// as the unsigned value of its `underlying_primitive` width (module note); a signed enum's
/// `i64` passes through verbatim.
fn format_enum_value(value: i64, enum_type: &TypeRef) -> String {
    if value < 0 && enum_is_unsigned(enum_type) {
        let mask = width_mask(enum_bits(enum_type));
        ((value as u64) & mask).to_string()
    } else {
        value.to_string()
    }
}

/// The lowercased primitive name backing an enum type — direct for a `Primitive` `enum_type`,
/// via `underlying_primitive` for an `Alias`.
fn enum_underlying(enum_type: &TypeRef) -> Option<String> {
    match &enum_type.kind {
        TypeRefKind::Primitive { name } => Some(name.to_ascii_lowercase()),
        TypeRefKind::Alias {
            underlying_primitive,
            ..
        } => underlying_primitive
            .as_ref()
            .map(|s| s.to_ascii_lowercase()),
        _ => None,
    }
}

fn enum_is_unsigned(enum_type: &TypeRef) -> bool {
    matches!(
        enum_underlying(enum_type).as_deref(),
        Some("uint8" | "uint16" | "uint32" | "uint64" | "nsuinteger")
    )
}

/// The enum's bit width; defaults to 64 (`nsuinteger`/`uint64`/unknown).
fn enum_bits(enum_type: &TypeRef) -> u32 {
    match enum_underlying(enum_type).as_deref() {
        Some("uint8" | "int8") => 8,
        Some("uint16" | "int16") => 16,
        Some("uint32" | "int32") => 32,
        _ => 64,
    }
}

fn width_mask(bits: u32) -> u64 {
    if bits >= 64 {
        u64::MAX
    } else {
        (1u64 << bits) - 1
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use apianyware_types::ir::EnumValue;

    fn en(name: &str, underlying: &str, vs: &[(&str, i64)]) -> Enum {
        Enum {
            name: name.into(),
            enum_type: TypeRef {
                nullable: false,
                kind: TypeRefKind::Primitive {
                    name: underlying.into(),
                },
            },
            values: vs
                .iter()
                .map(|(n, v)| EnumValue {
                    name: (*n).into(),
                    value: *v,
                })
                .collect(),
            source: None,
            provenance: None,
            doc_refs: None,
            objc_exposed: true,
        }
    }

    #[test]
    fn signed_enum_emits_verbatim_named_members() {
        let enums = vec![en(
            "NSComparisonResult",
            "int64",
            &[
                ("NSOrderedAscending", -1),
                ("NSOrderedSame", 0),
                ("NSOrderedDescending", 1),
            ],
        )];
        let out = render_enums_module(&enums, "Foundation");
        // Banner + module specifier.
        assert!(out.contains("// Enums: Foundation (module @apianyware/foundation)"));
        // A real `export enum` (not `const enum`), verbatim names, signed values verbatim.
        assert!(out.contains("export enum NSComparisonResult {"));
        assert!(out.contains("  NSOrderedAscending = -1,"), "{out}");
        assert!(out.contains("  NSOrderedSame = 0,"), "{out}");
        assert!(out.contains("  NSOrderedDescending = 1,"), "{out}");
        assert!(out.contains("}\n"));
        // `const enum` is avoided (ADR-0055 §6) — a plain `export enum`, never the erased
        // `export const enum` form (the banner names the rule, so check the decl syntax).
        assert!(!out.contains("export const enum"), "{out}");
    }

    #[test]
    fn unsigned_enum_reinterprets_high_bit_value() {
        // A uint32 NS_OPTIONS "all bits" value arrives as i64 -1; emitting it raw would be a
        // negative flag. Reinterpret to the 32-bit unsigned max (precise, < 2^53).
        let enums = vec![en(
            "NSOptionFlags",
            "uint32",
            &[("NSOptionNone", 0), ("NSOptionAll", -1)],
        )];
        let out = render_enums_module(&enums, "Foundation");
        assert!(out.contains("  NSOptionNone = 0,"), "{out}");
        assert!(out.contains("  NSOptionAll = 4294967295,"), "{out}");
        assert!(!out.contains("= -1,"), "{out}");
    }

    #[test]
    fn unsigned_wide_enum_reinterprets_to_64_bit_max() {
        // The documented >2^53 caveat: the string is deterministic even though the TS number
        // literal is imprecise. A uint64 -1 → the 64-bit unsigned max.
        let enums = vec![en("NSUIntFlags", "uint64", &[("NSAll", -1)])];
        let out = render_enums_module(&enums, "Foundation");
        assert!(out.contains("  NSAll = 18446744073709551615,"), "{out}");
    }

    #[test]
    fn signed_narrow_enum_keeps_negative() {
        let enums = vec![en("NSSigned", "int32", &[("NSNeg", -5)])];
        let out = render_enums_module(&enums, "Foundation");
        assert!(out.contains("  NSNeg = -5,"), "{out}");
    }

    #[test]
    fn alias_underlying_drives_signedness() {
        // An enum typed as an Alias carrying an unsigned underlying primitive reinterprets
        // just like a direct Primitive uint enum.
        let enums = vec![Enum {
            name: "AXValueType".into(),
            enum_type: TypeRef {
                nullable: false,
                kind: TypeRefKind::Alias {
                    name: "AXValueType".into(),
                    framework: None,
                    underlying_primitive: Some("uint32".into()),
                },
            },
            values: vec![EnumValue {
                name: "kAXAll".into(),
                value: -1,
            }],
            source: None,
            provenance: None,
            doc_refs: None,
            objc_exposed: true,
        }];
        let out = render_enums_module(&enums, "ApplicationServices");
        assert!(out.contains("  kAXAll = 4294967295,"), "{out}");
    }

    #[test]
    fn multiple_enums_are_blank_line_separated_in_ir_order() {
        let enums = vec![
            en("First", "int64", &[("A", 0)]),
            en("Second", "int64", &[("B", 1)]),
        ];
        let out = render_enums_module(&enums, "TestKit");
        let first = out.find("export enum First {").expect("First");
        let second = out.find("export enum Second {").expect("Second");
        assert!(first < second, "IR order preserved:\n{out}");
        // A blank line separates the two blocks.
        assert!(out.contains("}\n\nexport enum Second {"), "{out}");
    }

    #[test]
    fn ts_and_dts_bodies_are_identical() {
        // The ADR-0055 §2 non-drift invariant for enums, made observable: both artifacts
        // concatenate the SAME body onto their banner, so both end with it byte-for-byte.
        let enums = vec![
            en("NSComparisonResult", "int64", &[("NSOrderedSame", 0)]),
            en("NSOptionFlags", "uint32", &[("NSOptionAll", -1)]),
        ];
        let body = render_enum_bodies(&enums);
        assert!(!body.is_empty());
        let ts = render_enums_module(&enums, "Foundation");
        let dts = render_enums_dts(&enums, "Foundation");
        assert!(ts.ends_with(&body), "the .ts body:\n{ts}");
        assert!(dts.ends_with(&body), "the .d.ts body:\n{dts}");
        // The banners genuinely differ (so the equality above is about the body, not the file).
        assert!(ts.contains("// Enums: Foundation"));
        assert!(dts.contains("// Type surface: enums (Foundation)"));
    }

    #[test]
    fn dts_declares_the_same_enums_no_declare_keyword() {
        // The .d.ts uses the same no-`declare` style the class .d.ts uses (ambient-implicit
        // in a declaration file), so it reads identically to the .ts.
        let enums = vec![en("NSComparisonResult", "int64", &[("NSOrderedSame", 0)])];
        let dts = render_enums_dts(&enums, "Foundation");
        assert!(dts.contains("export enum NSComparisonResult {"), "{dts}");
        assert!(!dts.contains("declare"), "{dts}");
    }

    #[test]
    fn empty_enum_list_renders_no_body() {
        // Defensive: the orchestrator only writes the files when the framework has enums, but
        // an empty list still produces a valid banner-only module with no enum blocks.
        assert_eq!(render_enum_bodies(&[]), "");
        assert_eq!(emitted_enum_count(&[]), 0);
        let out = render_enums_module(&[], "TestKit");
        assert!(out.contains("// Enums: TestKit"));
        assert!(!out.contains("export enum"));
    }

    #[test]
    fn anonymous_synthetic_named_enum_is_skipped() {
        // libclang names an anonymous enum `enum (unnamed at …)` — not a valid TS identifier,
        // so emitting it verbatim would be uncompilable TS. It is skipped; a named enum
        // alongside it still emits (and becomes the "first" block — no stray leading blank).
        let anon = en(
            "enum (unnamed at System/Library/Frameworks/Foundation.framework/Headers/FoundationErrors.h:11:1)",
            "int64",
            &[("NSFileNoSuchFileError", 4)],
        );
        let named = en("NSComparisonResult", "int64", &[("NSOrderedSame", 0)]);
        let enums = vec![anon, named];
        assert_eq!(emitted_enum_count(&enums), 1, "only the named enum emits");
        let body = render_enum_bodies(&enums);
        assert!(
            body.starts_with("export enum NSComparisonResult"),
            "the surviving enum is the first block, no leading blank:\n{body}"
        );
        assert!(
            !body.contains("unnamed at"),
            "synthetic name skipped:\n{body}"
        );
        assert!(
            !body.contains("NSFileNoSuchFileError"),
            "anon members skipped:\n{body}"
        );
    }

    #[test]
    fn all_anonymous_enums_emit_nothing() {
        let anon = en("enum (unnamed at Foo.h:3:1)", "int64", &[("kFoo", 1)]);
        let enums = vec![anon];
        assert_eq!(emitted_enum_count(&enums), 0);
        assert_eq!(render_enum_bodies(&enums), "");
    }
}
