;;; Generated Foundation bindings — NSArray — class + dispatch (ADR-0034) — do not edit
(in-package #:apianyware-sbcl-impl)

;; --- NSArray (Foundation) — metaclass-backed class (ADR-0034) ---
(defclass ns:ns-array (ns:ns-object) () (:metaclass objc-class))
(register-objc-class 'ns:ns-array "NSArray" "NSObject")

;; --- NSArray (Foundation) — dispatch (ADR-0034 §2) ---
(defmethod ns:count ((self ns:ns-array))
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:unsigned 64) sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "count")))
(defmethod ns:description ((self ns:ns-array))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "description")) t))
(defmethod ns:first-object ((self ns:ns-array))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "firstObject"))))
(defmethod ns:last-object ((self ns:ns-array))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "lastObject"))))
(defmethod ns:sorted-array-hint ((self ns:ns-array))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "sortedArrayHint")) t))
(defmethod ns:object-at-index_ ((self ns:ns-array) index)
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:unsigned 64))) (aw-ptr self) (aw-sel "objectAtIndex:") index)))
(defmethod ns:array-by-adding-object_ ((self ns:ns-array) an-object)
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "arrayByAddingObject:") (aw-ptr an-object))))
(defmethod ns:array-by-adding-objects-from-array_ ((self ns:ns-array) other-array)
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "arrayByAddingObjectsFromArray:") (aw-ptr other-array))))
(defmethod ns:components-joined-by-string_ ((self ns:ns-array) separator)
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "componentsJoinedByString:") (aw-ptr separator))))
(defmethod ns:contains-object_ ((self ns:ns-array) an-object)
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:boolean 8) sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "containsObject:") (aw-ptr an-object)))
(defmethod ns:description-with-locale_ ((self ns:ns-array) locale)
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "descriptionWithLocale:") (aw-ptr locale))))
(defmethod ns:description-with-locale_indent_ ((self ns:ns-array) locale level)
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:unsigned 64))) (aw-ptr self) (aw-sel "descriptionWithLocale:indent:") (aw-ptr locale) level)))
(defmethod ns:first-object-common-with-array_ ((self ns:ns-array) other-array)
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "firstObjectCommonWithArray:") (aw-ptr other-array))))
(defmethod ns:index-of-object_ ((self ns:ns-array) an-object)
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:unsigned 64) sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "indexOfObject:") (aw-ptr an-object)))
(defmethod ns:index-of-object_in-range_ ((self ns:ns-array) an-object range)
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:unsigned 64) sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:struct ns-range))) (aw-ptr self) (aw-sel "indexOfObject:inRange:") (aw-ptr an-object) range))
(defmethod ns:index-of-object-identical-to_ ((self ns:ns-array) an-object)
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:unsigned 64) sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "indexOfObjectIdenticalTo:") (aw-ptr an-object)))
(defmethod ns:index-of-object-identical-to_in-range_ ((self ns:ns-array) an-object range)
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:unsigned 64) sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:struct ns-range))) (aw-ptr self) (aw-sel "indexOfObjectIdenticalTo:inRange:") (aw-ptr an-object) range))
(defmethod ns:is-equal-to-array_ ((self ns:ns-array) other-array)
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:boolean 8) sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "isEqualToArray:") (aw-ptr other-array)))
(defmethod ns:object-enumerator ((self ns:ns-array))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "objectEnumerator"))))
(defmethod ns:reverse-object-enumerator ((self ns:ns-array))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "reverseObjectEnumerator"))))
(defmethod ns:sorted-array-using-selector_ ((self ns:ns-array) comparator)
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "sortedArrayUsingSelector:") (aw-sel comparator))))
(defmethod ns:subarray-with-range_ ((self ns:ns-array) range)
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:struct ns-range))) (aw-ptr self) (aw-sel "subarrayWithRange:") range)))
(defmethod ns:write-to-url_error_ ((self ns:ns-array) url)
  (aw-with-error-cell (%err)
    (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:boolean 8) sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "writeToURL:error:") (aw-ptr url) %err)))
(defmethod ns:make-objects-perform-selector_ ((self ns:ns-array) a-selector)
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:void sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "makeObjectsPerformSelector:") (aw-sel a-selector)))
(defmethod ns:make-objects-perform-selector_with-object_ ((self ns:ns-array) a-selector argument)
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:void sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "makeObjectsPerformSelector:withObject:") (aw-sel a-selector) (aw-ptr argument)))
(defmethod ns:objects-at-indexes_ ((self ns:ns-array) indexes)
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "objectsAtIndexes:") (aw-ptr indexes))))
(defmethod ns:object-at-indexed-subscript_ ((self ns:ns-array) idx)
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:unsigned 64))) (aw-ptr self) (aw-sel "objectAtIndexedSubscript:") idx)))
(defmethod ns:enumerate-objects-using-block_ ((self ns:ns-array) block)
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:void sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "enumerateObjectsUsingBlock:") (aw-block block)))
(defmethod ns:enumerate-objects-with-options_using-block_ ((self ns:ns-array) opts block)
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:void sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:unsigned 64) sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "enumerateObjectsWithOptions:usingBlock:") opts (aw-block block)))
(defmethod ns:enumerate-objects-at-indexes_options_using-block_ ((self ns:ns-array) s opts block)
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:void sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:unsigned 64) sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "enumerateObjectsAtIndexes:options:usingBlock:") (aw-ptr s) opts (aw-block block)))
(defmethod ns:index-of-object-passing-test_ ((self ns:ns-array) predicate)
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:unsigned 64) sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "indexOfObjectPassingTest:") (aw-block predicate)))
(defmethod ns:index-of-object-with-options_passing-test_ ((self ns:ns-array) opts predicate)
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:unsigned 64) sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:unsigned 64) sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "indexOfObjectWithOptions:passingTest:") opts (aw-block predicate)))
(defmethod ns:index-of-object-at-indexes_options_passing-test_ ((self ns:ns-array) s opts predicate)
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:unsigned 64) sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:unsigned 64) sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "indexOfObjectAtIndexes:options:passingTest:") (aw-ptr s) opts (aw-block predicate)))
(defmethod ns:indexes-of-objects-passing-test_ ((self ns:ns-array) predicate)
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "indexesOfObjectsPassingTest:") (aw-block predicate))))
(defmethod ns:indexes-of-objects-with-options_passing-test_ ((self ns:ns-array) opts predicate)
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:unsigned 64) sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "indexesOfObjectsWithOptions:passingTest:") opts (aw-block predicate))))
(defmethod ns:indexes-of-objects-at-indexes_options_passing-test_ ((self ns:ns-array) s opts predicate)
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:unsigned 64) sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "indexesOfObjectsAtIndexes:options:passingTest:") (aw-ptr s) opts (aw-block predicate))))
(defmethod ns:sorted-array-using-comparator_ ((self ns:ns-array) cmptr)
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "sortedArrayUsingComparator:") (aw-block cmptr))))
(defmethod ns:sorted-array-with-options_using-comparator_ ((self ns:ns-array) opts cmptr)
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:unsigned 64) sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "sortedArrayWithOptions:usingComparator:") opts (aw-block cmptr))))
(defmethod ns:index-of-object_in-sorted-range_options_using-comparator_ ((self ns:ns-array) obj r opts cmp)
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:unsigned 64) sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:struct ns-range) (sb-alien:unsigned 64) sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "indexOfObject:inSortedRange:options:usingComparator:") (aw-ptr obj) r opts (aw-block cmp)))
(defmethod ns:difference-from-array_with-options_using-equivalence-test_ ((self ns:ns-array) other options block)
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:unsigned 64) sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "differenceFromArray:withOptions:usingEquivalenceTest:") (aw-ptr other) options (aw-block block))))
(defmethod ns:difference-from-array_with-options_ ((self ns:ns-array) other options)
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:unsigned 64))) (aw-ptr self) (aw-sel "differenceFromArray:withOptions:") (aw-ptr other) options)))
(defmethod ns:difference-from-array_ ((self ns:ns-array) other)
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "differenceFromArray:") (aw-ptr other))))
(defmethod ns:array-by-applying-difference_ ((self ns:ns-array) difference)
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "arrayByApplyingDifference:") (aw-ptr difference))))
(defmethod ns:write-to-file_atomically_ ((self ns:ns-array) path use-auxiliary-file)
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:boolean 8) sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:boolean 8))) (aw-ptr self) (aw-sel "writeToFile:atomically:") (aw-ptr path) use-auxiliary-file))
(defmethod ns:write-to-url_atomically_ ((self ns:ns-array) url atomically)
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:boolean 8) sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:boolean 8))) (aw-ptr self) (aw-sel "writeToURL:atomically:") (aw-ptr url) atomically))
(defmethod ns:paths-matching-extensions_ ((self ns:ns-array) filter-types)
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "pathsMatchingExtensions:") (aw-ptr filter-types))))
(defmethod ns:value-for-key_ ((self ns:ns-array) key)
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "valueForKey:") (aw-ptr key))))
(defmethod ns:set-value_for-key_ ((self ns:ns-array) value key)
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:void sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "setValue:forKey:") (aw-ptr value) (aw-ptr key)))
(defmethod ns:remove-observer_from-objects-at-indexes_for-key-path_ ((self ns:ns-array) observer indexes key-path)
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:void sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "removeObserver:fromObjectsAtIndexes:forKeyPath:") (aw-ptr observer) (aw-ptr indexes) (aw-ptr key-path)))
(defmethod ns:remove-observer_for-key-path_ ((self ns:ns-array) observer key-path)
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:void sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "removeObserver:forKeyPath:") (aw-ptr observer) (aw-ptr key-path)))
(defmethod ns:sorted-array-using-descriptors_ ((self ns:ns-array) sort-descriptors)
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "sortedArrayUsingDescriptors:") (aw-ptr sort-descriptors))))
(defmethod ns:filtered-array-using-predicate_ ((self ns:ns-array) predicate)
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "filteredArrayUsingPredicate:") (aw-ptr predicate))))
(defmethod ns:encode-with-coder_ ((self ns:ns-array) coder)
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:void sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "encodeWithCoder:") (aw-ptr coder)))
(defmethod ns:array ((class (eql (find-class 'ns:ns-array))))
  (declare (ignore class))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-class "NSArray") (aw-sel "array"))))
(defmethod ns:array-with-object_ ((class (eql (find-class 'ns:ns-array))) an-object)
  (declare (ignore class))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-class "NSArray") (aw-sel "arrayWithObject:") (aw-ptr an-object))))
(defmethod ns:array-with-array_ ((class (eql (find-class 'ns:ns-array))) array)
  (declare (ignore class))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-class "NSArray") (aw-sel "arrayWithArray:") (aw-ptr array))))
(defmethod ns:array-with-contents-of-url_error_ ((class (eql (find-class 'ns:ns-array))) url)
  (declare (ignore class))
  (aw-with-error-cell (%err)
    (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-class "NSArray") (aw-sel "arrayWithContentsOfURL:error:") (aw-ptr url) %err))))
(defmethod ns:array-with-contents-of-file_ ((class (eql (find-class 'ns:ns-array))) path)
  (declare (ignore class))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-class "NSArray") (aw-sel "arrayWithContentsOfFile:") (aw-ptr path))))
(defmethod ns:array-with-contents-of-url_ ((class (eql (find-class 'ns:ns-array))) url)
  (declare (ignore class))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-class "NSArray") (aw-sel "arrayWithContentsOfURL:") (aw-ptr url))))
(defmethod ns:supports-secure-coding ((class (eql (find-class 'ns:ns-array))))
  (declare (ignore class))
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:boolean 8) sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-class "NSArray") (aw-sel "supportsSecureCoding")))
(register-objc-init 'ns:ns-array "initWithCoder:" (:init-with-coder) (lambda (%alloced %args) (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) %alloced (aw-sel "initWithCoder:") (aw-ptr (getf %args :init-with-coder)))))
(register-objc-init 'ns:ns-array "initWithArray:" (:init-with-array) (lambda (%alloced %args) (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) %alloced (aw-sel "initWithArray:") (aw-ptr (getf %args :init-with-array)))))
(register-objc-init 'ns:ns-array "initWithArray:copyItems:" (:init-with-array :copy-items) (lambda (%alloced %args) (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:boolean 8))) %alloced (aw-sel "initWithArray:copyItems:") (aw-ptr (getf %args :init-with-array)) (getf %args :copy-items))))
(register-objc-init 'ns:ns-array "initWithContentsOfFile:" (:init-with-contents-of-file) (lambda (%alloced %args) (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) %alloced (aw-sel "initWithContentsOfFile:") (aw-ptr (getf %args :init-with-contents-of-file)))))
(register-objc-init 'ns:ns-array "initWithContentsOfURL:" (:init-with-contents-of-url) (lambda (%alloced %args) (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) %alloced (aw-sel "initWithContentsOfURL:") (aw-ptr (getf %args :init-with-contents-of-url)))))

;; --- NSArray (Foundation) — Swift-native residual (receiver-handle trampolines, ADR-0038) ---
(defmethod ns:make-iterator ((self ns:ns-array))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_m_Foundation_NSArray_makeIterator" (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self)) t))

