;;; Generated Foundation bindings — NSData — class + dispatch (ADR-0034) — do not edit
(in-package #:apianyware-sbcl-impl)

;; --- NSData (Foundation) — metaclass-backed class (ADR-0034) ---
(defclass ns:ns-data (ns:ns-object) () (:metaclass objc-class))
(register-objc-class 'ns:ns-data "NSData" "NSObject")

;; --- NSData (Foundation) — dispatch (ADR-0034 §2) ---
(defmethod ns:length ((self ns:ns-data))
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:unsigned 64) sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "length")))
(defmethod ns:bytes ((self ns:ns-data))
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "bytes")))
(defmethod ns:description ((self ns:ns-data))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "description")) t))
(defmethod ns:is-equal-to-data_ ((self ns:ns-data) other)
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:boolean 8) sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "isEqualToData:") (aw-ptr other)))
(defmethod ns:subdata-with-range_ ((self ns:ns-data) range)
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:struct ns-range))) (aw-ptr self) (aw-sel "subdataWithRange:") range)))
(defmethod ns:write-to-file_atomically_ ((self ns:ns-data) path use-auxiliary-file)
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:boolean 8) sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:boolean 8))) (aw-ptr self) (aw-sel "writeToFile:atomically:") (aw-ptr path) use-auxiliary-file))
(defmethod ns:write-to-url_atomically_ ((self ns:ns-data) url atomically)
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:boolean 8) sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:boolean 8))) (aw-ptr self) (aw-sel "writeToURL:atomically:") (aw-ptr url) atomically))
(defmethod ns:range-of-data_options_range_ ((self ns:ns-data) data-to-find mask search-range)
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:struct ns-range) sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:unsigned 64) (sb-alien:struct ns-range))) (aw-ptr self) (aw-sel "rangeOfData:options:range:") (aw-ptr data-to-find) mask search-range))
(defmethod ns:base64-encoded-string-with-options_ ((self ns:ns-data) options)
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:unsigned 64))) (aw-ptr self) (aw-sel "base64EncodedStringWithOptions:") options)))
(defmethod ns:base64-encoded-data-with-options_ ((self ns:ns-data) options)
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:unsigned 64))) (aw-ptr self) (aw-sel "base64EncodedDataWithOptions:") options)))
(defmethod ns:decompressed-data-using-algorithm_error_ ((self ns:ns-data) algorithm)
  (aw-with-error-cell (%err)
    (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:signed 64) sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "decompressedDataUsingAlgorithm:error:") algorithm %err))))
(defmethod ns:compressed-data-using-algorithm_error_ ((self ns:ns-data) algorithm)
  (aw-with-error-cell (%err)
    (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:signed 64) sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "compressedDataUsingAlgorithm:error:") algorithm %err))))
(defmethod ns:encode-with-coder_ ((self ns:ns-data) coder)
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:void sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "encodeWithCoder:") (aw-ptr coder)))
(defmethod ns:data ((class (eql (find-class 'ns:ns-data))))
  (declare (ignore class))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-class "NSData") (aw-sel "data"))))
(defmethod ns:data-with-contents-of-file_ ((class (eql (find-class 'ns:ns-data))) path)
  (declare (ignore class))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-class "NSData") (aw-sel "dataWithContentsOfFile:") (aw-ptr path))))
(defmethod ns:data-with-contents-of-url_ ((class (eql (find-class 'ns:ns-data))) url)
  (declare (ignore class))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-class "NSData") (aw-sel "dataWithContentsOfURL:") (aw-ptr url))))
(defmethod ns:data-with-data_ ((class (eql (find-class 'ns:ns-data))) data)
  (declare (ignore class))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-class "NSData") (aw-sel "dataWithData:") (aw-ptr data))))
(defmethod ns:supports-secure-coding ((class (eql (find-class 'ns:ns-data))))
  (declare (ignore class))
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:boolean 8) sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-class "NSData") (aw-sel "supportsSecureCoding")))
(register-objc-init 'ns:ns-data "initWithContentsOfFile:" (:init-with-contents-of-file) (lambda (%alloced %args) (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) %alloced (aw-sel "initWithContentsOfFile:") (aw-ptr (getf %args :init-with-contents-of-file)))))
(register-objc-init 'ns:ns-data "initWithContentsOfURL:" (:init-with-contents-of-url) (lambda (%alloced %args) (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) %alloced (aw-sel "initWithContentsOfURL:") (aw-ptr (getf %args :init-with-contents-of-url)))))
(register-objc-init 'ns:ns-data "initWithData:" (:init-with-data) (lambda (%alloced %args) (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) %alloced (aw-sel "initWithData:") (aw-ptr (getf %args :init-with-data)))))
(register-objc-init 'ns:ns-data "initWithBase64EncodedString:options:" (:init-with-base64-encoded-string :options) (lambda (%alloced %args) (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:unsigned 64))) %alloced (aw-sel "initWithBase64EncodedString:options:") (aw-ptr (getf %args :init-with-base64-encoded-string)) (getf %args :options))))
(register-objc-init 'ns:ns-data "initWithBase64EncodedData:options:" (:init-with-base64-encoded-data :options) (lambda (%alloced %args) (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:unsigned 64))) %alloced (aw-sel "initWithBase64EncodedData:options:") (aw-ptr (getf %args :init-with-base64-encoded-data)) (getf %args :options))))

