;;; Generated Foundation bindings — NSError — class + dispatch (ADR-0034) — do not edit
(in-package #:apianyware-sbcl-impl)

;; --- NSError (Foundation) — metaclass-backed class (ADR-0034) ---
(defclass ns:ns-error (ns:ns-object) () (:metaclass objc-class))
(register-objc-class 'ns:ns-error "NSError" "NSObject")

;; --- NSError (Foundation) — dispatch (ADR-0034 §2) ---
(defmethod ns:domain ((self ns:ns-error))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "domain")) t))
(defmethod ns:code ((self ns:ns-error))
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:signed 64) sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "code")))
(defmethod ns:user-info ((self ns:ns-error))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "userInfo")) t))
(defmethod ns:localized-description ((self ns:ns-error))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "localizedDescription")) t))
(defmethod ns:localized-failure-reason ((self ns:ns-error))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "localizedFailureReason")) t))
(defmethod ns:localized-recovery-suggestion ((self ns:ns-error))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "localizedRecoverySuggestion")) t))
(defmethod ns:localized-recovery-options ((self ns:ns-error))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "localizedRecoveryOptions")) t))
(defmethod ns:recovery-attempter ((self ns:ns-error))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "recoveryAttempter"))))
(defmethod ns:help-anchor ((self ns:ns-error))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "helpAnchor")) t))
(defmethod ns:underlying-errors ((self ns:ns-error))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "underlyingErrors")) t))
(defmethod ns:encode-with-coder_ ((self ns:ns-error) coder)
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:void sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "encodeWithCoder:") (aw-ptr coder)))
(defmethod ns:error-with-domain_code_user-info_ ((class (eql (find-class 'ns:ns-error))) domain code dict)
  (declare (ignore class))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:signed 64) sb-alien:system-area-pointer)) (aw-class "NSError") (aw-sel "errorWithDomain:code:userInfo:") (aw-ptr domain) code (aw-ptr dict))))
(defmethod ns:set-user-info-value-provider-for-domain_provider_ ((class (eql (find-class 'ns:ns-error))) error-domain provider)
  (declare (ignore class))
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:void sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-class "NSError") (aw-sel "setUserInfoValueProviderForDomain:provider:") (aw-ptr error-domain) (aw-block provider)))
(defmethod ns:supports-secure-coding ((class (eql (find-class 'ns:ns-error))))
  (declare (ignore class))
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:boolean 8) sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-class "NSError") (aw-sel "supportsSecureCoding")))
(register-objc-init 'ns:ns-error "initWithDomain:code:userInfo:" (:init-with-domain :code :user-info) (lambda (%alloced %args) (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:signed 64) sb-alien:system-area-pointer)) %alloced (aw-sel "initWithDomain:code:userInfo:") (aw-ptr (getf %args :init-with-domain)) (getf %args :code) (aw-ptr (getf %args :user-info)))))

