;;; Generated Foundation bindings — NSString — class + dispatch (ADR-0034) — do not edit
(in-package #:apianyware-sbcl-impl)

;; --- NSString (Foundation) — metaclass-backed class (ADR-0034) ---
(defclass ns:ns-string (ns:ns-object) () (:metaclass objc-class))
(register-objc-class 'ns:ns-string "NSString" "NSObject")

;; --- NSString (Foundation) — dispatch (ADR-0034 §2) ---
(defmethod ns:length ((self ns:ns-string))
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:unsigned 64) sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "length")))
(defmethod ns:double-value ((self ns:ns-string))
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:double sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "doubleValue")))
(defmethod ns:float-value ((self ns:ns-string))
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:float sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "floatValue")))
(defmethod ns:int-value ((self ns:ns-string))
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:signed 32) sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "intValue")))
(defmethod ns:integer-value ((self ns:ns-string))
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:signed 64) sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "integerValue")))
(defmethod ns:long-long-value ((self ns:ns-string))
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:signed 64) sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "longLongValue")))
(defmethod ns:bool-value ((self ns:ns-string))
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:boolean 8) sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "boolValue")))
(defmethod ns:uppercase-string ((self ns:ns-string))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "uppercaseString")) t))
(defmethod ns:lowercase-string ((self ns:ns-string))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "lowercaseString")) t))
(defmethod ns:capitalized-string ((self ns:ns-string))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "capitalizedString")) t))
(defmethod ns:localized-uppercase-string ((self ns:ns-string))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "localizedUppercaseString")) t))
(defmethod ns:localized-lowercase-string ((self ns:ns-string))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "localizedLowercaseString")) t))
(defmethod ns:localized-capitalized-string ((self ns:ns-string))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "localizedCapitalizedString")) t))
(defmethod ns:utf8-string ((self ns:ns-string))
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:c-string sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "UTF8String")))
(defmethod ns:fastest-encoding ((self ns:ns-string))
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:unsigned 64) sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "fastestEncoding")))
(defmethod ns:smallest-encoding ((self ns:ns-string))
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:unsigned 64) sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "smallestEncoding")))
(defmethod ns:available-string-encodings ((class (eql (find-class 'ns:ns-string))))
  (declare (ignore class))
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-class "NSString") (aw-sel "availableStringEncodings")))
(defmethod ns:default-c-string-encoding ((class (eql (find-class 'ns:ns-string))))
  (declare (ignore class))
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:unsigned 64) sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-class "NSString") (aw-sel "defaultCStringEncoding")))
(defmethod ns:decomposed-string-with-canonical-mapping ((self ns:ns-string))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "decomposedStringWithCanonicalMapping")) t))
(defmethod ns:precomposed-string-with-canonical-mapping ((self ns:ns-string))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "precomposedStringWithCanonicalMapping")) t))
(defmethod ns:decomposed-string-with-compatibility-mapping ((self ns:ns-string))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "decomposedStringWithCompatibilityMapping")) t))
(defmethod ns:precomposed-string-with-compatibility-mapping ((self ns:ns-string))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "precomposedStringWithCompatibilityMapping")) t))
(defmethod ns:description ((self ns:ns-string))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "description")) t))
(defmethod ns:hash ((self ns:ns-string))
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:unsigned 64) sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "hash")))
(defmethod ns:path-components ((self ns:ns-string))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "pathComponents")) t))
(defmethod ns:absolute-path ((self ns:ns-string))
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:boolean 8) sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "absolutePath")))
(defmethod ns:last-path-component ((self ns:ns-string))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "lastPathComponent")) t))
(defmethod ns:string-by-deleting-last-path-component ((self ns:ns-string))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "stringByDeletingLastPathComponent")) t))
(defmethod ns:path-extension ((self ns:ns-string))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "pathExtension")) t))
(defmethod ns:string-by-deleting-path-extension ((self ns:ns-string))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "stringByDeletingPathExtension")) t))
(defmethod ns:string-by-abbreviating-with-tilde-in-path ((self ns:ns-string))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "stringByAbbreviatingWithTildeInPath")) t))
(defmethod ns:string-by-expanding-tilde-in-path ((self ns:ns-string))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "stringByExpandingTildeInPath")) t))
(defmethod ns:string-by-standardizing-path ((self ns:ns-string))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "stringByStandardizingPath")) t))
(defmethod ns:string-by-resolving-symlinks-in-path ((self ns:ns-string))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "stringByResolvingSymlinksInPath")) t))
(defmethod ns:file-system-representation ((self ns:ns-string))
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:c-string sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "fileSystemRepresentation")))
(defmethod ns:string-by-removing-percent-encoding ((self ns:ns-string))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "stringByRemovingPercentEncoding")) t))
(defmethod ns:character-at-index_ ((self ns:ns-string) index)
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:unsigned 16) sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:unsigned 64))) (aw-ptr self) (aw-sel "characterAtIndex:") index))
(defmethod ns:substring-from-index_ ((self ns:ns-string) from)
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:unsigned 64))) (aw-ptr self) (aw-sel "substringFromIndex:") from)))
(defmethod ns:substring-to-index_ ((self ns:ns-string) to)
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:unsigned 64))) (aw-ptr self) (aw-sel "substringToIndex:") to)))
(defmethod ns:substring-with-range_ ((self ns:ns-string) range)
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:struct ns-range))) (aw-ptr self) (aw-sel "substringWithRange:") range)))
(defmethod ns:compare_ ((self ns:ns-string) string)
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:signed 64) sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "compare:") (aw-ptr string)))
(defmethod ns:compare_options_ ((self ns:ns-string) string mask)
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:signed 64) sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:unsigned 64))) (aw-ptr self) (aw-sel "compare:options:") (aw-ptr string) mask))
(defmethod ns:compare_options_range_ ((self ns:ns-string) string mask range-of-receiver-to-compare)
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:signed 64) sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:unsigned 64) (sb-alien:struct ns-range))) (aw-ptr self) (aw-sel "compare:options:range:") (aw-ptr string) mask range-of-receiver-to-compare))
(defmethod ns:compare_options_range_locale_ ((self ns:ns-string) string mask range-of-receiver-to-compare locale)
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:signed 64) sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:unsigned 64) (sb-alien:struct ns-range) sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "compare:options:range:locale:") (aw-ptr string) mask range-of-receiver-to-compare (aw-ptr locale)))
(defmethod ns:case-insensitive-compare_ ((self ns:ns-string) string)
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:signed 64) sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "caseInsensitiveCompare:") (aw-ptr string)))
(defmethod ns:localized-compare_ ((self ns:ns-string) string)
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:signed 64) sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "localizedCompare:") (aw-ptr string)))
(defmethod ns:localized-case-insensitive-compare_ ((self ns:ns-string) string)
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:signed 64) sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "localizedCaseInsensitiveCompare:") (aw-ptr string)))
(defmethod ns:localized-standard-compare_ ((self ns:ns-string) string)
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:signed 64) sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "localizedStandardCompare:") (aw-ptr string)))
(defmethod ns:is-equal-to-string_ ((self ns:ns-string) a-string)
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:boolean 8) sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "isEqualToString:") (aw-ptr a-string)))
(defmethod ns:has-prefix_ ((self ns:ns-string) str)
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:boolean 8) sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "hasPrefix:") (aw-ptr str)))
(defmethod ns:has-suffix_ ((self ns:ns-string) str)
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:boolean 8) sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "hasSuffix:") (aw-ptr str)))
(defmethod ns:common-prefix-with-string_options_ ((self ns:ns-string) str mask)
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:unsigned 64))) (aw-ptr self) (aw-sel "commonPrefixWithString:options:") (aw-ptr str) mask)))
(defmethod ns:contains-string_ ((self ns:ns-string) str)
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:boolean 8) sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "containsString:") (aw-ptr str)))
(defmethod ns:localized-case-insensitive-contains-string_ ((self ns:ns-string) str)
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:boolean 8) sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "localizedCaseInsensitiveContainsString:") (aw-ptr str)))
(defmethod ns:localized-standard-contains-string_ ((self ns:ns-string) str)
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:boolean 8) sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "localizedStandardContainsString:") (aw-ptr str)))
(defmethod ns:localized-standard-range-of-string_ ((self ns:ns-string) str)
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:struct ns-range) sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "localizedStandardRangeOfString:") (aw-ptr str)))
(defmethod ns:range-of-string_ ((self ns:ns-string) search-string)
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:struct ns-range) sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "rangeOfString:") (aw-ptr search-string)))
(defmethod ns:range-of-string_options_ ((self ns:ns-string) search-string mask)
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:struct ns-range) sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:unsigned 64))) (aw-ptr self) (aw-sel "rangeOfString:options:") (aw-ptr search-string) mask))
(defmethod ns:range-of-string_options_range_ ((self ns:ns-string) search-string mask range-of-receiver-to-search)
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:struct ns-range) sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:unsigned 64) (sb-alien:struct ns-range))) (aw-ptr self) (aw-sel "rangeOfString:options:range:") (aw-ptr search-string) mask range-of-receiver-to-search))
(defmethod ns:range-of-string_options_range_locale_ ((self ns:ns-string) search-string mask range-of-receiver-to-search locale)
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:struct ns-range) sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:unsigned 64) (sb-alien:struct ns-range) sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "rangeOfString:options:range:locale:") (aw-ptr search-string) mask range-of-receiver-to-search (aw-ptr locale)))
(defmethod ns:range-of-character-from-set_ ((self ns:ns-string) search-set)
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:struct ns-range) sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "rangeOfCharacterFromSet:") (aw-ptr search-set)))
(defmethod ns:range-of-character-from-set_options_ ((self ns:ns-string) search-set mask)
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:struct ns-range) sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:unsigned 64))) (aw-ptr self) (aw-sel "rangeOfCharacterFromSet:options:") (aw-ptr search-set) mask))
(defmethod ns:range-of-character-from-set_options_range_ ((self ns:ns-string) search-set mask range-of-receiver-to-search)
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:struct ns-range) sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:unsigned 64) (sb-alien:struct ns-range))) (aw-ptr self) (aw-sel "rangeOfCharacterFromSet:options:range:") (aw-ptr search-set) mask range-of-receiver-to-search))
(defmethod ns:range-of-composed-character-sequence-at-index_ ((self ns:ns-string) index)
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:struct ns-range) sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:unsigned 64))) (aw-ptr self) (aw-sel "rangeOfComposedCharacterSequenceAtIndex:") index))
(defmethod ns:range-of-composed-character-sequences-for-range_ ((self ns:ns-string) range)
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:struct ns-range) sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:struct ns-range))) (aw-ptr self) (aw-sel "rangeOfComposedCharacterSequencesForRange:") range))
(defmethod ns:string-by-appending-string_ ((self ns:ns-string) a-string)
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "stringByAppendingString:") (aw-ptr a-string))))
(defmethod ns:uppercase-string-with-locale_ ((self ns:ns-string) locale)
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "uppercaseStringWithLocale:") (aw-ptr locale))))
(defmethod ns:lowercase-string-with-locale_ ((self ns:ns-string) locale)
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "lowercaseStringWithLocale:") (aw-ptr locale))))
(defmethod ns:capitalized-string-with-locale_ ((self ns:ns-string) locale)
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "capitalizedStringWithLocale:") (aw-ptr locale))))
(defmethod ns:line-range-for-range_ ((self ns:ns-string) range)
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:struct ns-range) sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:struct ns-range))) (aw-ptr self) (aw-sel "lineRangeForRange:") range))
(defmethod ns:paragraph-range-for-range_ ((self ns:ns-string) range)
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:struct ns-range) sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:struct ns-range))) (aw-ptr self) (aw-sel "paragraphRangeForRange:") range))
(defmethod ns:enumerate-lines-using-block_ ((self ns:ns-string) block)
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:void sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "enumerateLinesUsingBlock:") (aw-block block)))
(defmethod ns:data-using-encoding_allow-lossy-conversion_ ((self ns:ns-string) encoding lossy)
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:unsigned 64) (sb-alien:boolean 8))) (aw-ptr self) (aw-sel "dataUsingEncoding:allowLossyConversion:") encoding lossy)))
(defmethod ns:data-using-encoding_ ((self ns:ns-string) encoding)
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:unsigned 64))) (aw-ptr self) (aw-sel "dataUsingEncoding:") encoding)))
(defmethod ns:can-be-converted-to-encoding_ ((self ns:ns-string) encoding)
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:boolean 8) sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:unsigned 64))) (aw-ptr self) (aw-sel "canBeConvertedToEncoding:") encoding))
(defmethod ns:c-string-using-encoding_ ((self ns:ns-string) encoding)
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:c-string sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:unsigned 64))) (aw-ptr self) (aw-sel "cStringUsingEncoding:") encoding))
(defmethod ns:maximum-length-of-bytes-using-encoding_ ((self ns:ns-string) enc)
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:unsigned 64) sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:unsigned 64))) (aw-ptr self) (aw-sel "maximumLengthOfBytesUsingEncoding:") enc))
(defmethod ns:length-of-bytes-using-encoding_ ((self ns:ns-string) enc)
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:unsigned 64) sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:unsigned 64))) (aw-ptr self) (aw-sel "lengthOfBytesUsingEncoding:") enc))
(defmethod ns:components-separated-by-string_ ((self ns:ns-string) separator)
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "componentsSeparatedByString:") (aw-ptr separator))))
(defmethod ns:components-separated-by-characters-in-set_ ((self ns:ns-string) separator)
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "componentsSeparatedByCharactersInSet:") (aw-ptr separator))))
(defmethod ns:string-by-trimming-characters-in-set_ ((self ns:ns-string) set)
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "stringByTrimmingCharactersInSet:") (aw-ptr set))))
(defmethod ns:string-by-padding-to-length_with-string_starting-at-index_ ((self ns:ns-string) new-length pad-string pad-index)
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:unsigned 64) sb-alien:system-area-pointer (sb-alien:unsigned 64))) (aw-ptr self) (aw-sel "stringByPaddingToLength:withString:startingAtIndex:") new-length (aw-ptr pad-string) pad-index)))
(defmethod ns:string-by-folding-with-options_locale_ ((self ns:ns-string) options locale)
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:unsigned 64) sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "stringByFoldingWithOptions:locale:") options (aw-ptr locale))))
(defmethod ns:string-by-replacing-occurrences-of-string_with-string_options_range_ ((self ns:ns-string) target replacement options search-range)
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:unsigned 64) (sb-alien:struct ns-range))) (aw-ptr self) (aw-sel "stringByReplacingOccurrencesOfString:withString:options:range:") (aw-ptr target) (aw-ptr replacement) options search-range)))
(defmethod ns:string-by-replacing-occurrences-of-string_with-string_ ((self ns:ns-string) target replacement)
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "stringByReplacingOccurrencesOfString:withString:") (aw-ptr target) (aw-ptr replacement))))
(defmethod ns:string-by-replacing-characters-in-range_with-string_ ((self ns:ns-string) range replacement)
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:struct ns-range) sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "stringByReplacingCharactersInRange:withString:") range (aw-ptr replacement))))
(defmethod ns:string-by-applying-transform_reverse_ ((self ns:ns-string) transform reverse)
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:boolean 8))) (aw-ptr self) (aw-sel "stringByApplyingTransform:reverse:") (aw-ptr transform) reverse)))
(defmethod ns:write-to-url_atomically_encoding_error_ ((self ns:ns-string) url use-auxiliary-file enc)
  (aw-with-error-cell (%err)
    (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:boolean 8) sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:boolean 8) (sb-alien:unsigned 64) sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "writeToURL:atomically:encoding:error:") (aw-ptr url) use-auxiliary-file enc %err)))
(defmethod ns:write-to-file_atomically_encoding_error_ ((self ns:ns-string) path use-auxiliary-file enc)
  (aw-with-error-cell (%err)
    (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:boolean 8) sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:boolean 8) (sb-alien:unsigned 64) sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "writeToFile:atomically:encoding:error:") (aw-ptr path) use-auxiliary-file enc %err)))
(defmethod ns:property-list ((self ns:ns-string))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "propertyList"))))
(defmethod ns:property-list-from-strings-file-format ((self ns:ns-string))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "propertyListFromStringsFileFormat"))))
(defmethod ns:variant-fitting-presentation-width_ ((self ns:ns-string) width)
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:signed 64))) (aw-ptr self) (aw-sel "variantFittingPresentationWidth:") width)))
(defmethod ns:string-by-appending-path-component_ ((self ns:ns-string) str)
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "stringByAppendingPathComponent:") (aw-ptr str))))
(defmethod ns:string-by-appending-path-extension_ ((self ns:ns-string) str)
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "stringByAppendingPathExtension:") (aw-ptr str))))
(defmethod ns:strings-by-appending-paths_ ((self ns:ns-string) paths)
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "stringsByAppendingPaths:") (aw-ptr paths))))
(defmethod ns:is-absolute-path ((self ns:ns-string))
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:boolean 8) sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "isAbsolutePath")))
(defmethod ns:string-by-adding-percent-encoding-with-allowed-characters_ ((self ns:ns-string) allowed-characters)
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "stringByAddingPercentEncodingWithAllowedCharacters:") (aw-ptr allowed-characters))))
(defmethod ns:encode-with-coder_ ((self ns:ns-string) coder)
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:void sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "encodeWithCoder:") (aw-ptr coder)))
(defmethod ns:item-provider-visibility-for-representation-with-type-identifier_ ((self ns:ns-string) type-identifier)
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:signed 64) sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "itemProviderVisibilityForRepresentationWithTypeIdentifier:") (aw-ptr type-identifier)))
(defmethod ns:load-data-with-type-identifier_for-item-provider-completion-handler_ ((self ns:ns-string) type-identifier completion-handler)
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "loadDataWithTypeIdentifier:forItemProviderCompletionHandler:") (aw-ptr type-identifier) (aw-block completion-handler))))
(defmethod ns:writable-type-identifiers-for-item-provider ((self ns:ns-string))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "writableTypeIdentifiersForItemProvider"))))
(defmethod ns:localized-name-of-string-encoding_ ((class (eql (find-class 'ns:ns-string))) encoding)
  (declare (ignore class))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:unsigned 64))) (aw-class "NSString") (aw-sel "localizedNameOfStringEncoding:") encoding)))
(defmethod ns:string ((class (eql (find-class 'ns:ns-string))))
  (declare (ignore class))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-class "NSString") (aw-sel "string"))))
(defmethod ns:string-with-string_ ((class (eql (find-class 'ns:ns-string))) string)
  (declare (ignore class))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-class "NSString") (aw-sel "stringWithString:") (aw-ptr string))))
(defmethod ns:string-with-utf8-string_ ((class (eql (find-class 'ns:ns-string))) null-terminated-c-string)
  (declare (ignore class))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:c-string)) (aw-class "NSString") (aw-sel "stringWithUTF8String:") null-terminated-c-string)))
(defmethod ns:string-with-c-string_encoding_ ((class (eql (find-class 'ns:ns-string))) c-string enc)
  (declare (ignore class))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:c-string (sb-alien:unsigned 64))) (aw-class "NSString") (aw-sel "stringWithCString:encoding:") c-string enc)))
(defmethod ns:string-with-contents-of-url_encoding_error_ ((class (eql (find-class 'ns:ns-string))) url enc)
  (declare (ignore class))
  (aw-with-error-cell (%err)
    (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:unsigned 64) sb-alien:system-area-pointer)) (aw-class "NSString") (aw-sel "stringWithContentsOfURL:encoding:error:") (aw-ptr url) enc %err))))
(defmethod ns:string-with-contents-of-file_encoding_error_ ((class (eql (find-class 'ns:ns-string))) path enc)
  (declare (ignore class))
  (aw-with-error-cell (%err)
    (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:unsigned 64) sb-alien:system-area-pointer)) (aw-class "NSString") (aw-sel "stringWithContentsOfFile:encoding:error:") (aw-ptr path) enc %err))))
(defmethod ns:path-with-components_ ((class (eql (find-class 'ns:ns-string))) components)
  (declare (ignore class))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-class "NSString") (aw-sel "pathWithComponents:") (aw-ptr components))))
(defmethod ns:object-with-item-provider-data_type-identifier_error_ ((class (eql (find-class 'ns:ns-string))) data type-identifier)
  (declare (ignore class))
  (aw-with-error-cell (%err)
    (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-class "NSString") (aw-sel "objectWithItemProviderData:typeIdentifier:error:") (aw-ptr data) (aw-ptr type-identifier) %err))))
(defmethod ns:readable-type-identifiers-for-item-provider ((class (eql (find-class 'ns:ns-string))))
  (declare (ignore class))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-class "NSString") (aw-sel "readableTypeIdentifiersForItemProvider"))))
(defmethod ns:supports-secure-coding ((class (eql (find-class 'ns:ns-string))))
  (declare (ignore class))
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:boolean 8) sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-class "NSString") (aw-sel "supportsSecureCoding")))
(register-objc-init 'ns:ns-string "initWithCoder:" (:init-with-coder) (lambda (%alloced %args) (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) %alloced (aw-sel "initWithCoder:") (aw-ptr (getf %args :init-with-coder)))))
(register-objc-init 'ns:ns-string "initWithUTF8String:" (:init-with-utf8-string) (lambda (%alloced %args) (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:c-string)) %alloced (aw-sel "initWithUTF8String:") (getf %args :init-with-utf8-string))))
(register-objc-init 'ns:ns-string "initWithString:" (:init-with-string) (lambda (%alloced %args) (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) %alloced (aw-sel "initWithString:") (aw-ptr (getf %args :init-with-string)))))
(register-objc-init 'ns:ns-string "initWithData:encoding:" (:init-with-data :encoding) (lambda (%alloced %args) (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:unsigned 64))) %alloced (aw-sel "initWithData:encoding:") (aw-ptr (getf %args :init-with-data)) (getf %args :encoding))))
(register-objc-init 'ns:ns-string "initWithCString:encoding:" (:init-with-c-string :encoding) (lambda (%alloced %args) (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:c-string (sb-alien:unsigned 64))) %alloced (aw-sel "initWithCString:encoding:") (getf %args :init-with-c-string) (getf %args :encoding))))

;; --- NSString (Foundation) — Swift-native residual (receiver-handle trampolines, ADR-0038) ---
(defun ns:make-ns-string-string (string)
  (aw-wrap (sb-alien:alien-funcall (sb-alien:extern-alien "aw_sbcl_swift_init_Foundation_NSString_bd6dd38a" (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-swift-string-arg string)) t))

