;;; Generated Foundation bindings — NSURL — class + dispatch (ADR-0034) — do not edit
(in-package #:apianyware-sbcl-impl)

;; --- NSURL (Foundation) — metaclass-backed class (ADR-0034) ---
(defclass ns:ns-url (ns:ns-object) () (:metaclass objc-class))
(register-objc-class 'ns:ns-url "NSURL" "NSObject")

;; --- NSURL (Foundation) — dispatch (ADR-0034 §2) ---
(defmethod ns:data-representation ((self ns:ns-url))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "dataRepresentation")) t))
(defmethod ns:absolute-string ((self ns:ns-url))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "absoluteString")) t))
(defmethod ns:relative-string ((self ns:ns-url))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "relativeString")) t))
(defmethod ns:base-url ((self ns:ns-url))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "baseURL")) t))
(defmethod ns:absolute-url ((self ns:ns-url))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "absoluteURL")) t))
(defmethod ns:scheme ((self ns:ns-url))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "scheme")) t))
(defmethod ns:resource-specifier ((self ns:ns-url))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "resourceSpecifier")) t))
(defmethod ns:host ((self ns:ns-url))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "host")) t))
(defmethod ns:port ((self ns:ns-url))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "port")) t))
(defmethod ns:user ((self ns:ns-url))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "user")) t))
(defmethod ns:password ((self ns:ns-url))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "password")) t))
(defmethod ns:path ((self ns:ns-url))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "path")) t))
(defmethod ns:fragment ((self ns:ns-url))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "fragment")) t))
(defmethod ns:parameter-string ((self ns:ns-url))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "parameterString")) t))
(defmethod ns:query ((self ns:ns-url))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "query")) t))
(defmethod ns:relative-path ((self ns:ns-url))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "relativePath")) t))
(defmethod ns:has-directory-path ((self ns:ns-url))
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:boolean 8) sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "hasDirectoryPath")))
(defmethod ns:file-system-representation ((self ns:ns-url))
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:c-string sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "fileSystemRepresentation")))
(defmethod ns:file-url ((self ns:ns-url))
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:boolean 8) sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "fileURL")))
(defmethod ns:standardized-url ((self ns:ns-url))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "standardizedURL")) t))
(defmethod ns:file-path-url ((self ns:ns-url))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "filePathURL")) t))
(defmethod ns:path-components ((self ns:ns-url))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "pathComponents")) t))
(defmethod ns:last-path-component ((self ns:ns-url))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "lastPathComponent")) t))
(defmethod ns:path-extension ((self ns:ns-url))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "pathExtension")) t))
(defmethod ns:url-by-deleting-last-path-component ((self ns:ns-url))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "URLByDeletingLastPathComponent")) t))
(defmethod ns:url-by-deleting-path-extension ((self ns:ns-url))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "URLByDeletingPathExtension")) t))
(defmethod ns:url-by-standardizing-path ((self ns:ns-url))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "URLByStandardizingPath")) t))
(defmethod ns:url-by-resolving-symlinks-in-path ((self ns:ns-url))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "URLByResolvingSymlinksInPath")) t))
(defmethod ns:init-file-url-with-path_is-directory_relative-to-url_ ((self ns:ns-url) path is-dir base-url)
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:boolean 8) sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "initFileURLWithPath:isDirectory:relativeToURL:") (aw-ptr path) is-dir (aw-ptr base-url)) t))
(defmethod ns:init-file-url-with-path_relative-to-url_ ((self ns:ns-url) path base-url)
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "initFileURLWithPath:relativeToURL:") (aw-ptr path) (aw-ptr base-url)) t))
(defmethod ns:init-file-url-with-path_is-directory_ ((self ns:ns-url) path is-dir)
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:boolean 8))) (aw-ptr self) (aw-sel "initFileURLWithPath:isDirectory:") (aw-ptr path) is-dir) t))
(defmethod ns:init-file-url-with-path_ ((self ns:ns-url) path)
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "initFileURLWithPath:") (aw-ptr path)) t))
(defmethod ns:init-file-url-with-file-system-representation_is-directory_relative-to-url_ ((self ns:ns-url) path is-dir base-url)
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:c-string (sb-alien:boolean 8) sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "initFileURLWithFileSystemRepresentation:isDirectory:relativeToURL:") path is-dir (aw-ptr base-url)) t))
(defmethod ns:init-absolute-url-with-data-representation_relative-to-url_ ((self ns:ns-url) data base-url)
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "initAbsoluteURLWithDataRepresentation:relativeToURL:") (aw-ptr data) (aw-ptr base-url)) t))
(defmethod ns:is-file-reference-url ((self ns:ns-url))
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:boolean 8) sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "isFileReferenceURL")))
(defmethod ns:file-reference-url ((self ns:ns-url))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "fileReferenceURL"))))
(defmethod ns:resource-values-for-keys_error_ ((self ns:ns-url) keys)
  (aw-with-error-cell (%err)
    (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "resourceValuesForKeys:error:") (aw-ptr keys) %err))))
(defmethod ns:set-resource-value_for-key_error_ ((self ns:ns-url) value key)
  (aw-with-error-cell (%err)
    (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:boolean 8) sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "setResourceValue:forKey:error:") (aw-ptr value) (aw-ptr key) %err)))
(defmethod ns:set-resource-values_error_ ((self ns:ns-url) keyed-values)
  (aw-with-error-cell (%err)
    (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:boolean 8) sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "setResourceValues:error:") (aw-ptr keyed-values) %err)))
(defmethod ns:remove-cached-resource-value-for-key_ ((self ns:ns-url) key)
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:void sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "removeCachedResourceValueForKey:") (aw-ptr key)))
(defmethod ns:remove-all-cached-resource-values ((self ns:ns-url))
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:void sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "removeAllCachedResourceValues")))
(defmethod ns:set-temporary-resource-value_for-key_ ((self ns:ns-url) value key)
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:void sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "setTemporaryResourceValue:forKey:") (aw-ptr value) (aw-ptr key)))
(defmethod ns:bookmark-data-with-options_including-resource-values-for-keys_relative-to-url_error_ ((self ns:ns-url) options keys relative-url)
  (aw-with-error-cell (%err)
    (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:unsigned 64) sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "bookmarkDataWithOptions:includingResourceValuesForKeys:relativeToURL:error:") options (aw-ptr keys) (aw-ptr relative-url) %err))))
(defmethod ns:start-accessing-security-scoped-resource ((self ns:ns-url))
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:boolean 8) sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "startAccessingSecurityScopedResource")))
(defmethod ns:stop-accessing-security-scoped-resource ((self ns:ns-url))
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:void sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "stopAccessingSecurityScopedResource")))
(defmethod ns:is-file-url ((self ns:ns-url))
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:boolean 8) sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "isFileURL")))
(defmethod ns:promised-item-resource-values-for-keys_error_ ((self ns:ns-url) keys)
  (aw-with-error-cell (%err)
    (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "promisedItemResourceValuesForKeys:error:") (aw-ptr keys) %err))))
(defmethod ns:check-promised-item-is-reachable-and-return-error_ ((self ns:ns-url))
  (aw-with-error-cell (%err)
    (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:boolean 8) sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "checkPromisedItemIsReachableAndReturnError:") %err)))
(defmethod ns:url-by-appending-path-component_ ((self ns:ns-url) path-component)
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "URLByAppendingPathComponent:") (aw-ptr path-component))))
(defmethod ns:url-by-appending-path-component_is-directory_ ((self ns:ns-url) path-component is-directory)
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:boolean 8))) (aw-ptr self) (aw-sel "URLByAppendingPathComponent:isDirectory:") (aw-ptr path-component) is-directory)))
(defmethod ns:url-by-appending-path-extension_ ((self ns:ns-url) path-extension)
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "URLByAppendingPathExtension:") (aw-ptr path-extension))))
(defmethod ns:check-resource-is-reachable-and-return-error_ ((self ns:ns-url))
  (aw-with-error-cell (%err)
    (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:boolean 8) sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "checkResourceIsReachableAndReturnError:") %err)))
(defmethod ns:encode-with-coder_ ((self ns:ns-url) coder)
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:void sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "encodeWithCoder:") (aw-ptr coder)))
(defmethod ns:item-provider-visibility-for-representation-with-type-identifier_ ((self ns:ns-url) type-identifier)
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:signed 64) sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "itemProviderVisibilityForRepresentationWithTypeIdentifier:") (aw-ptr type-identifier)))
(defmethod ns:load-data-with-type-identifier_for-item-provider-completion-handler_ ((self ns:ns-url) type-identifier completion-handler)
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "loadDataWithTypeIdentifier:forItemProviderCompletionHandler:") (aw-ptr type-identifier) (aw-block completion-handler))))
(defmethod ns:writable-type-identifiers-for-item-provider ((self ns:ns-url))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-ptr self) (aw-sel "writableTypeIdentifiersForItemProvider"))))
(defmethod ns:file-url-with-path_is-directory_relative-to-url_ ((class (eql (find-class 'ns:ns-url))) path is-dir base-url)
  (declare (ignore class))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:boolean 8) sb-alien:system-area-pointer)) (aw-class "NSURL") (aw-sel "fileURLWithPath:isDirectory:relativeToURL:") (aw-ptr path) is-dir (aw-ptr base-url))))
(defmethod ns:file-url-with-path_relative-to-url_ ((class (eql (find-class 'ns:ns-url))) path base-url)
  (declare (ignore class))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-class "NSURL") (aw-sel "fileURLWithPath:relativeToURL:") (aw-ptr path) (aw-ptr base-url))))
(defmethod ns:file-url-with-path_is-directory_ ((class (eql (find-class 'ns:ns-url))) path is-dir)
  (declare (ignore class))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:boolean 8))) (aw-class "NSURL") (aw-sel "fileURLWithPath:isDirectory:") (aw-ptr path) is-dir)))
(defmethod ns:file-url-with-path_ ((class (eql (find-class 'ns:ns-url))) path)
  (declare (ignore class))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-class "NSURL") (aw-sel "fileURLWithPath:") (aw-ptr path))))
(defmethod ns:file-url-with-file-system-representation_is-directory_relative-to-url_ ((class (eql (find-class 'ns:ns-url))) path is-dir base-url)
  (declare (ignore class))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:c-string (sb-alien:boolean 8) sb-alien:system-area-pointer)) (aw-class "NSURL") (aw-sel "fileURLWithFileSystemRepresentation:isDirectory:relativeToURL:") path is-dir (aw-ptr base-url))))
(defmethod ns:url-with-string_ ((class (eql (find-class 'ns:ns-url))) url-string)
  (declare (ignore class))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-class "NSURL") (aw-sel "URLWithString:") (aw-ptr url-string))))
(defmethod ns:url-with-string_relative-to-url_ ((class (eql (find-class 'ns:ns-url))) url-string base-url)
  (declare (ignore class))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-class "NSURL") (aw-sel "URLWithString:relativeToURL:") (aw-ptr url-string) (aw-ptr base-url))))
(defmethod ns:url-with-string_encoding-invalid-characters_ ((class (eql (find-class 'ns:ns-url))) url-string encoding-invalid-characters)
  (declare (ignore class))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:boolean 8))) (aw-class "NSURL") (aw-sel "URLWithString:encodingInvalidCharacters:") (aw-ptr url-string) encoding-invalid-characters)))
(defmethod ns:url-with-data-representation_relative-to-url_ ((class (eql (find-class 'ns:ns-url))) data base-url)
  (declare (ignore class))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-class "NSURL") (aw-sel "URLWithDataRepresentation:relativeToURL:") (aw-ptr data) (aw-ptr base-url))))
(defmethod ns:absolute-url-with-data-representation_relative-to-url_ ((class (eql (find-class 'ns:ns-url))) data base-url)
  (declare (ignore class))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-class "NSURL") (aw-sel "absoluteURLWithDataRepresentation:relativeToURL:") (aw-ptr data) (aw-ptr base-url))))
(defmethod ns:resource-values-for-keys_from-bookmark-data_ ((class (eql (find-class 'ns:ns-url))) keys bookmark-data)
  (declare (ignore class))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-class "NSURL") (aw-sel "resourceValuesForKeys:fromBookmarkData:") (aw-ptr keys) (aw-ptr bookmark-data))))
(defmethod ns:write-bookmark-data_to-url_options_error_ ((class (eql (find-class 'ns:ns-url))) bookmark-data bookmark-file-url options)
  (declare (ignore class))
  (aw-with-error-cell (%err)
    (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:boolean 8) sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:unsigned 64) sb-alien:system-area-pointer)) (aw-class "NSURL") (aw-sel "writeBookmarkData:toURL:options:error:") (aw-ptr bookmark-data) (aw-ptr bookmark-file-url) options %err)))
(defmethod ns:bookmark-data-with-contents-of-url_error_ ((class (eql (find-class 'ns:ns-url))) bookmark-file-url)
  (declare (ignore class))
  (aw-with-error-cell (%err)
    (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-class "NSURL") (aw-sel "bookmarkDataWithContentsOfURL:error:") (aw-ptr bookmark-file-url) %err))))
(defmethod ns:url-by-resolving-alias-file-at-url_options_error_ ((class (eql (find-class 'ns:ns-url))) url options)
  (declare (ignore class))
  (aw-with-error-cell (%err)
    (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:unsigned 64) sb-alien:system-area-pointer)) (aw-class "NSURL") (aw-sel "URLByResolvingAliasFileAtURL:options:error:") (aw-ptr url) options %err))))
(defmethod ns:file-url-with-path-components_ ((class (eql (find-class 'ns:ns-url))) components)
  (declare (ignore class))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-class "NSURL") (aw-sel "fileURLWithPathComponents:") (aw-ptr components))))
(defmethod ns:object-with-item-provider-data_type-identifier_error_ ((class (eql (find-class 'ns:ns-url))) data type-identifier)
  (declare (ignore class))
  (aw-with-error-cell (%err)
    (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-class "NSURL") (aw-sel "objectWithItemProviderData:typeIdentifier:error:") (aw-ptr data) (aw-ptr type-identifier) %err))))
(defmethod ns:readable-type-identifiers-for-item-provider ((class (eql (find-class 'ns:ns-url))))
  (declare (ignore class))
  (aw-wrap (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-class "NSURL") (aw-sel "readableTypeIdentifiersForItemProvider"))))
(defmethod ns:supports-secure-coding ((class (eql (find-class 'ns:ns-url))))
  (declare (ignore class))
  (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function (sb-alien:boolean 8) sb-alien:system-area-pointer sb-alien:system-area-pointer)) (aw-class "NSURL") (aw-sel "supportsSecureCoding")))
(register-objc-init 'ns:ns-url "initWithString:" (:init-with-string) (lambda (%alloced %args) (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) %alloced (aw-sel "initWithString:") (aw-ptr (getf %args :init-with-string)))))
(register-objc-init 'ns:ns-url "initWithString:relativeToURL:" (:init-with-string :relative-to-url) (lambda (%alloced %args) (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) %alloced (aw-sel "initWithString:relativeToURL:") (aw-ptr (getf %args :init-with-string)) (aw-ptr (getf %args :relative-to-url)))))
(register-objc-init 'ns:ns-url "initWithString:encodingInvalidCharacters:" (:init-with-string :encoding-invalid-characters) (lambda (%alloced %args) (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer (sb-alien:boolean 8))) %alloced (aw-sel "initWithString:encodingInvalidCharacters:") (aw-ptr (getf %args :init-with-string)) (getf %args :encoding-invalid-characters))))
(register-objc-init 'ns:ns-url "initWithDataRepresentation:relativeToURL:" (:init-with-data-representation :relative-to-url) (lambda (%alloced %args) (sb-alien:alien-funcall (sb-alien:sap-alien +objc-msgsend+ (sb-alien:function sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer sb-alien:system-area-pointer)) %alloced (aw-sel "initWithDataRepresentation:relativeToURL:") (aw-ptr (getf %args :init-with-data-representation)) (aw-ptr (getf %args :relative-to-url)))))

