//! Version-resilient bundle entry point.
//!
//! A precompiled chez bundle ships `.so` objects produced by one exact
//! Chez Scheme version (see [`crate::precompile`]). Chez refuses to load a
//! `.so` written by a *different* version — a hard error, not a silent
//! fall-through to source — so a bundle precompiled on the dev host crashes
//! on launch on any machine whose Chez differs (e.g. a freshly provisioned
//! VM where `brew install chezscheme` poured a newer bottle).
//!
//! Rather than couple the bundle to a pinned runtime, the bundler emits a
//! tiny `launch.ss` bootstrap as the stub's `--script` target. It compares
//! the running Chez (`scheme-version-number`) against the version stamped at
//! bundle time and, on mismatch, drops the *object* extension from
//! `library-extensions` so Chez finds only source and compiles it in memory.
//!
//! Why mangle the object extension rather than delete the `.so` files or
//! flip `compile-imported-libraries`:
//!
//! - `library-extensions` is a list of `(source-ext . object-ext)` pairs;
//!   Chez derives each candidate `.so` path from the matching source path.
//!   Rewriting the object half to a non-existent suffix makes every object
//!   lookup miss, so the stale objects are never opened — their version is
//!   irrelevant.
//! - The fallback **writes nothing**: Chez compiles the source in memory
//!   (the same ~75 s cost a non-precompiled bundle pays) without emitting
//!   objects, so the code signature over the bundle stays intact.
//!
//! When versions match the bootstrap is a no-op and the fast `.so` path runs
//! exactly as before. A source-only bundle ([`crate::AppSpec::skip_precompile`])
//! ships no objects, so it is emitted without a version stamp and always
//! loads source.

use std::process::Command;

use crate::bundle::BundleError;

/// Query the version of the Chez at `chez_bin` by parsing `--version`.
///
/// Chez prints e.g. `10.4.1` to stdout. Returns the `(major, minor, sub)`
/// triple, matching `scheme-version-number`'s three values.
pub(crate) fn chez_version(chez_bin: &str) -> Result<(u32, u32, u32), BundleError> {
    let output = Command::new(chez_bin)
        .arg("--version")
        .output()
        .map_err(|e| BundleError::ChezNotAvailable {
            chez_bin: chez_bin.to_string(),
            source: e,
        })?;
    // Chez writes the version to stdout; tolerate stderr too in case a
    // future build flips streams.
    let text = if output.stdout.iter().any(|b| !b.is_ascii_whitespace()) {
        String::from_utf8_lossy(&output.stdout)
    } else {
        String::from_utf8_lossy(&output.stderr)
    };
    parse_version(text.trim()).ok_or_else(|| BundleError::ChezVersion {
        chez_bin: chez_bin.to_string(),
        detail: format!("could not parse a N.N.N version from {text:?}"),
    })
}

/// Parse the leading `major.minor.sub` triple of a Chez `--version` string.
///
/// Each component is the leading run of digits, so a trailing pre-release
/// suffix on the patch component (`10.4.1-rc2`) still parses.
fn parse_version(s: &str) -> Option<(u32, u32, u32)> {
    let mut parts = s.split('.');
    let major = leading_u32(parts.next()?)?;
    let minor = leading_u32(parts.next()?)?;
    let sub = leading_u32(parts.next()?)?;
    Some((major, minor, sub))
}

fn leading_u32(s: &str) -> Option<u32> {
    let digits: String = s.chars().take_while(|c| c.is_ascii_digit()).collect();
    digits.parse().ok()
}

/// Generate the `launch.ss` bootstrap source.
///
/// `entry_rel` is the entry script's path relative to the bundle's
/// `chez-app` libdir (e.g. `apps/note-editor/note-editor.sls`). `stamp` is
/// the precompiling Chez version, or `None` for a source-only bundle.
pub(crate) fn generate_launch_bootstrap(entry_rel: &str, stamp: Option<(u32, u32, u32)>) -> String {
    let entry_lit = scheme_string(entry_rel);
    let mut s = String::with_capacity(1024);

    s.push_str(
        ";; launch.ss — generated by apianyware-macos-bundle-chez. Do not edit.\n\
         ;;\n\
         ;; Version-resilient entry point. See bundle-chez/src/launch.rs and\n\
         ;; knowledge/targets/chez.md for the rationale.\n\n\
         (import (chezscheme))\n\n",
    );

    s.push_str(&format!("(define entry-rel {entry_lit})\n\n"));

    s.push_str(
        "(define libdir\n\
        \x20 (let ([d (car (library-directories))])\n\
        \x20   (if (pair? d) (car d) d)))\n\n",
    );

    if let Some((major, minor, sub)) = stamp {
        s.push_str(&format!(
            ";; This bundle's .so objects were precompiled by Chez {major}.{minor}.{sub}.\n\
             ;; Chez cannot load objects from a different version, so when the running\n\
             ;; Chez differs we drop the object extension from library-extensions: Chez\n\
             ;; then finds only source and compiles it in memory (slower cold start, no\n\
             ;; objects written, signature intact) instead of crashing on the .so load.\n\
             (let-values ([(major minor sub) (scheme-version-number)])\n\
            \x20 (unless (and (= major {major}) (= minor {minor}) (= sub {sub}))\n\
            \x20   (fprintf (current-error-port)\n\
            \x20            \"[apianyware] bundle precompiled by Chez {major}.{minor}.{sub}, but ~a.~a.~a is running; loading source (slower launch)~%\"\n\
            \x20            major minor sub)\n\
            \x20   (library-extensions\n\
            \x20     (map (lambda (p) (cons (car p) (string-append (cdr p) \"-disabled\")))\n\
            \x20          (library-extensions)))))\n\n"
        ));
    } else {
        s.push_str(
            ";; Source-only bundle (skip_precompile): no precompiled objects ship, so\n\
             ;; Chez always compiles source in memory — no version coupling to guard.\n\n",
        );
    }

    s.push_str("(load (string-append libdir \"/\" entry-rel))\n");
    s
}

/// Escape a string for use as a Scheme string literal.
fn scheme_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            _ => out.push(c),
        }
    }
    out.push('"');
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_version_plain() {
        assert_eq!(parse_version("10.4.1"), Some((10, 4, 1)));
    }

    #[test]
    fn parse_version_tolerates_prerelease_suffix() {
        assert_eq!(parse_version("10.4.1-rc2"), Some((10, 4, 1)));
    }

    #[test]
    fn parse_version_rejects_garbage() {
        assert_eq!(parse_version("not-a-version"), None);
        assert_eq!(parse_version("10.4"), None);
    }

    #[test]
    fn scheme_string_escapes_quotes_and_backslashes() {
        assert_eq!(scheme_string(r#"a"b\c"#), r#""a\"b\\c""#);
    }

    #[test]
    fn bootstrap_stamped_guards_version_and_mangles_object_ext() {
        let src = generate_launch_bootstrap("apps/hello-window/hello-window.sls", Some((10, 4, 1)));
        assert!(src.contains(r#"(define entry-rel "apps/hello-window/hello-window.sls")"#));
        assert!(src.contains("(scheme-version-number)"));
        assert!(src.contains("(= major 10)"));
        assert!(src.contains("(= minor 4)"));
        assert!(src.contains("(= sub 1)"));
        assert!(src.contains("-disabled"));
        assert!(src.contains("library-extensions"));
        assert!(src.trim_end().ends_with(r#"(load (string-append libdir "/" entry-rel))"#));
    }

    #[test]
    fn bootstrap_source_only_omits_version_guard() {
        let src = generate_launch_bootstrap("apps/hello-window/hello-window.sls", None);
        assert!(!src.contains("scheme-version-number"));
        assert!(!src.contains("-disabled"));
        assert!(src.contains("Source-only bundle"));
        assert!(src.trim_end().ends_with(r#"(load (string-append libdir "/" entry-rel))"#));
    }
}
